<?xml version="1.0" standalone="no" ?>
<!DOCTYPE DATA [
  <!ELEMENT DATA                     (SOURCE,EXPORT_TYPE,NUM_CLOSINGS,RUN_DATE,RUN_EPOCH,RECORD*)>
  <!ELEMENT SOURCE                   (CDATA)>
  <!ELEMENT EXPORT_TYPE              (CDATA)>
  <!ELEMENT NUM_CLOSINGS             (CDATA)>
  <!ELEMENT RUN_DATE                 (CDATA)>
  <!ELEMENT RUN_EPOCH                (CDATA)>
  <!ELEMENT RECORD                   (REC_ID,FORCED_ORGANIZATION_NAME,ORGANIZATION_NAME1,ORGANIZATION_NAME2,ORGANIZATION_NAME3,ALT_ORGANIZATION_NAME,FORCED_COUNTY_NAME,COUNTY_NAME1,COUNTY_NAME2,ALT_COUNTY_NAME,CAT_CODE,CATEGORY_NAME1,CATEGORY_NAME2,FORCED_STATUS_NAME,STATUS_NAME1,STATUS_NAME2,STATUS_NAME3,ALT_STATUS_TEXT,STATUS_CODE,STATUS2_NAME1,STATUS2_NAME2,STATUS2_NAME3,STATUS_CODE2,EXPIRATION,UPDATED,COMMENTS_LINE1,COMMENTS_LINE2,COMMENTS_LINE3,ADDRESS1,ADDRESS2,CITY,STATE,ZIPCODE,ORGANIZATION_HOMEPAGE)>
  <!ELEMENT REC_ID                   (ID)>
  <!ELEMENT FORCED_ORGANIZATION_NAME (CDATA)>
  <!ELEMENT ORGANIZATION_NAME1       (CDATA)>
  <!ELEMENT ORGANIZATION_NAME2       (CDATA)>
  <!ELEMENT ORGANIZATION_NAME3       (CDATA)>
  <!ELEMENT ALT_ORGANIZATION_NAME    (CDATA)>
  <!ELEMENT FORCED_COUNTY_NAME       (CDATA)>
  <!ELEMENT COUNTY_NAME1             (CDATA)>
  <!ELEMENT COUNTY_NAME2             (CDATA)>
  <!ELEMENT ALT_COUNTY_NAME          (CDATA)>
  <!ELEMENT CAT_CODE                 (CDATA)>
  <!ELEMENT CATEGORY_NAME1           (CDATA)>
  <!ELEMENT CATEGORY_NAME2           (CDATA)>
  <!ELEMENT FORCED_STATUS_NAME       (CDATA)>
  <!ELEMENT STATUS_NAME1             (CDATA)>
  <!ELEMENT STATUS_NAME2             (CDATA)>
  <!ELEMENT STATUS_NAME3             (CDATA)>
  <!ELEMENT ALT_STATUS_TEXT          (CDATA)>
  <!ELEMENT STATUS_CODE              (CDATA)>
  <!ELEMENT STATUS2_NAME1            (CDATA)>
  <!ELEMENT STATUS2_NAME2            (CDATA)>
  <!ELEMENT STATUS2_NAME3            (CDATA)>
  <!ELEMENT STATUS_CODE2             (CDATA)>
  <!ELEMENT EXPIRATION               (CDATA)>
  <!ELEMENT UPDATED                  (CDATA)>
  <!ELEMENT COMMENTS_LINE1           (CDATA)>
  <!ELEMENT COMMENTS_LINE2           (CDATA)>
  <!ELEMENT COMMENTS_LINE3           (CDATA)>
  <!ELEMENT ADDRESS1                 (CDATA)>
  <!ELEMENT ADDRESS2                 (CDATA)>
  <!ELEMENT CITY                     (CDATA)>
  <!ELEMENT STATE                    (CDATA)>
  <!ELEMENT ZIPCODE                  (CDATA)>
  <!ELEMENT ORGANIZATION_HOMEPAGE    (CDATA)>
]>
<DATA>
<SOURCE>NewsTicker</SOURCE>
<EXPORT_TYPE>L2</EXPORT_TYPE>
<NUM_CLOSINGS>1931</NUM_CLOSINGS>
<RUN_DATE>Mon Nov  3 03:03:02 CST 2014</RUN_DATE>
<RUN_EPOCH>1415005382</RUN_EPOCH>
<RECORD>
<REC_ID>10155</REC_ID>
<FORCED_ORGANIZATION_NAME>Arkansas Children&apos;s Hospital Outpatient Clinics</FORCED_ORGANIZATION_NAME>
<ORGANIZATION_NAME1>Arkansas Children&apos;s Hospital Outpatient Clinics</ORGANIZATION_NAME1>
<ORGANIZATION_NAME2></ORGANIZATION_NAME2>
<ORGANIZATION_NAME3></ORGANIZATION_NAME3>
<ALT_ORGANIZATION_NAME></ALT_ORGANIZATION_NAME>
<FORCED_COUNTY_NAME>Pulaski</FORCED_COUNTY_NAME>
<COUNTY_NAME1>Pulaski</COUNTY_NAME1>
<COUNTY_NAME2></COUNTY_NAME2>
<ALT_COUNTY_NAME></ALT_COUNTY_NAME>
<FORCED_CATEGORY_NAME></FORCED_CATEGORY_NAME>
<CAT_CODE></CAT_CODE>
<CATEGORY_NAME1></CATEGORY_NAME1>
<CATEGORY_NAME2></CATEGORY_NAME2>
<FORCED_STATUS_NAME></FORCED_STATUS_NAME>
<STATUS_NAME1></STATUS_NAME1>
<STATUS_NAME2></STATUS_NAME2>
<STATUS_NAME3></STATUS_NAME3>
<ALT_STATUS_TEXT></ALT_STATUS_TEXT>
<STATUS_CODE></STATUS_CODE>
<STATUS2_NAME1></STATUS2_NAME1>
<STATUS2_NAME2></STATUS2_NAME2>
<STATUS2_NAME3></STATUS2_NAME3>
<STATUS_CODE2></STATUS_CODE2>
<EXPIRATION></EXPIRATION>
<UPDATED></UPDATED>
<COMMENTS_LINE1></COMMENTS_LINE1>
<COMMENTS_LINE2></COMMENTS_LINE2>
<COMMENTS_LINE3></COMMENTS_LINE3>
<ADDRESS1></ADDRESS1>
<ADDRESS2></ADDRESS2>
<CITY></CITY>
<STATE>AR</STATE>
<ZIPCODE></ZIPCODE>
<ORGANIZATION_HOMEPAGE></ORGANIZATION_HOMEPAGE>
</RECORD>
<RECORD>
<REC_ID>9703</REC_ID>
<FORCED_ORGANIZATION_NAME>CARTI</FORCED_ORGANIZATION_NAME>
<ORGANIZATION_NAME1>CARTI</ORGANIZATION_NAME1>
<ORGANIZATION_NAME2></ORGANIZATION_NAME2>
<ORGANIZATION_NAME3></ORGANIZATION_NAME3>
<ALT_ORGANIZATION_NAME></ALT_ORGANIZATION_NAME>
<FORCED_COUNTY_NAME>Pulaski</FORCED_COUNTY_NAME>
<COUNTY_NAME1>Pulaski</COUNTY_NAME1>
<COUNTY_NAME2></COUNTY_NAME2>
<ALT_COUNTY_NAME></ALT_COUNTY_NAME>
<FORCED_CATEGORY_NAME></FORCED_CATEGORY_NAME>
<CAT_CODE></CAT_CODE>
<CATEGORY_NAME1></CATEGORY_NAME1>
<CATEGORY_NAME2></CATEGORY_NAME2>
<FORCED_STATUS_NAME></FORCED_STATUS_NAME>
<STATUS_NAME1></STATUS_NAME1>
<STATUS_NAME2></STATUS_NAME2>
<STATUS_NAME3></STATUS_NAME3>
<ALT_STATUS_TEXT></ALT_STATUS_TEXT>
<STATUS_CODE></STATUS_CODE>
<STATUS2_NAME1></STATUS2_NAME1>
<STATUS2_NAME2></STATUS2_NAME2>
<STATUS2_NAME3></STATUS2_NAME3>
<STATUS_CODE2></STATUS_CODE2>
<EXPIRATION></EXPIRATION>
<UPDATED></UPDATED>
<COMMENTS_LINE1></COMMENTS_LINE1>
<COMMENTS_LINE2></COMMENTS_LINE2>
<COMMENTS_LINE3></COMMENTS_LINE3>
<ADDRESS1></ADDRESS1>
<ADDRESS2></ADDRESS2>
<CITY></CITY>
<STATE>AR</STATE>
<ZIPCODE></ZIPCODE>
<ORGANIZATION_HOMEPAGE></ORGANIZATION_HOMEPAGE>
</RECORD>
<RECORD>
<REC_ID>9595</REC_ID>
<FORCED_ORGANIZATION_NAME>Cleburne Co. District Court</FORCED_ORGANIZATION_NAME>
<ORGANIZATION_NAME1>Cleburne Co. District Court</ORGANIZATION_NAME1>
<ORGANIZATION_NAME2></ORGANIZATION_NAME2>
<ORGANIZATION_NAME3></ORGANIZATION_NAME3>
<ALT_ORGANIZATION_NAME></ALT_ORGANIZATION_NAME>
<FORCED_COUNTY_NAME>Cleburne</FORCED_COUNTY_NAME>
<COUNTY_NAME1>Cleburne</COUNTY_NAME1>
<COUNTY_NAME2></COUNTY_NAME2>
<ALT_COUNTY_NAME></ALT_COUNTY_NAME>
<FORCED_CATEGORY_NAME></FORCED_CATEGORY_NAME>
<CAT_CODE></CAT_CODE>
<CATEGORY_NAME1></CATEGORY_NAME1>
<CATEGORY_NAME2></CATEGORY_NAME2>
<FORCED_STATUS_NAME></FORCED_STATUS_NAME>
<STATUS_NAME1></STATUS_NAME1>
<STATUS_NAME2></STATUS_NAME2>
<STATUS_NAME3></STATUS_NAME3>
<ALT_STATUS_TEXT></ALT_STATUS_TEXT>
<STATUS_CODE></STATUS_CODE>
<STATUS2_NAME1></STATUS2_NAME1>
<STATUS2_NAME2></STATUS2_NAME2>
<STATUS2_NAME3></STATUS2_NAME3>
<STATUS_CODE2></STATUS_CODE2>
<EXPIRATION></EXPIRATION>
<UPDATED></UPDATED>
<COMMENTS_LINE1></COMMENTS_LINE1>
<COMMENTS_LINE2></COMMENTS_LINE2>
<COMMENTS_LINE3></COMMENTS_LINE3>
<ADDRESS1></ADDRESS1>
<ADDRESS2></ADDRESS2>
<CITY></CITY>
<STATE>AR</STATE>
<ZIPCODE></ZIPCODE>
<ORGANIZATION_HOMEPAGE></ORGANIZATION_HOMEPAGE>
</RECORD>
<RECORD>
<REC_ID>10063</REC_ID>
<FORCED_ORGANIZATION_NAME>Cross</FORCED_ORGANIZATION_NAME>
<ORGANIZATION_NAME1>Cross</ORGANIZATION_NAME1>
<ORGANIZATION_NAME2></ORGANIZATION_NAME2>
<ORGANIZATION_NAME3></ORGANIZATION_NAME3>
<ALT_ORGANIZATION_NAME></ALT_ORGANIZATION_NAME>
<FORCED_COUNTY_NAME></FORCED_COUNTY_NAME>
<COUNTY_NAME1></COUNTY_NAME1>
<COUNTY_NAME2></COUNTY_NAME2>
<ALT_COUNTY_NAME></ALT_COUNTY_NAME>
<FORCED_CATEGORY_NAME></FORCED_CATEGORY_NAME>
<CAT_CODE></CAT_CODE>
<CATEGORY_NAME1></CATEGORY_NAME1>
<CATEGORY_NAME2></CATEGORY_NAME2>
<FORCED_STATUS_NAME></FORCED_STATUS_NAME>
<STATUS_NAME1></STATUS_NAME1>
<STATUS_NAME2></STATUS_NAME2>
<STATUS_NAME3></STATUS_NAME3>
<ALT_STATUS_TEXT></ALT_STATUS_TEXT>
<STATUS_CODE></STATUS_CODE>
<STATUS2_NAME1></STATUS2_NAME1>
<STATUS2_NAME2></STATUS2_NAME2>
<STATUS2_NAME3></STATUS2_NAME3>
<STATUS_CODE2></STATUS_CODE2>
<EXPIRATION></EXPIRATION>
<UPDATED></UPDATED>
<COMMENTS_LINE1></COMMENTS_LINE1>
<COMMENTS_LINE2></COMMENTS_LINE2>
<COMMENTS_LINE3></COMMENTS_LINE3>
<ADDRESS1></ADDRESS1>
<ADDRESS2></ADDRESS2>
<CITY></CITY>
<STATE>AR</STATE>
<ZIPCODE></ZIPCODE>
<ORGANIZATION_HOMEPAGE></ORGANIZATION_HOMEPAGE>
</RECORD>
<RECORD>
<REC_ID>9563</REC_ID>
<FORCED_ORGANIZATION_NAME>Ozarka College-Baxter County</FORCED_ORGANIZATION_NAME>
<ORGANIZATION_NAME1>Ozarka College-Baxter County</ORGANIZATION_NAME1>
<ORGANIZATION_NAME2></ORGANIZATION_NAME2>
<ORGANIZATION_NAME3></ORGANIZATION_NAME3>
<ALT_ORGANIZATION_NAME></ALT_ORGANIZATION_NAME>
<FORCED_COUNTY_NAME></FORCED_COUNTY_NAME>
<COUNTY_NAME1></COUNTY_NAME1>
<COUNTY_NAME2></COUNTY_NAME2>
<ALT_COUNTY_NAME></ALT_COUNTY_NAME>
<FORCED_CATEGORY_NAME></FORCED_CATEGORY_NAME>
<CAT_CODE></CAT_CODE>
<CATEGORY_NAME1></CATEGORY_NAME1>
<CATEGORY_NAME2></CATEGORY_NAME2>
<FORCED_STATUS_NAME></FORCED_STATUS_NAME>
<STATUS_NAME1></STATUS_NAME1>
<STATUS_NAME2></STATUS_NAME2>
<STATUS_NAME3></STATUS_NAME3>
<ALT_STATUS_TEXT></ALT_STATUS_TEXT>
<STATUS_CODE></STATUS_CODE>
<STATUS2_NAME1></STATUS2_NAME1>
<STATUS2_NAME2></STATUS2_NAME2>
<STATUS2_NAME3></STATUS2_NAME3>
<STATUS_CODE2></STATUS_CODE2>
<EXPIRATION></EXPIRATION>
<UPDATED></UPDATED>
<COMMENTS_LINE1></COMMENTS_LINE1>
<COMMENTS_LINE2></COMMENTS_LINE2>
<COMMENTS_LINE3></COMMENTS_LINE3>
<ADDRESS1></ADDRESS1>
<ADDRESS2></ADDRESS2>
<CITY></CITY>
<STATE>AR</STATE>
<ZIPCODE></ZIPCODE>
<ORGANIZATION_HOMEPAGE></ORGANIZATION_HOMEPAGE>
</RECORD>
<RECORD>
<REC_ID>9575</REC_ID>
<FORCED_ORGANIZATION_NAME>Radiologist of Arkansas</FORCED_ORGANIZATION_NAME>
<ORGANIZATION_NAME1>Radiologist of Arkansas</ORGANIZATION_NAME1>
<ORGANIZATION_NAME2></ORGANIZATION_NAME2>
<ORGANIZATION_NAME3></ORGANIZATION_NAME3>
<ALT_ORGANIZATION_NAME></ALT_ORGANIZATION_NAME>
<FORCED_COUNTY_NAME>Pulaski</FORCED_COUNTY_NAME>
<COUNTY_NAME1>Pulaski</COUNTY_NAME1>
<COUNTY_NAME2></COUNTY_NAME2>
<ALT_COUNTY_NAME></ALT_COUNTY_NAME>
<FORCED_CATEGORY_NAME></FORCED_CATEGORY_NAME>
<CAT_CODE></CAT_CODE>
<CATEGORY_NAME1></CATEGORY_NAME1>
<CATEGORY_NAME2></CATEGORY_NAME2>
<FORCED_STATUS_NAME></FORCED_STATUS_NAME>
<STATUS_NAME1></STATUS_NAME1>
<STATUS_NAME2></STATUS_NAME2>
<STATUS_NAME3></STATUS_NAME3>
<ALT_STATUS_TEXT></ALT_STATUS_TEXT>
<STATUS_CODE></STATUS_CODE>
<STATUS2_NAME1></STATUS2_NAME1>
<STATUS2_NAME2></STATUS2_NAME2>
<STATUS2_NAME3></STATUS2_NAME3>
<STATUS_CODE2></STATUS_CODE2>
<EXPIRATION></EXPIRATION>
<UPDATED></UPDATED>
<COMMENTS_LINE1></COMMENTS_LINE1>
<COMMENTS_LINE2></COMMENTS_LINE2>
<COMMENTS_LINE3></COMMENTS_LINE3>
<ADDRESS1></ADDRESS1>
<ADDRESS2></ADDRESS2>
<CITY></CITY>
<STATE>AR</STATE>
<ZIPCODE></ZIPCODE>
<ORGANIZATION_HOMEPAGE></ORGANIZATION_HOMEPAGE>
</RECORD>
<RECORD>
<REC_ID>9579</REC_ID>
<FORCED_ORGANIZATION_NAME>St. Vincent Breast Clinci</FORCED_ORGANIZATION_NAME>
<ORGANIZATION_NAME1>St. Vincent Breast Clinci</ORGANIZATION_NAME1>
<ORGANIZATION_NAME2></ORGANIZATION_NAME2>
<ORGANIZATION_NAME3></ORGANIZATION_NAME3>
<ALT_ORGANIZATION_NAME></ALT_ORGANIZATION_NAME>
<FORCED_COUNTY_NAME>Pulaski</FORCED_COUNTY_NAME>
<COUNTY_NAME1>Pulaski</COUNTY_NAME1>
<COUNTY_NAME2></COUNTY_NAME2>
<ALT_COUNTY_NAME></ALT_COUNTY_NAME>
<FORCED_CATEGORY_NAME></FORCED_CATEGORY_NAME>
<CAT_CODE></CAT_CODE>
<CATEGORY_NAME1></CATEGORY_NAME1>
<CATEGORY_NAME2></CATEGORY_NAME2>
<FORCED_STATUS_NAME></FORCED_STATUS_NAME>
<STATUS_NAME1></STATUS_NAME1>
<STATUS_NAME2></STATUS_NAME2>
<STATUS_NAME3></STATUS_NAME3>
<ALT_STATUS_TEXT></ALT_STATUS_TEXT>
<STATUS_CODE></STATUS_CODE>
<STATUS2_NAME1></STATUS2_NAME1>
<STATUS2_NAME2></STATUS2_NAME2>
<STATUS2_NAME3></STATUS2_NAME3>
<STATUS_CODE2></STATUS_CODE2>
<EXPIRATION></EXPIRATION>
<UPDATED></UPDATED>
<COMMENTS_LINE1></COMMENTS_LINE1>
<COMMENTS_LINE2></COMMENTS_LINE2>
<COMMENTS_LINE3></COMMENTS_LINE3>
<ADDRESS1></ADDRESS1>
<ADDRESS2></ADDRESS2>
<CITY></CITY>
<STATE>AR</STATE>
<ZIPCODE></ZIPCODE>
<ORGANIZATION_HOMEPAGE></ORGANIZATION_HOMEPAGE>
</RECORD>
<RECORD>
<REC_ID>9695</REC_ID>
<FORCED_ORGANIZATION_NAME>UAMS Outpatient Clinics</FORCED_ORGANIZATION_NAME>
<ORGANIZATION_NAME1>UAMS Outpatient Clinics</ORGANIZATION_NAME1>
<ORGANIZATION_NAME2></ORGANIZATION_NAME2>
<ORGANIZATION_NAME3></ORGANIZATION_NAME3>
<ALT_ORGANIZATION_NAME></ALT_ORGANIZATION_NAME>
<FORCED_COUNTY_NAME>Pulaski</FORCED_COUNTY_NAME>
<COUNTY_NAME1>Pulaski</COUNTY_NAME1>
<COUNTY_NAME2></COUNTY_NAME2>
<ALT_COUNTY_NAME></ALT_COUNTY_NAME>
<FORCED_CATEGORY_NAME></FORCED_CATEGORY_NAME>
<CAT_CODE></CAT_CODE>
<CATEGORY_NAME1></CATEGORY_NAME1>
<CATEGORY_NAME2></CATEGORY_NAME2>
<FORCED_STATUS_NAME></FORCED_STATUS_NAME>
<STATUS_NAME1></STATUS_NAME1>
<STATUS_NAME2></STATUS_NAME2>
<STATUS_NAME3></STATUS_NAME3>
<ALT_STATUS_TEXT></ALT_STATUS_TEXT>
<STATUS_CODE></STATUS_CODE>
<STATUS2_NAME1></STATUS2_NAME1>
<STATUS2_NAME2></STATUS2_NAME2>
<STATUS2_NAME3></STATUS2_NAME3>
<STATUS_CODE2></STATUS_CODE2>
<EXPIRATION></EXPIRATION>
<UPDATED></UPDATED>
<COMMENTS_LINE1></COMMENTS_LINE1>
<COMMENTS_LINE2></COMMENTS_LINE2>
<COMMENTS_LINE3></COMMENTS_LINE3>
<ADDRESS1></ADDRESS1>
<ADDRESS2></ADDRESS2>
<CITY></CITY>
<STATE>AR</STATE>
<ZIPCODE></ZIPCODE>
<ORGANIZATION_HOMEPAGE></ORGANIZATION_HOMEPAGE>
</RECORD>
<RECORD>
<REC_ID>6886</REC_ID>
<FORCED_ORGANIZATION_NAME>1st Presbyterian School-Pine Bluff</FORCED_ORGANIZATION_NAME>
<ORGANIZATION_NAME1>1st Presbyterian School-Pine Bluff</ORGANIZATION_NAME1>
<ORGANIZATION_NAME2></ORGANIZATION_NAME2>
<ORGANIZATION_NAME3></ORGANIZATION_NAME3>
<ALT_ORGANIZATION_NAME></ALT_ORGANIZATION_NAME>
<FORCED_COUNTY_NAME>Jefferson</FORCED_COUNTY_NAME>
<COUNTY_NAME1>Jefferson</COUNTY_NAME1>
<COUNTY_NAME2></COUNTY_NAME2>
<ALT_COUNTY_NAME></ALT_COUNTY_NAME>
<FORCED_CATEGORY_NAME>Schools</FORCED_CATEGORY_NAME>
<CAT_CODE>1</CAT_CODE>
<CATEGORY_NAME1>Schools</CATEGORY_NAME1>
<CATEGORY_NAME2></CATEGORY_NAME2>
<FORCED_STATUS_NAME></FORCED_STATUS_NAME>
<STATUS_NAME1></STATUS_NAME1>
<STATUS_NAME2></STATUS_NAME2>
<STATUS_NAME3></STATUS_NAME3>
<ALT_STATUS_TEXT></ALT_STATUS_TEXT>
<STATUS_CODE></STATUS_CODE>
<STATUS2_NAME1></STATUS2_NAME1>
<STATUS2_NAME2></STATUS2_NAME2>
<STATUS2_NAME3></STATUS2_NAME3>
<STATUS_CODE2></STATUS_CODE2>
<EXPIRATION></EXPIRATION>
<UPDATED></UPDATED>
<COMMENTS_LINE1></COMMENTS_LINE1>
<COMMENTS_LINE2></COMMENTS_LINE2>
<COMMENTS_LINE3></COMMENTS_LINE3>
<ADDRESS1>717 W. 32nd Ave</ADDRESS1>
<ADDRESS2></ADDRESS2>
<CITY>Pine Bluff</CITY>
<STATE>AR</STATE>
<ZIPCODE>71603-6006</ZIPCODE>
<ORGANIZATION_HOMEPAGE></ORGANIZATION_HOMEPAGE>
</RECORD>
<RECORD>
<REC_ID>7879</REC_ID>
<FORCED_ORGANIZATION_NAME>A-1 Thompson Driving School</FORCED_ORGANIZATION_NAME>
<ORGANIZATION_NAME1>A-1 Thompson Driving School</ORGANIZATION_NAME1>
<ORGANIZATION_NAME2></ORGANIZATION_NAME2>
<ORGANIZATION_NAME3></ORGANIZATION_NAME3>
<ALT_ORGANIZATION_NAME></ALT_ORGANIZATION_NAME>
<FORCED_COUNTY_NAME>Pulaski</FORCED_COUNTY_NAME>
<COUNTY_NAME1>Pulaski</COUNTY_NAME1>
<COUNTY_NAME2></COUNTY_NAME2>
<ALT_COUNTY_NAME></ALT_COUNTY_NAME>
<FORCED_CATEGORY_NAME>Schools</FORCED_CATEGORY_NAME>
<CAT_CODE>1</CAT_CODE>
<CATEGORY_NAME1>Schools</CATEGORY_NAME1>
<CATEGORY_NAME2></CATEGORY_NAME2>
<FORCED_STATUS_NAME></FORCED_STATUS_NAME>
<STATUS_NAME1></STATUS_NAME1>
<STATUS_NAME2></STATUS_NAME2>
<STATUS_NAME3></STATUS_NAME3>
<ALT_STATUS_TEXT></ALT_STATUS_TEXT>
<STATUS_CODE></STATUS_CODE>
<STATUS2_NAME1></STATUS2_NAME1>
<STATUS2_NAME2></STATUS2_NAME2>
<STATUS2_NAME3></STATUS2_NAME3>
<STATUS_CODE2></STATUS_CODE2>
<EXPIRATION></EXPIRATION>
<UPDATED></UPDATED>
<COMMENTS_LINE1></COMMENTS_LINE1>
<COMMENTS_LINE2></COMMENTS_LINE2>
<COMMENTS_LINE3></COMMENTS_LINE3>
<ADDRESS1>2024 Arkansas Valley Dr.</ADDRESS1>
<ADDRESS2>Suite 501</ADDRESS2>
<CITY>Little Rock</CITY>
<STATE>AR</STATE>
<ZIPCODE>72212-4144</ZIPCODE>
<ORGANIZATION_HOMEPAGE></ORGANIZATION_HOMEPAGE>
</RECORD>
<RECORD>
<REC_ID>9239</REC_ID>
<FORCED_ORGANIZATION_NAME>ABC Inspection Institute</FORCED_ORGANIZATION_NAME>
<ORGANIZATION_NAME1>ABC Inspection Institute</ORGANIZATION_NAME1>
<ORGANIZATION_NAME2></ORGANIZATION_NAME2>
<ORGANIZATION_NAME3></ORGANIZATION_NAME3>
<ALT_ORGANIZATION_NAME></ALT_ORGANIZATION_NAME>
<FORCED_COUNTY_NAME>Faulkner</FORCED_COUNTY_NAME>
<COUNTY_NAME1>Faulkner</COUNTY_NAME1>
<COUNTY_NAME2></COUNTY_NAME2>
<ALT_COUNTY_NAME></ALT_COUNTY_NAME>
<FORCED_CATEGORY_NAME>Schools</FORCED_CATEGORY_NAME>
<CAT_CODE>1</CAT_CODE>
<CATEGORY_NAME1>Schools</CATEGORY_NAME1>
<CATEGORY_NAME2></CATEGORY_NAME2>
<FORCED_STATUS_NAME></FORCED_STATUS_NAME>
<STATUS_NAME1></STATUS_NAME1>
<STATUS_NAME2></STATUS_NAME2>
<STATUS_NAME3></STATUS_NAME3>
<ALT_STATUS_TEXT></ALT_STATUS_TEXT>
<STATUS_CODE></STATUS_CODE>
<STATUS2_NAME1></STATUS2_NAME1>
<STATUS2_NAME2></STATUS2_NAME2>
<STATUS2_NAME3></STATUS2_NAME3>
<STATUS_CODE2></STATUS_CODE2>
<EXPIRATION></EXPIRATION>
<UPDATED></UPDATED>
<COMMENTS_LINE1></COMMENTS_LINE1>
<COMMENTS_LINE2></COMMENTS_LINE2>
<COMMENTS_LINE3></COMMENTS_LINE3>
<ADDRESS1>P.O. Box 576</ADDRESS1>
<ADDRESS2></ADDRESS2>
<CITY>Vilonia</CITY>
<STATE>AR</STATE>
<ZIPCODE>72173-0576</ZIPCODE>
<ORGANIZATION_HOMEPAGE></ORGANIZATION_HOMEPAGE>
</RECORD>
<RECORD>
<REC_ID>2714</REC_ID>
<FORCED_ORGANIZATION_NAME>Abiding Faith Christian</FORCED_ORGANIZATION_NAME>
<ORGANIZATION_NAME1>Abiding Faith Christian</ORGANIZATION_NAME1>
<ORGANIZATION_NAME2></ORGANIZATION_NAME2>
<ORGANIZATION_NAME3></ORGANIZATION_NAME3>
<ALT_ORGANIZATION_NAME></ALT_ORGANIZATION_NAME>
<FORCED_COUNTY_NAME>Ashley</FORCED_COUNTY_NAME>
<COUNTY_NAME1>Ashley</COUNTY_NAME1>
<COUNTY_NAME2></COUNTY_NAME2>
<ALT_COUNTY_NAME></ALT_COUNTY_NAME>
<FORCED_CATEGORY_NAME>Schools</FORCED_CATEGORY_NAME>
<CAT_CODE>1</CAT_CODE>
<CATEGORY_NAME1>Schools</CATEGORY_NAME1>
<CATEGORY_NAME2></CATEGORY_NAME2>
<FORCED_STATUS_NAME></FORCED_STATUS_NAME>
<STATUS_NAME1></STATUS_NAME1>
<STATUS_NAME2></STATUS_NAME2>
<STATUS_NAME3></STATUS_NAME3>
<ALT_STATUS_TEXT></ALT_STATUS_TEXT>
<STATUS_CODE></STATUS_CODE>
<STATUS2_NAME1></STATUS2_NAME1>
<STATUS2_NAME2></STATUS2_NAME2>
<STATUS2_NAME3></STATUS2_NAME3>
<STATUS_CODE2></STATUS_CODE2>
<EXPIRATION></EXPIRATION>
<UPDATED></UPDATED>
<COMMENTS_LINE1></COMMENTS_LINE1>
<COMMENTS_LINE2></COMMENTS_LINE2>
<COMMENTS_LINE3></COMMENTS_LINE3>
<ADDRESS1>1552 Highway 52 W.</ADDRESS1>
<ADDRESS2></ADDRESS2>
<CITY>Crossett</CITY>
<STATE>AR</STATE>
<ZIPCODE>71635-8836</ZIPCODE>
<ORGANIZATION_HOMEPAGE></ORGANIZATION_HOMEPAGE>
</RECORD>
<RECORD>
<REC_ID>1000</REC_ID>
<FORCED_ORGANIZATION_NAME>Abundant Life</FORCED_ORGANIZATION_NAME>
<ORGANIZATION_NAME1>Abundant Life</ORGANIZATION_NAME1>
<ORGANIZATION_NAME2></ORGANIZATION_NAME2>
<ORGANIZATION_NAME3></ORGANIZATION_NAME3>
<ALT_ORGANIZATION_NAME></ALT_ORGANIZATION_NAME>
<FORCED_COUNTY_NAME>Pulaski</FORCED_COUNTY_NAME>
<COUNTY_NAME1>Pulaski</COUNTY_NAME1>
<COUNTY_NAME2></COUNTY_NAME2>
<ALT_COUNTY_NAME></ALT_COUNTY_NAME>
<FORCED_CATEGORY_NAME>Schools</FORCED_CATEGORY_NAME>
<CAT_CODE>1</CAT_CODE>
<CATEGORY_NAME1>Schools</CATEGORY_NAME1>
<CATEGORY_NAME2></CATEGORY_NAME2>
<FORCED_STATUS_NAME></FORCED_STATUS_NAME>
<STATUS_NAME1></STATUS_NAME1>
<STATUS_NAME2></STATUS_NAME2>
<STATUS_NAME3></STATUS_NAME3>
<ALT_STATUS_TEXT></ALT_STATUS_TEXT>
<STATUS_CODE></STATUS_CODE>
<STATUS2_NAME1></STATUS2_NAME1>
<STATUS2_NAME2></STATUS2_NAME2>
<STATUS2_NAME3></STATUS2_NAME3>
<STATUS_CODE2></STATUS_CODE2>
<EXPIRATION></EXPIRATION>
<UPDATED></UPDATED>
<COMMENTS_LINE1></COMMENTS_LINE1>
<COMMENTS_LINE2></COMMENTS_LINE2>
<COMMENTS_LINE3></COMMENTS_LINE3>
<ADDRESS1>9200 Hwy 107</ADDRESS1>
<ADDRESS2></ADDRESS2>
<CITY>Sherwood</CITY>
<STATE>AR</STATE>
<ZIPCODE>72120-2938</ZIPCODE>
<ORGANIZATION_HOMEPAGE></ORGANIZATION_HOMEPAGE>
</RECORD>
<RECORD>
<REC_ID>9219</REC_ID>
<FORCED_ORGANIZATION_NAME>Academic World of Cosmetology</FORCED_ORGANIZATION_NAME>
<ORGANIZATION_NAME1>Academic World of Cosmetology</ORGANIZATION_NAME1>
<ORGANIZATION_NAME2></ORGANIZATION_NAME2>
<ORGANIZATION_NAME3></ORGANIZATION_NAME3>
<ALT_ORGANIZATION_NAME></ALT_ORGANIZATION_NAME>
<FORCED_COUNTY_NAME>Pulaski</FORCED_COUNTY_NAME>
<COUNTY_NAME1>Pulaski</COUNTY_NAME1>
<COUNTY_NAME2></COUNTY_NAME2>
<ALT_COUNTY_NAME></ALT_COUNTY_NAME>
<FORCED_CATEGORY_NAME>Schools</FORCED_CATEGORY_NAME>
<CAT_CODE>1</CAT_CODE>
<CATEGORY_NAME1>Schools</CATEGORY_NAME1>
<CATEGORY_NAME2></CATEGORY_NAME2>
<FORCED_STATUS_NAME></FORCED_STATUS_NAME>
<STATUS_NAME1></STATUS_NAME1>
<STATUS_NAME2></STATUS_NAME2>
<STATUS_NAME3></STATUS_NAME3>
<ALT_STATUS_TEXT></ALT_STATUS_TEXT>
<STATUS_CODE></STATUS_CODE>
<STATUS2_NAME1></STATUS2_NAME1>
<STATUS2_NAME2></STATUS2_NAME2>
<STATUS2_NAME3></STATUS2_NAME3>
<STATUS_CODE2></STATUS_CODE2>
<EXPIRATION></EXPIRATION>
<UPDATED></UPDATED>
<COMMENTS_LINE1></COMMENTS_LINE1>
<COMMENTS_LINE2></COMMENTS_LINE2>
<COMMENTS_LINE3></COMMENTS_LINE3>
<ADDRESS1>240 S. Shackleford Rd.</ADDRESS1>
<ADDRESS2>Suite A</ADDRESS2>
<CITY>Little Rock</CITY>
<STATE>AR</STATE>
<ZIPCODE>72211-5716</ZIPCODE>
<ORGANIZATION_HOMEPAGE></ORGANIZATION_HOMEPAGE>
</RECORD>
<RECORD>
<REC_ID>1004</REC_ID>
<FORCED_ORGANIZATION_NAME>Academics Plus Charter</FORCED_ORGANIZATION_NAME>
<ORGANIZATION_NAME1>Academics Plus Charter</ORGANIZATION_NAME1>
<ORGANIZATION_NAME2></ORGANIZATION_NAME2>
<ORGANIZATION_NAME3></ORGANIZATION_NAME3>
<ALT_ORGANIZATION_NAME></ALT_ORGANIZATION_NAME>
<FORCED_COUNTY_NAME>Pulaski</FORCED_COUNTY_NAME>
<COUNTY_NAME1>Pulaski</COUNTY_NAME1>
<COUNTY_NAME2></COUNTY_NAME2>
<ALT_COUNTY_NAME></ALT_COUNTY_NAME>
<FORCED_CATEGORY_NAME>Schools</FORCED_CATEGORY_NAME>
<CAT_CODE>1</CAT_CODE>
<CATEGORY_NAME1>Schools</CATEGORY_NAME1>
<CATEGORY_NAME2></CATEGORY_NAME2>
<FORCED_STATUS_NAME></FORCED_STATUS_NAME>
<STATUS_NAME1></STATUS_NAME1>
<STATUS_NAME2></STATUS_NAME2>
<STATUS_NAME3></STATUS_NAME3>
<ALT_STATUS_TEXT></ALT_STATUS_TEXT>
<STATUS_CODE></STATUS_CODE>
<STATUS2_NAME1></STATUS2_NAME1>
<STATUS2_NAME2></STATUS2_NAME2>
<STATUS2_NAME3></STATUS2_NAME3>
<STATUS_CODE2></STATUS_CODE2>
<EXPIRATION></EXPIRATION>
<UPDATED></UPDATED>
<COMMENTS_LINE1></COMMENTS_LINE1>
<COMMENTS_LINE2></COMMENTS_LINE2>
<COMMENTS_LINE3></COMMENTS_LINE3>
<ADDRESS1>900 Edgewood Dr,</ADDRESS1>
<ADDRESS2></ADDRESS2>
<CITY>Maumelle</CITY>
<STATE>AR</STATE>
<ZIPCODE>72113-6275</ZIPCODE>
<ORGANIZATION_HOMEPAGE></ORGANIZATION_HOMEPAGE>
</RECORD>
<RECORD>
<REC_ID>1008</REC_ID>
<FORCED_ORGANIZATION_NAME>Access Schools</FORCED_ORGANIZATION_NAME>
<ORGANIZATION_NAME1>Access Schools</ORGANIZATION_NAME1>
<ORGANIZATION_NAME2></ORGANIZATION_NAME2>
<ORGANIZATION_NAME3></ORGANIZATION_NAME3>
<ALT_ORGANIZATION_NAME></ALT_ORGANIZATION_NAME>
<FORCED_COUNTY_NAME>Pulaski</FORCED_COUNTY_NAME>
<COUNTY_NAME1>Pulaski</COUNTY_NAME1>
<COUNTY_NAME2></COUNTY_NAME2>
<ALT_COUNTY_NAME></ALT_COUNTY_NAME>
<FORCED_CATEGORY_NAME>Schools</FORCED_CATEGORY_NAME>
<CAT_CODE>1</CAT_CODE>
<CATEGORY_NAME1>Schools</CATEGORY_NAME1>
<CATEGORY_NAME2></CATEGORY_NAME2>
<FORCED_STATUS_NAME></FORCED_STATUS_NAME>
<STATUS_NAME1></STATUS_NAME1>
<STATUS_NAME2></STATUS_NAME2>
<STATUS_NAME3></STATUS_NAME3>
<ALT_STATUS_TEXT></ALT_STATUS_TEXT>
<STATUS_CODE></STATUS_CODE>
<STATUS2_NAME1></STATUS2_NAME1>
<STATUS2_NAME2></STATUS2_NAME2>
<STATUS2_NAME3></STATUS2_NAME3>
<STATUS_CODE2></STATUS_CODE2>
<EXPIRATION></EXPIRATION>
<UPDATED></UPDATED>
<COMMENTS_LINE1></COMMENTS_LINE1>
<COMMENTS_LINE2></COMMENTS_LINE2>
<COMMENTS_LINE3></COMMENTS_LINE3>
<ADDRESS1>10618 Breckenridge Dr.</ADDRESS1>
<ADDRESS2>Attn: Communications</ADDRESS2>
<CITY>Little Rock</CITY>
<STATE>AR</STATE>
<ZIPCODE>72211-1802</ZIPCODE>
<ORGANIZATION_HOMEPAGE></ORGANIZATION_HOMEPAGE>
</RECORD>
<RECORD>
<REC_ID>8039</REC_ID>
<FORCED_ORGANIZATION_NAME>ACEF-Forrest City</FORCED_ORGANIZATION_NAME>
<ORGANIZATION_NAME1>ACEF-Forrest City</ORGANIZATION_NAME1>
<ORGANIZATION_NAME2></ORGANIZATION_NAME2>
<ORGANIZATION_NAME3></ORGANIZATION_NAME3>
<ALT_ORGANIZATION_NAME></ALT_ORGANIZATION_NAME>
<FORCED_COUNTY_NAME>St. Francis</FORCED_COUNTY_NAME>
<COUNTY_NAME1>St. Francis</COUNTY_NAME1>
<COUNTY_NAME2></COUNTY_NAME2>
<ALT_COUNTY_NAME></ALT_COUNTY_NAME>
<FORCED_CATEGORY_NAME>Schools</FORCED_CATEGORY_NAME>
<CAT_CODE>1</CAT_CODE>
<CATEGORY_NAME1>Schools</CATEGORY_NAME1>
<CATEGORY_NAME2></CATEGORY_NAME2>
<FORCED_STATUS_NAME></FORCED_STATUS_NAME>
<STATUS_NAME1></STATUS_NAME1>
<STATUS_NAME2></STATUS_NAME2>
<STATUS_NAME3></STATUS_NAME3>
<ALT_STATUS_TEXT></ALT_STATUS_TEXT>
<STATUS_CODE></STATUS_CODE>
<STATUS2_NAME1></STATUS2_NAME1>
<STATUS2_NAME2></STATUS2_NAME2>
<STATUS2_NAME3></STATUS2_NAME3>
<STATUS_CODE2></STATUS_CODE2>
<EXPIRATION></EXPIRATION>
<UPDATED></UPDATED>
<COMMENTS_LINE1></COMMENTS_LINE1>
<COMMENTS_LINE2></COMMENTS_LINE2>
<COMMENTS_LINE3></COMMENTS_LINE3>
<ADDRESS1>4421 W. 61st St.</ADDRESS1>
<ADDRESS2></ADDRESS2>
<CITY>Little Rock</CITY>
<STATE>AR</STATE>
<ZIPCODE>72209-2403</ZIPCODE>
<ORGANIZATION_HOMEPAGE></ORGANIZATION_HOMEPAGE>
</RECORD>
<RECORD>
<REC_ID>8031</REC_ID>
<FORCED_ORGANIZATION_NAME>ACEF-Jonesboro</FORCED_ORGANIZATION_NAME>
<ORGANIZATION_NAME1>ACEF-Jonesboro</ORGANIZATION_NAME1>
<ORGANIZATION_NAME2></ORGANIZATION_NAME2>
<ORGANIZATION_NAME3></ORGANIZATION_NAME3>
<ALT_ORGANIZATION_NAME></ALT_ORGANIZATION_NAME>
<FORCED_COUNTY_NAME>Craighead</FORCED_COUNTY_NAME>
<COUNTY_NAME1>Craighead</COUNTY_NAME1>
<COUNTY_NAME2></COUNTY_NAME2>
<ALT_COUNTY_NAME></ALT_COUNTY_NAME>
<FORCED_CATEGORY_NAME>Schools</FORCED_CATEGORY_NAME>
<CAT_CODE>1</CAT_CODE>
<CATEGORY_NAME1>Schools</CATEGORY_NAME1>
<CATEGORY_NAME2></CATEGORY_NAME2>
<FORCED_STATUS_NAME></FORCED_STATUS_NAME>
<STATUS_NAME1></STATUS_NAME1>
<STATUS_NAME2></STATUS_NAME2>
<STATUS_NAME3></STATUS_NAME3>
<ALT_STATUS_TEXT></ALT_STATUS_TEXT>
<STATUS_CODE></STATUS_CODE>
<STATUS2_NAME1></STATUS2_NAME1>
<STATUS2_NAME2></STATUS2_NAME2>
<STATUS2_NAME3></STATUS2_NAME3>
<STATUS_CODE2></STATUS_CODE2>
<EXPIRATION></EXPIRATION>
<UPDATED></UPDATED>
<COMMENTS_LINE1></COMMENTS_LINE1>
<COMMENTS_LINE2></COMMENTS_LINE2>
<COMMENTS_LINE3></COMMENTS_LINE3>
<ADDRESS1>4421 W. 61st St.</ADDRESS1>
<ADDRESS2></ADDRESS2>
<CITY>Little Rock</CITY>
<STATE>AR</STATE>
<ZIPCODE>72209-2403</ZIPCODE>
<ORGANIZATION_HOMEPAGE></ORGANIZATION_HOMEPAGE>
</RECORD>
<RECORD>
<REC_ID>8027</REC_ID>
<FORCED_ORGANIZATION_NAME>ACEF-Little Rock</FORCED_ORGANIZATION_NAME>
<ORGANIZATION_NAME1>ACEF-Little Rock</ORGANIZATION_NAME1>
<ORGANIZATION_NAME2></ORGANIZATION_NAME2>
<ORGANIZATION_NAME3></ORGANIZATION_NAME3>
<ALT_ORGANIZATION_NAME></ALT_ORGANIZATION_NAME>
<FORCED_COUNTY_NAME>Pulaski</FORCED_COUNTY_NAME>
<COUNTY_NAME1>Pulaski</COUNTY_NAME1>
<COUNTY_NAME2></COUNTY_NAME2>
<ALT_COUNTY_NAME></ALT_COUNTY_NAME>
<FORCED_CATEGORY_NAME>Schools</FORCED_CATEGORY_NAME>
<CAT_CODE>1</CAT_CODE>
<CATEGORY_NAME1>Schools</CATEGORY_NAME1>
<CATEGORY_NAME2></CATEGORY_NAME2>
<FORCED_STATUS_NAME></FORCED_STATUS_NAME>
<STATUS_NAME1></STATUS_NAME1>
<STATUS_NAME2></STATUS_NAME2>
<STATUS_NAME3></STATUS_NAME3>
<ALT_STATUS_TEXT></ALT_STATUS_TEXT>
<STATUS_CODE></STATUS_CODE>
<STATUS2_NAME1></STATUS2_NAME1>
<STATUS2_NAME2></STATUS2_NAME2>
<STATUS2_NAME3></STATUS2_NAME3>
<STATUS_CODE2></STATUS_CODE2>
<EXPIRATION></EXPIRATION>
<UPDATED></UPDATED>
<COMMENTS_LINE1></COMMENTS_LINE1>
<COMMENTS_LINE2></COMMENTS_LINE2>
<COMMENTS_LINE3></COMMENTS_LINE3>
<ADDRESS1>4421 W. 61 St.</ADDRESS1>
<ADDRESS2></ADDRESS2>
<CITY>Little Rock</CITY>
<STATE>AR</STATE>
<ZIPCODE>72209-2403</ZIPCODE>
<ORGANIZATION_HOMEPAGE></ORGANIZATION_HOMEPAGE>
</RECORD>
<RECORD>
<REC_ID>8035</REC_ID>
<FORCED_ORGANIZATION_NAME>ACEF-Morrilton</FORCED_ORGANIZATION_NAME>
<ORGANIZATION_NAME1>ACEF-Morrilton</ORGANIZATION_NAME1>
<ORGANIZATION_NAME2></ORGANIZATION_NAME2>
<ORGANIZATION_NAME3></ORGANIZATION_NAME3>
<ALT_ORGANIZATION_NAME></ALT_ORGANIZATION_NAME>
<FORCED_COUNTY_NAME>Conway</FORCED_COUNTY_NAME>
<COUNTY_NAME1>Conway</COUNTY_NAME1>
<COUNTY_NAME2></COUNTY_NAME2>
<ALT_COUNTY_NAME></ALT_COUNTY_NAME>
<FORCED_CATEGORY_NAME>Schools</FORCED_CATEGORY_NAME>
<CAT_CODE>1</CAT_CODE>
<CATEGORY_NAME1>Schools</CATEGORY_NAME1>
<CATEGORY_NAME2></CATEGORY_NAME2>
<FORCED_STATUS_NAME></FORCED_STATUS_NAME>
<STATUS_NAME1></STATUS_NAME1>
<STATUS_NAME2></STATUS_NAME2>
<STATUS_NAME3></STATUS_NAME3>
<ALT_STATUS_TEXT></ALT_STATUS_TEXT>
<STATUS_CODE></STATUS_CODE>
<STATUS2_NAME1></STATUS2_NAME1>
<STATUS2_NAME2></STATUS2_NAME2>
<STATUS2_NAME3></STATUS2_NAME3>
<STATUS_CODE2></STATUS_CODE2>
<EXPIRATION></EXPIRATION>
<UPDATED></UPDATED>
<COMMENTS_LINE1></COMMENTS_LINE1>
<COMMENTS_LINE2></COMMENTS_LINE2>
<COMMENTS_LINE3></COMMENTS_LINE3>
<ADDRESS1>4421 W. 61st St.</ADDRESS1>
<ADDRESS2></ADDRESS2>
<CITY>Little Rock</CITY>
<STATE>AR</STATE>
<ZIPCODE>72209-2403</ZIPCODE>
<ORGANIZATION_HOMEPAGE></ORGANIZATION_HOMEPAGE>
</RECORD>
<RECORD>
<REC_ID>9587</REC_ID>
<FORCED_ORGANIZATION_NAME>Acorn Public Schools</FORCED_ORGANIZATION_NAME>
<ORGANIZATION_NAME1>Acorn Public Schools</ORGANIZATION_NAME1>
<ORGANIZATION_NAME2>in Ouachita River</ORGANIZATION_NAME2>
<ORGANIZATION_NAME3></ORGANIZATION_NAME3>
<ALT_ORGANIZATION_NAME></ALT_ORGANIZATION_NAME>
<FORCED_COUNTY_NAME>Polk</FORCED_COUNTY_NAME>
<COUNTY_NAME1>Polk</COUNTY_NAME1>
<COUNTY_NAME2></COUNTY_NAME2>
<ALT_COUNTY_NAME></ALT_COUNTY_NAME>
<FORCED_CATEGORY_NAME>Schools</FORCED_CATEGORY_NAME>
<CAT_CODE>1</CAT_CODE>
<CATEGORY_NAME1>Schools</CATEGORY_NAME1>
<CATEGORY_NAME2></CATEGORY_NAME2>
<FORCED_STATUS_NAME></FORCED_STATUS_NAME>
<STATUS_NAME1></STATUS_NAME1>
<STATUS_NAME2></STATUS_NAME2>
<STATUS_NAME3></STATUS_NAME3>
<ALT_STATUS_TEXT></ALT_STATUS_TEXT>
<STATUS_CODE></STATUS_CODE>
<STATUS2_NAME1></STATUS2_NAME1>
<STATUS2_NAME2></STATUS2_NAME2>
<STATUS2_NAME3></STATUS2_NAME3>
<STATUS_CODE2></STATUS_CODE2>
<EXPIRATION></EXPIRATION>
<UPDATED></UPDATED>
<COMMENTS_LINE1></COMMENTS_LINE1>
<COMMENTS_LINE2></COMMENTS_LINE2>
<COMMENTS_LINE3></COMMENTS_LINE3>
<ADDRESS1>143 Polk</ADDRESS1>
<ADDRESS2></ADDRESS2>
<CITY>Mena</CITY>
<STATE>AR</STATE>
<ZIPCODE>71953</ZIPCODE>
<ORGANIZATION_HOMEPAGE></ORGANIZATION_HOMEPAGE>
</RECORD>
<RECORD>
<REC_ID>2726</REC_ID>
<FORCED_ORGANIZATION_NAME>AEDD</FORCED_ORGANIZATION_NAME>
<ORGANIZATION_NAME1>AEDD</ORGANIZATION_NAME1>
<ORGANIZATION_NAME2></ORGANIZATION_NAME2>
<ORGANIZATION_NAME3></ORGANIZATION_NAME3>
<ALT_ORGANIZATION_NAME></ALT_ORGANIZATION_NAME>
<FORCED_COUNTY_NAME>Pulaski</FORCED_COUNTY_NAME>
<COUNTY_NAME1>Pulaski</COUNTY_NAME1>
<COUNTY_NAME2></COUNTY_NAME2>
<ALT_COUNTY_NAME></ALT_COUNTY_NAME>
<FORCED_CATEGORY_NAME>Schools</FORCED_CATEGORY_NAME>
<CAT_CODE>1</CAT_CODE>
<CATEGORY_NAME1>Schools</CATEGORY_NAME1>
<CATEGORY_NAME2></CATEGORY_NAME2>
<FORCED_STATUS_NAME></FORCED_STATUS_NAME>
<STATUS_NAME1></STATUS_NAME1>
<STATUS_NAME2></STATUS_NAME2>
<STATUS_NAME3></STATUS_NAME3>
<ALT_STATUS_TEXT></ALT_STATUS_TEXT>
<STATUS_CODE></STATUS_CODE>
<STATUS2_NAME1></STATUS2_NAME1>
<STATUS2_NAME2></STATUS2_NAME2>
<STATUS2_NAME3></STATUS2_NAME3>
<STATUS_CODE2></STATUS_CODE2>
<EXPIRATION></EXPIRATION>
<UPDATED></UPDATED>
<COMMENTS_LINE1></COMMENTS_LINE1>
<COMMENTS_LINE2></COMMENTS_LINE2>
<COMMENTS_LINE3></COMMENTS_LINE3>
<ADDRESS1>6 Production Dr.</ADDRESS1>
<ADDRESS2></ADDRESS2>
<CITY>Little Rock</CITY>
<STATE>AR</STATE>