<?xml version="1.0" standalone="no" ?>
<!DOCTYPE DATA [
  <!ELEMENT DATA                     (SOURCE,EXPORT_TYPE,NUM_CLOSINGS,RUN_DATE,RUN_EPOCH,RECORD*)>
  <!ELEMENT SOURCE                   (CDATA)>
  <!ELEMENT EXPORT_TYPE              (CDATA)>
  <!ELEMENT NUM_CLOSINGS             (CDATA)>
  <!ELEMENT RUN_DATE                 (CDATA)>
  <!ELEMENT RUN_EPOCH                (CDATA)>
  <!ELEMENT RECORD                   (REC_ID,FORCED_ORGANIZATION_NAME,ORGANIZATION_NAME1,ORGANIZATION_NAME2,ORGANIZATION_NAME3,ALT_ORGANIZATION_NAME,FORCED_COUNTY_NAME,COUNTY_NAME1,COUNTY_NAME2,ALT_COUNTY_NAME,CAT_CODE,CATEGORY_NAME1,CATEGORY_NAME2,COMPLETE_STATUS,FORCED_STATUS_NAME,STATUS_NAME1,STATUS_NAME2,STATUS_NAME3,ALT_STATUS_TEXT,STATUS_CODE,STATUS2_NAME1,STATUS2_NAME2,STATUS2_NAME3,STATUS_CODE2,EXPIRATION,UPDATED,COMMENTS_LINE1,COMMENTS_LINE2,COMMENTS_LINE3,ADDRESS1,ADDRESS2,CITY,STATE,ZIPCODE,ORGANIZATION_HOMEPAGE)>
  <!ELEMENT REC_ID                   (ID)>
  <!ELEMENT FORCED_ORGANIZATION_NAME (CDATA)>
  <!ELEMENT ORGANIZATION_NAME1       (CDATA)>
  <!ELEMENT ORGANIZATION_NAME2       (CDATA)>
  <!ELEMENT ORGANIZATION_NAME3       (CDATA)>
  <!ELEMENT ALT_ORGANIZATION_NAME    (CDATA)>
  <!ELEMENT FORCED_COUNTY_NAME       (CDATA)>
  <!ELEMENT COUNTY_NAME1             (CDATA)>
  <!ELEMENT COUNTY_NAME2             (CDATA)>
  <!ELEMENT ALT_COUNTY_NAME          (CDATA)>
  <!ELEMENT CAT_CODE                 (CDATA)>
  <!ELEMENT CATEGORY_NAME1           (CDATA)>
  <!ELEMENT CATEGORY_NAME2           (CDATA)>
  <!ELEMENT COMPLETE_STATUS          (CDATA)>
  <!ELEMENT FORCED_STATUS_NAME       (CDATA)>
  <!ELEMENT STATUS_NAME1             (CDATA)>
  <!ELEMENT STATUS_NAME2             (CDATA)>
  <!ELEMENT STATUS_NAME3             (CDATA)>
  <!ELEMENT ALT_STATUS_TEXT          (CDATA)>
  <!ELEMENT STATUS_CODE              (CDATA)>
  <!ELEMENT STATUS2_NAME1            (CDATA)>
  <!ELEMENT STATUS2_NAME2            (CDATA)>
  <!ELEMENT STATUS2_NAME3            (CDATA)>
  <!ELEMENT STATUS_CODE2             (CDATA)>
  <!ELEMENT EXPIRATION               (CDATA)>
  <!ELEMENT UPDATED                  (CDATA)>
  <!ELEMENT COMMENTS_LINE1           (CDATA)>
  <!ELEMENT COMMENTS_LINE2           (CDATA)>
  <!ELEMENT COMMENTS_LINE3           (CDATA)>
  <!ELEMENT ADDRESS1                 (CDATA)>
  <!ELEMENT ADDRESS2                 (CDATA)>
  <!ELEMENT CITY                     (CDATA)>
  <!ELEMENT STATE                    (CDATA)>
  <!ELEMENT ZIPCODE                  (CDATA)>
  <!ELEMENT ORGANIZATION_HOMEPAGE    (CDATA)>
]>
<DATA>
<SOURCE>NewsTicker</SOURCE>
<EXPORT_TYPE>L2</EXPORT_TYPE>
<NUM_CLOSINGS>810</NUM_CLOSINGS>
<RUN_DATE>Mon Oct 19 03:03:01 CDT 2015</RUN_DATE>
<RUN_EPOCH>1445241781</RUN_EPOCH>
<RECORD>
<REC_ID>5131</REC_ID>
<FORCED_ORGANIZATION_NAME>A Cab Taxi Service</FORCED_ORGANIZATION_NAME>
<ORGANIZATION_NAME1>A Cab Taxi Service</ORGANIZATION_NAME1>
<ORGANIZATION_NAME2></ORGANIZATION_NAME2>
<ORGANIZATION_NAME3></ORGANIZATION_NAME3>
<ALT_ORGANIZATION_NAME></ALT_ORGANIZATION_NAME>
<FORCED_COUNTY_NAME></FORCED_COUNTY_NAME>
<COUNTY_NAME1></COUNTY_NAME1>
<COUNTY_NAME2></COUNTY_NAME2>
<ALT_COUNTY_NAME></ALT_COUNTY_NAME>
<FORCED_CATEGORY_NAME></FORCED_CATEGORY_NAME>
<CAT_CODE></CAT_CODE>
<CATEGORY_NAME1></CATEGORY_NAME1>
<CATEGORY_NAME2></CATEGORY_NAME2>
<COMPLETE_STATUS></COMPLETE_STATUS>
<FORCED_STATUS_NAME></FORCED_STATUS_NAME>
<STATUS_NAME1></STATUS_NAME1>
<STATUS_NAME2></STATUS_NAME2>
<STATUS_NAME3></STATUS_NAME3>
<ALT_STATUS_TEXT></ALT_STATUS_TEXT>
<STATUS_CODE></STATUS_CODE>
<STATUS2_NAME1></STATUS2_NAME1>
<STATUS2_NAME2></STATUS2_NAME2>
<STATUS2_NAME3></STATUS2_NAME3>
<STATUS_CODE2></STATUS_CODE2>
<EXPIRATION></EXPIRATION>
<UPDATED></UPDATED>
<COMMENTS_LINE1></COMMENTS_LINE1>
<COMMENTS_LINE2></COMMENTS_LINE2>
<COMMENTS_LINE3></COMMENTS_LINE3>
<ADDRESS1>501 Chateau Drive</ADDRESS1>
<ADDRESS2></ADDRESS2>
<CITY>St. Joseph</CITY>
<STATE>IL</STATE>
<ZIPCODE>61873</ZIPCODE>
<ORGANIZATION_HOMEPAGE></ORGANIZATION_HOMEPAGE>
</RECORD>
<RECORD>
<REC_ID>6115</REC_ID>
<FORCED_ORGANIZATION_NAME>Abbott&apos;s Florist</FORCED_ORGANIZATION_NAME>
<ORGANIZATION_NAME1>Abbott&apos;s Florist</ORGANIZATION_NAME1>
<ORGANIZATION_NAME2></ORGANIZATION_NAME2>
<ORGANIZATION_NAME3></ORGANIZATION_NAME3>
<ALT_ORGANIZATION_NAME></ALT_ORGANIZATION_NAME>
<FORCED_COUNTY_NAME></FORCED_COUNTY_NAME>
<COUNTY_NAME1></COUNTY_NAME1>
<COUNTY_NAME2></COUNTY_NAME2>
<ALT_COUNTY_NAME></ALT_COUNTY_NAME>
<FORCED_CATEGORY_NAME></FORCED_CATEGORY_NAME>
<CAT_CODE></CAT_CODE>
<CATEGORY_NAME1></CATEGORY_NAME1>
<CATEGORY_NAME2></CATEGORY_NAME2>
<COMPLETE_STATUS></COMPLETE_STATUS>
<FORCED_STATUS_NAME></FORCED_STATUS_NAME>
<STATUS_NAME1></STATUS_NAME1>
<STATUS_NAME2></STATUS_NAME2>
<STATUS_NAME3></STATUS_NAME3>
<ALT_STATUS_TEXT></ALT_STATUS_TEXT>
<STATUS_CODE></STATUS_CODE>
<STATUS2_NAME1></STATUS2_NAME1>
<STATUS2_NAME2></STATUS2_NAME2>
<STATUS2_NAME3></STATUS2_NAME3>
<STATUS_CODE2></STATUS_CODE2>
<EXPIRATION></EXPIRATION>
<UPDATED></UPDATED>
<COMMENTS_LINE1></COMMENTS_LINE1>
<COMMENTS_LINE2></COMMENTS_LINE2>
<COMMENTS_LINE3></COMMENTS_LINE3>
<ADDRESS1>1119 w Windsor</ADDRESS1>
<ADDRESS2></ADDRESS2>
<CITY>Champaign</CITY>
<STATE>IL</STATE>
<ZIPCODE>61821</ZIPCODE>
<ORGANIZATION_HOMEPAGE></ORGANIZATION_HOMEPAGE>
</RECORD>
<RECORD>
<REC_ID>5191</REC_ID>
<FORCED_ORGANIZATION_NAME>ABC Learning Center in Savoy</FORCED_ORGANIZATION_NAME>
<ORGANIZATION_NAME1>ABC Learning Center in Savoy</ORGANIZATION_NAME1>
<ORGANIZATION_NAME2></ORGANIZATION_NAME2>
<ORGANIZATION_NAME3></ORGANIZATION_NAME3>
<ALT_ORGANIZATION_NAME></ALT_ORGANIZATION_NAME>
<FORCED_COUNTY_NAME></FORCED_COUNTY_NAME>
<COUNTY_NAME1></COUNTY_NAME1>
<COUNTY_NAME2></COUNTY_NAME2>
<ALT_COUNTY_NAME></ALT_COUNTY_NAME>
<FORCED_CATEGORY_NAME></FORCED_CATEGORY_NAME>
<CAT_CODE></CAT_CODE>
<CATEGORY_NAME1></CATEGORY_NAME1>
<CATEGORY_NAME2></CATEGORY_NAME2>
<COMPLETE_STATUS></COMPLETE_STATUS>
<FORCED_STATUS_NAME></FORCED_STATUS_NAME>
<STATUS_NAME1></STATUS_NAME1>
<STATUS_NAME2></STATUS_NAME2>
<STATUS_NAME3></STATUS_NAME3>
<ALT_STATUS_TEXT></ALT_STATUS_TEXT>
<STATUS_CODE></STATUS_CODE>
<STATUS2_NAME1></STATUS2_NAME1>
<STATUS2_NAME2></STATUS2_NAME2>
<STATUS2_NAME3></STATUS2_NAME3>
<STATUS_CODE2></STATUS_CODE2>
<EXPIRATION></EXPIRATION>
<UPDATED></UPDATED>
<COMMENTS_LINE1></COMMENTS_LINE1>
<COMMENTS_LINE2></COMMENTS_LINE2>
<COMMENTS_LINE3></COMMENTS_LINE3>
<ADDRESS1></ADDRESS1>
<ADDRESS2></ADDRESS2>
<CITY></CITY>
<STATE>IL</STATE>
<ZIPCODE></ZIPCODE>
<ORGANIZATION_HOMEPAGE></ORGANIZATION_HOMEPAGE>
</RECORD>
<RECORD>
<REC_ID>6233</REC_ID>
<FORCED_ORGANIZATION_NAME>ADM Offices in Decatur</FORCED_ORGANIZATION_NAME>
<ORGANIZATION_NAME1>ADM Offices in Decatur</ORGANIZATION_NAME1>
<ORGANIZATION_NAME2></ORGANIZATION_NAME2>
<ORGANIZATION_NAME3></ORGANIZATION_NAME3>
<ALT_ORGANIZATION_NAME></ALT_ORGANIZATION_NAME>
<FORCED_COUNTY_NAME></FORCED_COUNTY_NAME>
<COUNTY_NAME1></COUNTY_NAME1>
<COUNTY_NAME2></COUNTY_NAME2>
<ALT_COUNTY_NAME></ALT_COUNTY_NAME>
<FORCED_CATEGORY_NAME></FORCED_CATEGORY_NAME>
<CAT_CODE></CAT_CODE>
<CATEGORY_NAME1></CATEGORY_NAME1>
<CATEGORY_NAME2></CATEGORY_NAME2>
<COMPLETE_STATUS></COMPLETE_STATUS>
<FORCED_STATUS_NAME></FORCED_STATUS_NAME>
<STATUS_NAME1></STATUS_NAME1>
<STATUS_NAME2></STATUS_NAME2>
<STATUS_NAME3></STATUS_NAME3>
<ALT_STATUS_TEXT></ALT_STATUS_TEXT>
<STATUS_CODE></STATUS_CODE>
<STATUS2_NAME1></STATUS2_NAME1>
<STATUS2_NAME2></STATUS2_NAME2>
<STATUS2_NAME3></STATUS2_NAME3>
<STATUS_CODE2></STATUS_CODE2>
<EXPIRATION></EXPIRATION>
<UPDATED></UPDATED>
<COMMENTS_LINE1></COMMENTS_LINE1>
<COMMENTS_LINE2></COMMENTS_LINE2>
<COMMENTS_LINE3></COMMENTS_LINE3>
<ADDRESS1></ADDRESS1>
<ADDRESS2></ADDRESS2>
<CITY></CITY>
<STATE>IL</STATE>
<ZIPCODE></ZIPCODE>
<ORGANIZATION_HOMEPAGE></ORGANIZATION_HOMEPAGE>
</RECORD>
<RECORD>
<REC_ID>6325</REC_ID>
<FORCED_ORGANIZATION_NAME>AFSCME Retirees Subchapter 88</FORCED_ORGANIZATION_NAME>
<ORGANIZATION_NAME1>AFSCME Retirees Subchapter 88</ORGANIZATION_NAME1>
<ORGANIZATION_NAME2></ORGANIZATION_NAME2>
<ORGANIZATION_NAME3></ORGANIZATION_NAME3>
<ALT_ORGANIZATION_NAME></ALT_ORGANIZATION_NAME>
<FORCED_COUNTY_NAME></FORCED_COUNTY_NAME>
<COUNTY_NAME1></COUNTY_NAME1>
<COUNTY_NAME2></COUNTY_NAME2>
<ALT_COUNTY_NAME></ALT_COUNTY_NAME>
<FORCED_CATEGORY_NAME></FORCED_CATEGORY_NAME>
<CAT_CODE></CAT_CODE>
<CATEGORY_NAME1></CATEGORY_NAME1>
<CATEGORY_NAME2></CATEGORY_NAME2>
<COMPLETE_STATUS></COMPLETE_STATUS>
<FORCED_STATUS_NAME></FORCED_STATUS_NAME>
<STATUS_NAME1></STATUS_NAME1>
<STATUS_NAME2></STATUS_NAME2>
<STATUS_NAME3></STATUS_NAME3>
<ALT_STATUS_TEXT></ALT_STATUS_TEXT>
<STATUS_CODE></STATUS_CODE>
<STATUS2_NAME1></STATUS2_NAME1>
<STATUS2_NAME2></STATUS2_NAME2>
<STATUS2_NAME3></STATUS2_NAME3>
<STATUS_CODE2></STATUS_CODE2>
<EXPIRATION></EXPIRATION>
<UPDATED></UPDATED>
<COMMENTS_LINE1></COMMENTS_LINE1>
<COMMENTS_LINE2></COMMENTS_LINE2>
<COMMENTS_LINE3></COMMENTS_LINE3>
<ADDRESS1></ADDRESS1>
<ADDRESS2></ADDRESS2>
<CITY></CITY>
<STATE>IL</STATE>
<ZIPCODE></ZIPCODE>
<ORGANIZATION_HOMEPAGE></ORGANIZATION_HOMEPAGE>
</RECORD>
<RECORD>
<REC_ID>5803</REC_ID>
<FORCED_ORGANIZATION_NAME>Amara Yoga &amp; Arts</FORCED_ORGANIZATION_NAME>
<ORGANIZATION_NAME1>Amara Yoga &amp; Arts</ORGANIZATION_NAME1>
<ORGANIZATION_NAME2></ORGANIZATION_NAME2>
<ORGANIZATION_NAME3></ORGANIZATION_NAME3>
<ALT_ORGANIZATION_NAME></ALT_ORGANIZATION_NAME>
<FORCED_COUNTY_NAME></FORCED_COUNTY_NAME>
<COUNTY_NAME1></COUNTY_NAME1>
<COUNTY_NAME2></COUNTY_NAME2>
<ALT_COUNTY_NAME></ALT_COUNTY_NAME>
<FORCED_CATEGORY_NAME></FORCED_CATEGORY_NAME>
<CAT_CODE></CAT_CODE>
<CATEGORY_NAME1></CATEGORY_NAME1>
<CATEGORY_NAME2></CATEGORY_NAME2>
<COMPLETE_STATUS></COMPLETE_STATUS>
<FORCED_STATUS_NAME></FORCED_STATUS_NAME>
<STATUS_NAME1></STATUS_NAME1>
<STATUS_NAME2></STATUS_NAME2>
<STATUS_NAME3></STATUS_NAME3>
<ALT_STATUS_TEXT></ALT_STATUS_TEXT>
<STATUS_CODE></STATUS_CODE>
<STATUS2_NAME1></STATUS2_NAME1>
<STATUS2_NAME2></STATUS2_NAME2>
<STATUS2_NAME3></STATUS2_NAME3>
<STATUS_CODE2></STATUS_CODE2>
<EXPIRATION></EXPIRATION>
<UPDATED></UPDATED>
<COMMENTS_LINE1></COMMENTS_LINE1>
<COMMENTS_LINE2></COMMENTS_LINE2>
<COMMENTS_LINE3></COMMENTS_LINE3>
<ADDRESS1></ADDRESS1>
<ADDRESS2></ADDRESS2>
<CITY>Urbana</CITY>
<STATE>IL</STATE>
<ZIPCODE></ZIPCODE>
<ORGANIZATION_HOMEPAGE></ORGANIZATION_HOMEPAGE>
</RECORD>
<RECORD>
<REC_ID>5839</REC_ID>
<FORCED_ORGANIZATION_NAME>American Legion Auxilary Champaign County</FORCED_ORGANIZATION_NAME>
<ORGANIZATION_NAME1>American Legion Auxilary Champaign County</ORGANIZATION_NAME1>
<ORGANIZATION_NAME2></ORGANIZATION_NAME2>
<ORGANIZATION_NAME3></ORGANIZATION_NAME3>
<ALT_ORGANIZATION_NAME></ALT_ORGANIZATION_NAME>
<FORCED_COUNTY_NAME></FORCED_COUNTY_NAME>
<COUNTY_NAME1></COUNTY_NAME1>
<COUNTY_NAME2></COUNTY_NAME2>
<ALT_COUNTY_NAME></ALT_COUNTY_NAME>
<FORCED_CATEGORY_NAME></FORCED_CATEGORY_NAME>
<CAT_CODE></CAT_CODE>
<CATEGORY_NAME1></CATEGORY_NAME1>
<CATEGORY_NAME2></CATEGORY_NAME2>
<COMPLETE_STATUS></COMPLETE_STATUS>
<FORCED_STATUS_NAME></FORCED_STATUS_NAME>
<STATUS_NAME1></STATUS_NAME1>
<STATUS_NAME2></STATUS_NAME2>
<STATUS_NAME3></STATUS_NAME3>
<ALT_STATUS_TEXT></ALT_STATUS_TEXT>
<STATUS_CODE></STATUS_CODE>
<STATUS2_NAME1></STATUS2_NAME1>
<STATUS2_NAME2></STATUS2_NAME2>
<STATUS2_NAME3></STATUS2_NAME3>
<STATUS_CODE2></STATUS_CODE2>
<EXPIRATION></EXPIRATION>
<UPDATED></UPDATED>
<COMMENTS_LINE1></COMMENTS_LINE1>
<COMMENTS_LINE2></COMMENTS_LINE2>
<COMMENTS_LINE3></COMMENTS_LINE3>
<ADDRESS1>705 W. Bloomington Road</ADDRESS1>
<ADDRESS2></ADDRESS2>
<CITY>Champaign</CITY>
<STATE>IL</STATE>
<ZIPCODE></ZIPCODE>
<ORGANIZATION_HOMEPAGE></ORGANIZATION_HOMEPAGE>
</RECORD>
<RECORD>
<REC_ID>6087</REC_ID>
<FORCED_ORGANIZATION_NAME>American Legion Post #122</FORCED_ORGANIZATION_NAME>
<ORGANIZATION_NAME1>American Legion Post #122</ORGANIZATION_NAME1>
<ORGANIZATION_NAME2></ORGANIZATION_NAME2>
<ORGANIZATION_NAME3></ORGANIZATION_NAME3>
<ALT_ORGANIZATION_NAME></ALT_ORGANIZATION_NAME>
<FORCED_COUNTY_NAME></FORCED_COUNTY_NAME>
<COUNTY_NAME1></COUNTY_NAME1>
<COUNTY_NAME2></COUNTY_NAME2>
<ALT_COUNTY_NAME></ALT_COUNTY_NAME>
<FORCED_CATEGORY_NAME></FORCED_CATEGORY_NAME>
<CAT_CODE></CAT_CODE>
<CATEGORY_NAME1></CATEGORY_NAME1>
<CATEGORY_NAME2></CATEGORY_NAME2>
<COMPLETE_STATUS></COMPLETE_STATUS>
<FORCED_STATUS_NAME></FORCED_STATUS_NAME>
<STATUS_NAME1></STATUS_NAME1>
<STATUS_NAME2></STATUS_NAME2>
<STATUS_NAME3></STATUS_NAME3>
<ALT_STATUS_TEXT></ALT_STATUS_TEXT>
<STATUS_CODE></STATUS_CODE>
<STATUS2_NAME1></STATUS2_NAME1>
<STATUS2_NAME2></STATUS2_NAME2>
<STATUS2_NAME3></STATUS2_NAME3>
<STATUS_CODE2></STATUS_CODE2>
<EXPIRATION></EXPIRATION>
<UPDATED></UPDATED>
<COMMENTS_LINE1></COMMENTS_LINE1>
<COMMENTS_LINE2></COMMENTS_LINE2>
<COMMENTS_LINE3></COMMENTS_LINE3>
<ADDRESS1>127 Jackson Street</ADDRESS1>
<ADDRESS2></ADDRESS2>
<CITY>Cullom</CITY>
<STATE>IL</STATE>
<ZIPCODE>60929</ZIPCODE>
<ORGANIZATION_HOMEPAGE>N/A</ORGANIZATION_HOMEPAGE>
</RECORD>
<RECORD>
<REC_ID>6168</REC_ID>
<FORCED_ORGANIZATION_NAME>American Legion Post #122</FORCED_ORGANIZATION_NAME>
<ORGANIZATION_NAME1>American Legion Post #122</ORGANIZATION_NAME1>
<ORGANIZATION_NAME2></ORGANIZATION_NAME2>
<ORGANIZATION_NAME3></ORGANIZATION_NAME3>
<ALT_ORGANIZATION_NAME></ALT_ORGANIZATION_NAME>
<FORCED_COUNTY_NAME></FORCED_COUNTY_NAME>
<COUNTY_NAME1></COUNTY_NAME1>
<COUNTY_NAME2></COUNTY_NAME2>
<ALT_COUNTY_NAME></ALT_COUNTY_NAME>
<FORCED_CATEGORY_NAME></FORCED_CATEGORY_NAME>
<CAT_CODE></CAT_CODE>
<CATEGORY_NAME1></CATEGORY_NAME1>
<CATEGORY_NAME2></CATEGORY_NAME2>
<COMPLETE_STATUS></COMPLETE_STATUS>
<FORCED_STATUS_NAME></FORCED_STATUS_NAME>
<STATUS_NAME1></STATUS_NAME1>
<STATUS_NAME2></STATUS_NAME2>
<STATUS_NAME3></STATUS_NAME3>
<ALT_STATUS_TEXT></ALT_STATUS_TEXT>
<STATUS_CODE></STATUS_CODE>
<STATUS2_NAME1></STATUS2_NAME1>
<STATUS2_NAME2></STATUS2_NAME2>
<STATUS2_NAME3></STATUS2_NAME3>
<STATUS_CODE2></STATUS_CODE2>
<EXPIRATION></EXPIRATION>
<UPDATED></UPDATED>
<COMMENTS_LINE1></COMMENTS_LINE1>
<COMMENTS_LINE2></COMMENTS_LINE2>
<COMMENTS_LINE3></COMMENTS_LINE3>
<ADDRESS1>P O Box 122</ADDRESS1>
<ADDRESS2></ADDRESS2>
<CITY>Cullom</CITY>
<STATE>IL</STATE>
<ZIPCODE>60929</ZIPCODE>
<ORGANIZATION_HOMEPAGE></ORGANIZATION_HOMEPAGE>
</RECORD>
<RECORD>
<REC_ID>6142</REC_ID>
<FORCED_ORGANIZATION_NAME>AMERICAN LEGION POST 210 DANVILLE IL</FORCED_ORGANIZATION_NAME>
<ORGANIZATION_NAME1>AMERICAN LEGION POST 210 DANVILLE IL</ORGANIZATION_NAME1>
<ORGANIZATION_NAME2></ORGANIZATION_NAME2>
<ORGANIZATION_NAME3></ORGANIZATION_NAME3>
<ALT_ORGANIZATION_NAME></ALT_ORGANIZATION_NAME>
<FORCED_COUNTY_NAME></FORCED_COUNTY_NAME>
<COUNTY_NAME1></COUNTY_NAME1>
<COUNTY_NAME2></COUNTY_NAME2>
<ALT_COUNTY_NAME></ALT_COUNTY_NAME>
<FORCED_CATEGORY_NAME></FORCED_CATEGORY_NAME>
<CAT_CODE></CAT_CODE>
<CATEGORY_NAME1></CATEGORY_NAME1>
<CATEGORY_NAME2></CATEGORY_NAME2>
<COMPLETE_STATUS></COMPLETE_STATUS>
<FORCED_STATUS_NAME></FORCED_STATUS_NAME>
<STATUS_NAME1></STATUS_NAME1>
<STATUS_NAME2></STATUS_NAME2>
<STATUS_NAME3></STATUS_NAME3>
<ALT_STATUS_TEXT></ALT_STATUS_TEXT>
<STATUS_CODE></STATUS_CODE>
<STATUS2_NAME1></STATUS2_NAME1>
<STATUS2_NAME2></STATUS2_NAME2>
<STATUS2_NAME3></STATUS2_NAME3>
<STATUS_CODE2></STATUS_CODE2>
<EXPIRATION></EXPIRATION>
<UPDATED></UPDATED>
<COMMENTS_LINE1></COMMENTS_LINE1>
<COMMENTS_LINE2></COMMENTS_LINE2>
<COMMENTS_LINE3></COMMENTS_LINE3>
<ADDRESS1>1218 E. Williams</ADDRESS1>
<ADDRESS2></ADDRESS2>
<CITY>danville</CITY>
<STATE>IL</STATE>
<ZIPCODE>61832</ZIPCODE>
<ORGANIZATION_HOMEPAGE></ORGANIZATION_HOMEPAGE>
</RECORD>
<RECORD>
<REC_ID>5883</REC_ID>
<FORCED_ORGANIZATION_NAME>Anabel Hulling Early Learning Center</FORCED_ORGANIZATION_NAME>
<ORGANIZATION_NAME1>Anabel Hulling Early Learning Center</ORGANIZATION_NAME1>
<ORGANIZATION_NAME2></ORGANIZATION_NAME2>
<ORGANIZATION_NAME3></ORGANIZATION_NAME3>
<ALT_ORGANIZATION_NAME></ALT_ORGANIZATION_NAME>
<FORCED_COUNTY_NAME></FORCED_COUNTY_NAME>
<COUNTY_NAME1></COUNTY_NAME1>
<COUNTY_NAME2></COUNTY_NAME2>
<ALT_COUNTY_NAME></ALT_COUNTY_NAME>
<FORCED_CATEGORY_NAME></FORCED_CATEGORY_NAME>
<CAT_CODE></CAT_CODE>
<CATEGORY_NAME1></CATEGORY_NAME1>
<CATEGORY_NAME2></CATEGORY_NAME2>
<COMPLETE_STATUS></COMPLETE_STATUS>
<FORCED_STATUS_NAME></FORCED_STATUS_NAME>
<STATUS_NAME1></STATUS_NAME1>
<STATUS_NAME2></STATUS_NAME2>
<STATUS_NAME3></STATUS_NAME3>
<ALT_STATUS_TEXT></ALT_STATUS_TEXT>
<STATUS_CODE></STATUS_CODE>
<STATUS2_NAME1></STATUS2_NAME1>
<STATUS2_NAME2></STATUS2_NAME2>
<STATUS2_NAME3></STATUS2_NAME3>
<STATUS_CODE2></STATUS_CODE2>
<EXPIRATION></EXPIRATION>
<UPDATED></UPDATED>
<COMMENTS_LINE1></COMMENTS_LINE1>
<COMMENTS_LINE2></COMMENTS_LINE2>
<COMMENTS_LINE3></COMMENTS_LINE3>
<ADDRESS1>106 N. Chanute</ADDRESS1>
<ADDRESS2></ADDRESS2>
<CITY>Rantoul</CITY>
<STATE>IL</STATE>
<ZIPCODE></ZIPCODE>
<ORGANIZATION_HOMEPAGE></ORGANIZATION_HOMEPAGE>
</RECORD>
<RECORD>
<REC_ID>5503</REC_ID>
<FORCED_ORGANIZATION_NAME>Apostolic Life</FORCED_ORGANIZATION_NAME>
<ORGANIZATION_NAME1>Apostolic Life</ORGANIZATION_NAME1>
<ORGANIZATION_NAME2></ORGANIZATION_NAME2>
<ORGANIZATION_NAME3></ORGANIZATION_NAME3>
<ALT_ORGANIZATION_NAME></ALT_ORGANIZATION_NAME>
<FORCED_COUNTY_NAME></FORCED_COUNTY_NAME>
<COUNTY_NAME1></COUNTY_NAME1>
<COUNTY_NAME2></COUNTY_NAME2>
<ALT_COUNTY_NAME></ALT_COUNTY_NAME>
<FORCED_CATEGORY_NAME></FORCED_CATEGORY_NAME>
<CAT_CODE></CAT_CODE>
<CATEGORY_NAME1></CATEGORY_NAME1>
<CATEGORY_NAME2></CATEGORY_NAME2>
<COMPLETE_STATUS></COMPLETE_STATUS>
<FORCED_STATUS_NAME></FORCED_STATUS_NAME>
<STATUS_NAME1></STATUS_NAME1>
<STATUS_NAME2></STATUS_NAME2>
<STATUS_NAME3></STATUS_NAME3>
<ALT_STATUS_TEXT></ALT_STATUS_TEXT>
<STATUS_CODE></STATUS_CODE>
<STATUS2_NAME1></STATUS2_NAME1>
<STATUS2_NAME2></STATUS2_NAME2>
<STATUS2_NAME3></STATUS2_NAME3>
<STATUS_CODE2></STATUS_CODE2>
<EXPIRATION></EXPIRATION>
<UPDATED></UPDATED>
<COMMENTS_LINE1></COMMENTS_LINE1>
<COMMENTS_LINE2></COMMENTS_LINE2>
<COMMENTS_LINE3></COMMENTS_LINE3>
<ADDRESS1></ADDRESS1>
<ADDRESS2></ADDRESS2>
<CITY>Urbana</CITY>
<STATE>IL</STATE>
<ZIPCODE></ZIPCODE>
<ORGANIZATION_HOMEPAGE></ORGANIZATION_HOMEPAGE>
</RECORD>
<RECORD>
<REC_ID>6159</REC_ID>
<FORCED_ORGANIZATION_NAME>Apostolic New Birth Church</FORCED_ORGANIZATION_NAME>
<ORGANIZATION_NAME1>Apostolic New Birth Church</ORGANIZATION_NAME1>
<ORGANIZATION_NAME2></ORGANIZATION_NAME2>
<ORGANIZATION_NAME3></ORGANIZATION_NAME3>
<ALT_ORGANIZATION_NAME></ALT_ORGANIZATION_NAME>
<FORCED_COUNTY_NAME></FORCED_COUNTY_NAME>
<COUNTY_NAME1></COUNTY_NAME1>
<COUNTY_NAME2></COUNTY_NAME2>
<ALT_COUNTY_NAME></ALT_COUNTY_NAME>
<FORCED_CATEGORY_NAME></FORCED_CATEGORY_NAME>
<CAT_CODE></CAT_CODE>
<CATEGORY_NAME1></CATEGORY_NAME1>
<CATEGORY_NAME2></CATEGORY_NAME2>
<COMPLETE_STATUS></COMPLETE_STATUS>
<FORCED_STATUS_NAME></FORCED_STATUS_NAME>
<STATUS_NAME1></STATUS_NAME1>
<STATUS_NAME2></STATUS_NAME2>
<STATUS_NAME3></STATUS_NAME3>
<ALT_STATUS_TEXT></ALT_STATUS_TEXT>
<STATUS_CODE></STATUS_CODE>
<STATUS2_NAME1></STATUS2_NAME1>
<STATUS2_NAME2></STATUS2_NAME2>
<STATUS2_NAME3></STATUS2_NAME3>
<STATUS_CODE2></STATUS_CODE2>
<EXPIRATION></EXPIRATION>
<UPDATED></UPDATED>
<COMMENTS_LINE1></COMMENTS_LINE1>
<COMMENTS_LINE2></COMMENTS_LINE2>
<COMMENTS_LINE3></COMMENTS_LINE3>
<ADDRESS1>102 W. Williams</ADDRESS1>
<ADDRESS2></ADDRESS2>
<CITY>Danville</CITY>
<STATE>IL</STATE>
<ZIPCODE>61832</ZIPCODE>
<ORGANIZATION_HOMEPAGE></ORGANIZATION_HOMEPAGE>
</RECORD>
<RECORD>
<REC_ID>6166</REC_ID>
<FORCED_ORGANIZATION_NAME>Arcola Food Pantry</FORCED_ORGANIZATION_NAME>
<ORGANIZATION_NAME1>Arcola Food Pantry</ORGANIZATION_NAME1>
<ORGANIZATION_NAME2></ORGANIZATION_NAME2>
<ORGANIZATION_NAME3></ORGANIZATION_NAME3>
<ALT_ORGANIZATION_NAME></ALT_ORGANIZATION_NAME>
<FORCED_COUNTY_NAME></FORCED_COUNTY_NAME>
<COUNTY_NAME1></COUNTY_NAME1>
<COUNTY_NAME2></COUNTY_NAME2>
<ALT_COUNTY_NAME></ALT_COUNTY_NAME>
<FORCED_CATEGORY_NAME></FORCED_CATEGORY_NAME>
<CAT_CODE></CAT_CODE>
<CATEGORY_NAME1></CATEGORY_NAME1>
<CATEGORY_NAME2></CATEGORY_NAME2>
<COMPLETE_STATUS></COMPLETE_STATUS>
<FORCED_STATUS_NAME></FORCED_STATUS_NAME>
<STATUS_NAME1></STATUS_NAME1>
<STATUS_NAME2></STATUS_NAME2>
<STATUS_NAME3></STATUS_NAME3>
<ALT_STATUS_TEXT></ALT_STATUS_TEXT>
<STATUS_CODE></STATUS_CODE>
<STATUS2_NAME1></STATUS2_NAME1>
<STATUS2_NAME2></STATUS2_NAME2>
<STATUS2_NAME3></STATUS2_NAME3>
<STATUS_CODE2></STATUS_CODE2>
<EXPIRATION></EXPIRATION>
<UPDATED></UPDATED>
<COMMENTS_LINE1></COMMENTS_LINE1>
<COMMENTS_LINE2></COMMENTS_LINE2>
<COMMENTS_LINE3></COMMENTS_LINE3>
<ADDRESS1>126 S. Locust</ADDRESS1>
<ADDRESS2></ADDRESS2>
<CITY>Arcola</CITY>
<STATE>IL</STATE>
<ZIPCODE>61910</ZIPCODE>
<ORGANIZATION_HOMEPAGE></ORGANIZATION_HOMEPAGE>
</RECORD>
<RECORD>
<REC_ID>6143</REC_ID>
<FORCED_ORGANIZATION_NAME>Arthur Public Library</FORCED_ORGANIZATION_NAME>
<ORGANIZATION_NAME1>Arthur Public Library</ORGANIZATION_NAME1>
<ORGANIZATION_NAME2></ORGANIZATION_NAME2>
<ORGANIZATION_NAME3></ORGANIZATION_NAME3>
<ALT_ORGANIZATION_NAME></ALT_ORGANIZATION_NAME>
<FORCED_COUNTY_NAME></FORCED_COUNTY_NAME>
<COUNTY_NAME1></COUNTY_NAME1>
<COUNTY_NAME2></COUNTY_NAME2>
<ALT_COUNTY_NAME></ALT_COUNTY_NAME>
<FORCED_CATEGORY_NAME></FORCED_CATEGORY_NAME>
<CAT_CODE></CAT_CODE>
<CATEGORY_NAME1></CATEGORY_NAME1>
<CATEGORY_NAME2></CATEGORY_NAME2>
<COMPLETE_STATUS></COMPLETE_STATUS>
<FORCED_STATUS_NAME></FORCED_STATUS_NAME>
<STATUS_NAME1></STATUS_NAME1>
<STATUS_NAME2></STATUS_NAME2>
<STATUS_NAME3></STATUS_NAME3>
<ALT_STATUS_TEXT></ALT_STATUS_TEXT>
<STATUS_CODE></STATUS_CODE>
<STATUS2_NAME1></STATUS2_NAME1>
<STATUS2_NAME2></STATUS2_NAME2>
<STATUS2_NAME3></STATUS2_NAME3>
<STATUS_CODE2></STATUS_CODE2>
<EXPIRATION></EXPIRATION>
<UPDATED></UPDATED>
<COMMENTS_LINE1></COMMENTS_LINE1>
<COMMENTS_LINE2></COMMENTS_LINE2>
<COMMENTS_LINE3></COMMENTS_LINE3>
<ADDRESS1>225 S. Walnut</ADDRESS1>
<ADDRESS2></ADDRESS2>
<CITY>Arthur</CITY>
<STATE>IL</STATE>
<ZIPCODE>61911</ZIPCODE>
<ORGANIZATION_HOMEPAGE></ORGANIZATION_HOMEPAGE>
</RECORD>
<RECORD>
<REC_ID>6141</REC_ID>
<FORCED_ORGANIZATION_NAME>Arthur United Methodist Church</FORCED_ORGANIZATION_NAME>
<ORGANIZATION_NAME1>Arthur United Methodist Church</ORGANIZATION_NAME1>
<ORGANIZATION_NAME2></ORGANIZATION_NAME2>
<ORGANIZATION_NAME3></ORGANIZATION_NAME3>
<ALT_ORGANIZATION_NAME></ALT_ORGANIZATION_NAME>
<FORCED_COUNTY_NAME></FORCED_COUNTY_NAME>
<COUNTY_NAME1></COUNTY_NAME1>
<COUNTY_NAME2></COUNTY_NAME2>
<ALT_COUNTY_NAME></ALT_COUNTY_NAME>
<FORCED_CATEGORY_NAME></FORCED_CATEGORY_NAME>
<CAT_CODE></CAT_CODE>
<CATEGORY_NAME1></CATEGORY_NAME1>
<CATEGORY_NAME2></CATEGORY_NAME2>
<COMPLETE_STATUS></COMPLETE_STATUS>
<FORCED_STATUS_NAME></FORCED_STATUS_NAME>
<STATUS_NAME1></STATUS_NAME1>
<STATUS_NAME2></STATUS_NAME2>
<STATUS_NAME3></STATUS_NAME3>
<ALT_STATUS_TEXT></ALT_STATUS_TEXT>
<STATUS_CODE></STATUS_CODE>
<STATUS2_NAME1></STATUS2_NAME1>
<STATUS2_NAME2></STATUS2_NAME2>
<STATUS2_NAME3></STATUS2_NAME3>
<STATUS_CODE2></STATUS_CODE2>
<EXPIRATION></EXPIRATION>
<UPDATED></UPDATED>
<COMMENTS_LINE1></COMMENTS_LINE1>
<COMMENTS_LINE2></COMMENTS_LINE2>
<COMMENTS_LINE3></COMMENTS_LINE3>
<ADDRESS1>128 E. Illinois</ADDRESS1>
<ADDRESS2></ADDRESS2>
<CITY>Arthur</CITY>
<STATE>IL</STATE>
<ZIPCODE>61911</ZIPCODE>
<ORGANIZATION_HOMEPAGE></ORGANIZATION_HOMEPAGE>
</RECORD>
<RECORD>
<REC_ID>6293</REC_ID>
<FORCED_ORGANIZATION_NAME>Attorneys' Title Guaranty Fund, Inc.</FORCED_ORGANIZATION_NAME>
<ORGANIZATION_NAME1>Attorneys' Title Guaranty Fund, Inc.</ORGANIZATION_NAME1>
<ORGANIZATION_NAME2>Champaign</ORGANIZATION_NAME2>
<ORGANIZATION_NAME3></ORGANIZATION_NAME3>
<ALT_ORGANIZATION_NAME></ALT_ORGANIZATION_NAME>
<FORCED_COUNTY_NAME></FORCED_COUNTY_NAME>
<COUNTY_NAME1></COUNTY_NAME1>
<COUNTY_NAME2></COUNTY_NAME2>
<ALT_COUNTY_NAME></ALT_COUNTY_NAME>
<FORCED_CATEGORY_NAME></FORCED_CATEGORY_NAME>
<CAT_CODE></CAT_CODE>
<CATEGORY_NAME1></CATEGORY_NAME1>
<CATEGORY_NAME2></CATEGORY_NAME2>
<COMPLETE_STATUS></COMPLETE_STATUS>
<FORCED_STATUS_NAME></FORCED_STATUS_NAME>
<STATUS_NAME1></STATUS_NAME1>
<STATUS_NAME2></STATUS_NAME2>
<STATUS_NAME3></STATUS_NAME3>
<ALT_STATUS_TEXT></ALT_STATUS_TEXT>
<STATUS_CODE></STATUS_CODE>
<STATUS2_NAME1></STATUS2_NAME1>
<STATUS2_NAME2></STATUS2_NAME2>
<STATUS2_NAME3></STATUS2_NAME3>
<STATUS_CODE2></STATUS_CODE2>
<EXPIRATION></EXPIRATION>
<UPDATED></UPDATED>
<COMMENTS_LINE1></COMMENTS_LINE1>
<COMMENTS_LINE2></COMMENTS_LINE2>
<COMMENTS_LINE3></COMMENTS_LINE3>
<ADDRESS1></ADDRESS1>
<ADDRESS2></ADDRESS2>
<CITY></CITY>
<STATE>IL</STATE>
<ZIPCODE></ZIPCODE>
<ORGANIZATION_HOMEPAGE></ORGANIZATION_HOMEPAGE>
</RECORD>
<RECORD>
<REC_ID>6127</REC_ID>
<FORCED_ORGANIZATION_NAME>Audibel Hearing Centers</FORCED_ORGANIZATION_NAME>
<ORGANIZATION_NAME1>Audibel Hearing Centers</ORGANIZATION_NAME1>
<ORGANIZATION_NAME2></ORGANIZATION_NAME2>
<ORGANIZATION_NAME3></ORGANIZATION_NAME3>
<ALT_ORGANIZATION_NAME></ALT_ORGANIZATION_NAME>
<FORCED_COUNTY_NAME></FORCED_COUNTY_NAME>
<COUNTY_NAME1></COUNTY_NAME1>
<COUNTY_NAME2></COUNTY_NAME2>
<ALT_COUNTY_NAME></ALT_COUNTY_NAME>
<FORCED_CATEGORY_NAME></FORCED_CATEGORY_NAME>
<CAT_CODE></CAT_CODE>
<CATEGORY_NAME1></CATEGORY_NAME1>
<CATEGORY_NAME2></CATEGORY_NAME2>
<COMPLETE_STATUS></COMPLETE_STATUS>
<FORCED_STATUS_NAME></FORCED_STATUS_NAME>
<STATUS_NAME1></STATUS_NAME1>
<STATUS_NAME2></STATUS_NAME2>
<STATUS_NAME3></STATUS_NAME3>
<ALT_STATUS_TEXT></ALT_STATUS_TEXT>
<STATUS_CODE></STATUS_CODE>
<STATUS2_NAME1></STATUS2_NAME1>
<STATUS2_NAME2></STATUS2_NAME2>
<STATUS2_NAME3></STATUS2_NAME3>
<STATUS_CODE2></STATUS_CODE2>
<EXPIRATION></EXPIRATION>
<UPDATED></UPDATED>
<COMMENTS_LINE1></COMMENTS_LINE1>
<COMMENTS_LINE2></COMMENTS_LINE2>
<COMMENTS_LINE3></COMMENTS_LINE3>
<ADDRESS1>1901 N. Market St. - T6</ADDRESS1>
<ADDRESS2></ADDRESS2>
<CITY>Champaign</CITY>
<STATE>IL</STATE>
<ZIPCODE>61822</ZIPCODE>
<ORGANIZATION_HOMEPAGE></ORGANIZATION_HOMEPAGE>
</RECORD>
<RECORD>
<REC_ID>6109</REC_ID>
<FORCED_ORGANIZATION_NAME>Bard Optical</FORCED_ORGANIZATION_NAME>
<ORGANIZATION_NAME1>Bard Optical</ORGANIZATION_NAME1>
<ORGANIZATION_NAME2></ORGANIZATION_NAME2>
<ORGANIZATION_NAME3></ORGANIZATION_NAME3>
<ALT_ORGANIZATION_NAME></ALT_ORGANIZATION_NAME>
<FORCED_COUNTY_NAME></FORCED_COUNTY_NAME>
<COUNTY_NAME1></COUNTY_NAME1>
<COUNTY_NAME2></COUNTY_NAME2>
<ALT_COUNTY_NAME></ALT_COUNTY_NAME>
<FORCED_CATEGORY_NAME></FORCED_CATEGORY_NAME>
<CAT_CODE></CAT_CODE>
<CATEGORY_NAME1></CATEGORY_NAME1>
<CATEGORY_NAME2></CATEGORY_NAME2>
<COMPLETE_STATUS></COMPLETE_STATUS>
<FORCED_STATUS_NAME></FORCED_STATUS_NAME>
<STATUS_NAME1></STATUS_NAME1>
<STATUS_NAME2></STATUS_NAME2>
<STATUS_NAME3></STATUS_NAME3>
<ALT_STATUS_TEXT></ALT_STATUS_TEXT>
<STATUS_CODE></STATUS_CODE>
<STATUS2_NAME1></STATUS2_NAME1>
<STATUS2_NAME2></STATUS2_NAME2>
<STATUS2_NAME3></STATUS2_NAME3>
<STATUS_CODE2></STATUS_CODE2>
<EXPIRATION></EXPIRATION>
<UPDATED></UPDATED>
<COMMENTS_LINE1></COMMENTS_LINE1>
<COMMENTS_LINE2></COMMENTS_LINE2>
<COMMENTS_LINE3></COMMENTS_LINE3>
<ADDRESS1>304 Peacock</ADDRESS1>
<ADDRESS2></ADDRESS2>
<CITY>Champaign</CITY>
<STATE>IL</STATE>
<ZIPCODE>61822</ZIPCODE>
<ORGANIZATION_HOMEPAGE></ORGANIZATION_HOMEPAGE>
</RECORD>
<RECORD>
<REC_ID>4204</REC_ID>
<FORCED_ORGANIZATION_NAME>Beecher City</FORCED_ORGANIZATION_NAME>
<ORGANIZATION_NAME1>Beecher City</ORGANIZATION_NAME1>
<ORGANIZATION_NAME2></ORGANIZATION_NAME2>
<ORGANIZATION_NAME3></ORGANIZATION_NAME3>
<ALT_ORGANIZATION_NAME></ALT_ORGANIZATION_NAME>
<FORCED_COUNTY_NAME></FORCED_COUNTY_NAME>
<COUNTY_NAME1></COUNTY_NAME1>
<COUNTY_NAME2></COUNTY_NAME2>
<ALT_COUNTY_NAME></ALT_COUNTY_NAME>
<FORCED_CATEGORY_NAME></FORCED_CATEGORY_NAME>
<CAT_CODE></CAT_CODE>
<CATEGORY_NAME1></CATEGORY_NAME1>
<CATEGORY_NAME2></CATEGORY_NAME2>
<COMPLETE_STATUS></COMPLETE_STATUS>
<FORCED_STATUS_NAME></FORCED_STATUS_NAME>
<STATUS_NAME1></STATUS_NAME1>
<STATUS_NAME2></STATUS_NAME2>
<STATUS_NAME3></STATUS_NAME3>
<ALT_STATUS_TEXT></ALT_STATUS_TEXT>
<STATUS_CODE></STATUS_CODE>
<STATUS2_NAME1></STATUS2_NAME1>
<STATUS2_NAME2></STATUS2_NAME2>
<STATUS2_NAME3></STATUS2_NAME3>
<STATUS_CODE2></STATUS_CODE2>
<EXPIRATION></EXPIRATION>
<UPDATED></UPDATED>
<COMMENTS_LINE1></COMMENTS_LINE1>
<COMMENTS_LINE2></COMMENTS_LINE2>
<COMMENTS_LINE3></COMMENTS_LINE3>
<ADDRESS1>P.O. Box 98</ADDRESS1>
<ADDRESS2></ADDRESS2>
<CITY>Beecher City</CITY>
<STATE>IL</STATE>
<ZIPCODE>62414</ZIPCODE>
<ORGANIZATION_HOMEPAGE></ORGANIZATION_HOMEPAGE>
</RECORD>
<RECORD>
<REC_ID>6184</REC_ID>
<FORCED_ORGANIZATION_NAME>Bell Ridge Christian Church</FORCED_ORGANIZATION_NAME>
<ORGANIZATION_NAME1>Bell Ridge Christian Church</ORGANIZATION_NAME1>
<ORGANIZATION_NAME2></ORGANIZATION_NAME2>
<ORGANIZATION_NAME3></ORGANIZATION_NAME3>
<ALT_ORGANIZATION_NAME></ALT_ORGANIZATION_NAME>
<FORCED_COUNTY_NAME></FORCED_COUNTY_NAME>
<COUNTY_NAME1></COUNTY_NAME1>
<COUNTY_NAME2></COUNTY_NAME2>
<ALT_COUNTY_NAME></ALT_COUNTY_NAME>
<FORCED_CATEGORY_NAME></FORCED_CATEGORY_NAME>
<CAT_CODE></CAT_CODE>
<CATEGORY_NAME1></CATEGORY_NAME1>
<CATEGORY_NAME2></CATEGORY_NAME2>
<COMPLETE_STATUS></COMPLETE_STATUS>
<FORCED_STATUS_NAME></FORCED_STATUS_NAME>
<STATUS_NAME1></STATUS_NAME1>
<STATUS_NAME2></STATUS_NAME2>
<STATUS_NAME3></STATUS_NAME3>
<ALT_STATUS_TEXT></ALT_STATUS_TEXT>
<STATUS_CODE></STATUS_CODE>
<STATUS2_NAME1></STATUS2_NAME1>
<STATUS2_NAME2></STATUS2_NAME2>
<STATUS2_NAME3></STATUS2_NAME3>
<STATUS_CODE2></STATUS_CODE2>
<EXPIRATION></EXPIRATION>
<UPDATED></UPDATED>
<COMMENTS_LINE1></COMMENTS_LINE1>
<COMMENTS_LINE2></COMMENTS_LINE2>
<COMMENTS_LINE3></COMMENTS_LINE3>
<ADDRESS1>10535 E. 225th Road</ADDRESS1>
<ADDRESS2></ADDRESS2>
<CITY>Paris</CITY>
<STATE>IL</STATE>
<ZIPCODE>61944</ZIPCODE>
<ORGANIZATION_HOMEPAGE></ORGANIZATION_HOMEPAGE>
</RECORD>
<RECORD>
<REC_ID>6169</REC_ID>
<FORCED_ORGANIZATION_NAME>Bell Sports</FORCED_ORGANIZATION_NAME>
<ORGANIZATION_NAME1>Bell Sports</ORGANIZATION_NAME1>
<ORGANIZATION_NAME2></ORGANIZATION_NAME2>
<ORGANIZATION_NAME3></ORGANIZATION_NAME3>
<ALT_ORGANIZATION_NAME></ALT_ORGANIZATION_NAME>
<FORCED_COUNTY_NAME></FORCED_COUNTY_NAME>
<COUNTY_NAME1></COUNTY_NAME1>
<COUNTY_NAME2></COUNTY_NAME2>
<ALT_COUNTY_NAME></ALT_COUNTY_NAME>
<FORCED_CATEGORY_NAME></FORCED_CATEGORY_NAME>
<CAT_CODE></CAT_CODE>
<CATEGORY_NAME1></CATEGORY_NAME1>
<CATEGORY_NAME2></CATEGORY_NAME2>
<COMPLETE_STATUS></COMPLETE_STATUS>
<FORCED_STATUS_NAME></FORCED_STATUS_NAME>
<STATUS_NAME1></STATUS_NAME1>
<STATUS_NAME2></STATUS_NAME2>
<STATUS_NAME3></STATUS_NAME3>
<ALT_STATUS_TEXT></ALT_STATUS_TEXT>