<?xml version="1.0" standalone="no" ?>
<!DOCTYPE DATA [
  <!ELEMENT DATA                     (SOURCE,EXPORT_TYPE,NUM_CLOSINGS,RUN_DATE,RUN_EPOCH,RECORD*)>
  <!ELEMENT SOURCE                   (CDATA)>
  <!ELEMENT EXPORT_TYPE              (CDATA)>
  <!ELEMENT NUM_CLOSINGS             (CDATA)>
  <!ELEMENT RUN_DATE                 (CDATA)>
  <!ELEMENT RUN_EPOCH                (CDATA)>
  <!ELEMENT RECORD                   (REC_ID,FORCED_ORGANIZATION_NAME,ORGANIZATION_NAME1,ORGANIZATION_NAME2,ORGANIZATION_NAME3,ALT_ORGANIZATION_NAME,FORCED_COUNTY_NAME,COUNTY_NAME1,COUNTY_NAME2,ALT_COUNTY_NAME,CAT_CODE,CATEGORY_NAME1,CATEGORY_NAME2,FORCED_STATUS_NAME,STATUS_NAME1,STATUS_NAME2,STATUS_NAME3,ALT_STATUS_TEXT,STATUS_CODE,STATUS2_NAME1,STATUS2_NAME2,STATUS2_NAME3,STATUS_CODE2,EXPIRATION,UPDATED,COMMENTS_LINE1,COMMENTS_LINE2,COMMENTS_LINE3,ADDRESS1,ADDRESS2,CITY,STATE,ZIPCODE,ORGANIZATION_HOMEPAGE)>
  <!ELEMENT REC_ID                   (ID)>
  <!ELEMENT FORCED_ORGANIZATION_NAME (CDATA)>
  <!ELEMENT ORGANIZATION_NAME1       (CDATA)>
  <!ELEMENT ORGANIZATION_NAME2       (CDATA)>
  <!ELEMENT ORGANIZATION_NAME3       (CDATA)>
  <!ELEMENT ALT_ORGANIZATION_NAME    (CDATA)>
  <!ELEMENT FORCED_COUNTY_NAME       (CDATA)>
  <!ELEMENT COUNTY_NAME1             (CDATA)>
  <!ELEMENT COUNTY_NAME2             (CDATA)>
  <!ELEMENT ALT_COUNTY_NAME          (CDATA)>
  <!ELEMENT CAT_CODE                 (CDATA)>
  <!ELEMENT CATEGORY_NAME1           (CDATA)>
  <!ELEMENT CATEGORY_NAME2           (CDATA)>
  <!ELEMENT FORCED_STATUS_NAME       (CDATA)>
  <!ELEMENT STATUS_NAME1             (CDATA)>
  <!ELEMENT STATUS_NAME2             (CDATA)>
  <!ELEMENT STATUS_NAME3             (CDATA)>
  <!ELEMENT ALT_STATUS_TEXT          (CDATA)>
  <!ELEMENT STATUS_CODE              (CDATA)>
  <!ELEMENT STATUS2_NAME1            (CDATA)>
  <!ELEMENT STATUS2_NAME2            (CDATA)>
  <!ELEMENT STATUS2_NAME3            (CDATA)>
  <!ELEMENT STATUS_CODE2             (CDATA)>
  <!ELEMENT EXPIRATION               (CDATA)>
  <!ELEMENT UPDATED                  (CDATA)>
  <!ELEMENT COMMENTS_LINE1           (CDATA)>
  <!ELEMENT COMMENTS_LINE2           (CDATA)>
  <!ELEMENT COMMENTS_LINE3           (CDATA)>
  <!ELEMENT ADDRESS1                 (CDATA)>
  <!ELEMENT ADDRESS2                 (CDATA)>
  <!ELEMENT CITY                     (CDATA)>
  <!ELEMENT STATE                    (CDATA)>
  <!ELEMENT ZIPCODE                  (CDATA)>
  <!ELEMENT ORGANIZATION_HOMEPAGE    (CDATA)>
]>
<DATA>
<SOURCE>NewsTicker</SOURCE>
<EXPORT_TYPE>L2</EXPORT_TYPE>
<NUM_CLOSINGS>1086</NUM_CLOSINGS>
<RUN_DATE>Wed Oct 14 03:03:02 EDT 2015</RUN_DATE>
<RUN_EPOCH>1444806182</RUN_EPOCH>
<RECORD>
<REC_ID>1001477</REC_ID>
<FORCED_ORGANIZATION_NAME></FORCED_ORGANIZATION_NAME>
<ORGANIZATION_NAME1></ORGANIZATION_NAME1>
<ORGANIZATION_NAME2></ORGANIZATION_NAME2>
<ORGANIZATION_NAME3></ORGANIZATION_NAME3>
<ALT_ORGANIZATION_NAME></ALT_ORGANIZATION_NAME>
<FORCED_COUNTY_NAME></FORCED_COUNTY_NAME>
<COUNTY_NAME1></COUNTY_NAME1>
<COUNTY_NAME2></COUNTY_NAME2>
<ALT_COUNTY_NAME></ALT_COUNTY_NAME>
<FORCED_CATEGORY_NAME></FORCED_CATEGORY_NAME>
<CAT_CODE></CAT_CODE>
<CATEGORY_NAME1></CATEGORY_NAME1>
<CATEGORY_NAME2></CATEGORY_NAME2>
<FORCED_STATUS_NAME></FORCED_STATUS_NAME>
<STATUS_NAME1></STATUS_NAME1>
<STATUS_NAME2></STATUS_NAME2>
<STATUS_NAME3></STATUS_NAME3>
<ALT_STATUS_TEXT></ALT_STATUS_TEXT>
<STATUS_CODE></STATUS_CODE>
<STATUS2_NAME1></STATUS2_NAME1>
<STATUS2_NAME2></STATUS2_NAME2>
<STATUS2_NAME3></STATUS2_NAME3>
<STATUS_CODE2></STATUS_CODE2>
<EXPIRATION></EXPIRATION>
<UPDATED></UPDATED>
<COMMENTS_LINE1></COMMENTS_LINE1>
<COMMENTS_LINE2></COMMENTS_LINE2>
<COMMENTS_LINE3></COMMENTS_LINE3>
<ADDRESS1></ADDRESS1>
<ADDRESS2></ADDRESS2>
<CITY></CITY>
<STATE>NY</STATE>
<ZIPCODE></ZIPCODE>
<ORGANIZATION_HOMEPAGE></ORGANIZATION_HOMEPAGE>
</RECORD>
<RECORD>
<REC_ID>1000541</REC_ID>
<FORCED_ORGANIZATION_NAME></FORCED_ORGANIZATION_NAME>
<ORGANIZATION_NAME1></ORGANIZATION_NAME1>
<ORGANIZATION_NAME2></ORGANIZATION_NAME2>
<ORGANIZATION_NAME3></ORGANIZATION_NAME3>
<ALT_ORGANIZATION_NAME></ALT_ORGANIZATION_NAME>
<FORCED_COUNTY_NAME></FORCED_COUNTY_NAME>
<COUNTY_NAME1></COUNTY_NAME1>
<COUNTY_NAME2></COUNTY_NAME2>
<ALT_COUNTY_NAME></ALT_COUNTY_NAME>
<FORCED_CATEGORY_NAME></FORCED_CATEGORY_NAME>
<CAT_CODE></CAT_CODE>
<CATEGORY_NAME1></CATEGORY_NAME1>
<CATEGORY_NAME2></CATEGORY_NAME2>
<FORCED_STATUS_NAME></FORCED_STATUS_NAME>
<STATUS_NAME1></STATUS_NAME1>
<STATUS_NAME2></STATUS_NAME2>
<STATUS_NAME3></STATUS_NAME3>
<ALT_STATUS_TEXT></ALT_STATUS_TEXT>
<STATUS_CODE></STATUS_CODE>
<STATUS2_NAME1></STATUS2_NAME1>
<STATUS2_NAME2></STATUS2_NAME2>
<STATUS2_NAME3></STATUS2_NAME3>
<STATUS_CODE2></STATUS_CODE2>
<EXPIRATION></EXPIRATION>
<UPDATED></UPDATED>
<COMMENTS_LINE1></COMMENTS_LINE1>
<COMMENTS_LINE2></COMMENTS_LINE2>
<COMMENTS_LINE3></COMMENTS_LINE3>
<ADDRESS1></ADDRESS1>
<ADDRESS2></ADDRESS2>
<CITY></CITY>
<STATE>NY</STATE>
<ZIPCODE></ZIPCODE>
<ORGANIZATION_HOMEPAGE></ORGANIZATION_HOMEPAGE>
</RECORD>
<RECORD>
<REC_ID>1000665</REC_ID>
<FORCED_ORGANIZATION_NAME>7th Day Adventist Church, Westvale</FORCED_ORGANIZATION_NAME>
<ORGANIZATION_NAME1>7th Day Adventist Church, Westvale</ORGANIZATION_NAME1>
<ORGANIZATION_NAME2></ORGANIZATION_NAME2>
<ORGANIZATION_NAME3></ORGANIZATION_NAME3>
<ALT_ORGANIZATION_NAME></ALT_ORGANIZATION_NAME>
<FORCED_COUNTY_NAME></FORCED_COUNTY_NAME>
<COUNTY_NAME1></COUNTY_NAME1>
<COUNTY_NAME2></COUNTY_NAME2>
<ALT_COUNTY_NAME></ALT_COUNTY_NAME>
<FORCED_CATEGORY_NAME></FORCED_CATEGORY_NAME>
<CAT_CODE></CAT_CODE>
<CATEGORY_NAME1></CATEGORY_NAME1>
<CATEGORY_NAME2></CATEGORY_NAME2>
<FORCED_STATUS_NAME></FORCED_STATUS_NAME>
<STATUS_NAME1></STATUS_NAME1>
<STATUS_NAME2></STATUS_NAME2>
<STATUS_NAME3></STATUS_NAME3>
<ALT_STATUS_TEXT></ALT_STATUS_TEXT>
<STATUS_CODE></STATUS_CODE>
<STATUS2_NAME1></STATUS2_NAME1>
<STATUS2_NAME2></STATUS2_NAME2>
<STATUS2_NAME3></STATUS2_NAME3>
<STATUS_CODE2></STATUS_CODE2>
<EXPIRATION></EXPIRATION>
<UPDATED></UPDATED>
<COMMENTS_LINE1></COMMENTS_LINE1>
<COMMENTS_LINE2></COMMENTS_LINE2>
<COMMENTS_LINE3></COMMENTS_LINE3>
<ADDRESS1></ADDRESS1>
<ADDRESS2></ADDRESS2>
<CITY></CITY>
<STATE>NY</STATE>
<ZIPCODE></ZIPCODE>
<ORGANIZATION_HOMEPAGE></ORGANIZATION_HOMEPAGE>
</RECORD>
<RECORD>
<REC_ID>1001141</REC_ID>
<FORCED_ORGANIZATION_NAME>A&amp;E Transport, Minetto</FORCED_ORGANIZATION_NAME>
<ORGANIZATION_NAME1>A&amp;E Transport, Minetto</ORGANIZATION_NAME1>
<ORGANIZATION_NAME2></ORGANIZATION_NAME2>
<ORGANIZATION_NAME3></ORGANIZATION_NAME3>
<ALT_ORGANIZATION_NAME></ALT_ORGANIZATION_NAME>
<FORCED_COUNTY_NAME></FORCED_COUNTY_NAME>
<COUNTY_NAME1></COUNTY_NAME1>
<COUNTY_NAME2></COUNTY_NAME2>
<ALT_COUNTY_NAME></ALT_COUNTY_NAME>
<FORCED_CATEGORY_NAME></FORCED_CATEGORY_NAME>
<CAT_CODE></CAT_CODE>
<CATEGORY_NAME1></CATEGORY_NAME1>
<CATEGORY_NAME2></CATEGORY_NAME2>
<FORCED_STATUS_NAME></FORCED_STATUS_NAME>
<STATUS_NAME1></STATUS_NAME1>
<STATUS_NAME2></STATUS_NAME2>
<STATUS_NAME3></STATUS_NAME3>
<ALT_STATUS_TEXT></ALT_STATUS_TEXT>
<STATUS_CODE></STATUS_CODE>
<STATUS2_NAME1></STATUS2_NAME1>
<STATUS2_NAME2></STATUS2_NAME2>
<STATUS2_NAME3></STATUS2_NAME3>
<STATUS_CODE2></STATUS_CODE2>
<EXPIRATION></EXPIRATION>
<UPDATED></UPDATED>
<COMMENTS_LINE1></COMMENTS_LINE1>
<COMMENTS_LINE2></COMMENTS_LINE2>
<COMMENTS_LINE3></COMMENTS_LINE3>
<ADDRESS1></ADDRESS1>
<ADDRESS2></ADDRESS2>
<CITY></CITY>
<STATE>NY</STATE>
<ZIPCODE></ZIPCODE>
<ORGANIZATION_HOMEPAGE></ORGANIZATION_HOMEPAGE>
</RECORD>
<RECORD>
<REC_ID>1001321</REC_ID>
<FORCED_ORGANIZATION_NAME>ABC Dance Academy</FORCED_ORGANIZATION_NAME>
<ORGANIZATION_NAME1>ABC Dance Academy</ORGANIZATION_NAME1>
<ORGANIZATION_NAME2></ORGANIZATION_NAME2>
<ORGANIZATION_NAME3></ORGANIZATION_NAME3>
<ALT_ORGANIZATION_NAME></ALT_ORGANIZATION_NAME>
<FORCED_COUNTY_NAME></FORCED_COUNTY_NAME>
<COUNTY_NAME1></COUNTY_NAME1>
<COUNTY_NAME2></COUNTY_NAME2>
<ALT_COUNTY_NAME></ALT_COUNTY_NAME>
<FORCED_CATEGORY_NAME></FORCED_CATEGORY_NAME>
<CAT_CODE></CAT_CODE>
<CATEGORY_NAME1></CATEGORY_NAME1>
<CATEGORY_NAME2></CATEGORY_NAME2>
<FORCED_STATUS_NAME></FORCED_STATUS_NAME>
<STATUS_NAME1></STATUS_NAME1>
<STATUS_NAME2></STATUS_NAME2>
<STATUS_NAME3></STATUS_NAME3>
<ALT_STATUS_TEXT></ALT_STATUS_TEXT>
<STATUS_CODE></STATUS_CODE>
<STATUS2_NAME1></STATUS2_NAME1>
<STATUS2_NAME2></STATUS2_NAME2>
<STATUS2_NAME3></STATUS2_NAME3>
<STATUS_CODE2></STATUS_CODE2>
<EXPIRATION></EXPIRATION>
<UPDATED></UPDATED>
<COMMENTS_LINE1></COMMENTS_LINE1>
<COMMENTS_LINE2></COMMENTS_LINE2>
<COMMENTS_LINE3></COMMENTS_LINE3>
<ADDRESS1></ADDRESS1>
<ADDRESS2></ADDRESS2>
<CITY></CITY>
<STATE>NY</STATE>
<ZIPCODE></ZIPCODE>
<ORGANIZATION_HOMEPAGE></ORGANIZATION_HOMEPAGE>
</RECORD>
<RECORD>
<REC_ID>1000537</REC_ID>
<FORCED_ORGANIZATION_NAME>Abundant Life Christian Center</FORCED_ORGANIZATION_NAME>
<ORGANIZATION_NAME1>Abundant Life Christian Center</ORGANIZATION_NAME1>
<ORGANIZATION_NAME2></ORGANIZATION_NAME2>
<ORGANIZATION_NAME3></ORGANIZATION_NAME3>
<ALT_ORGANIZATION_NAME></ALT_ORGANIZATION_NAME>
<FORCED_COUNTY_NAME></FORCED_COUNTY_NAME>
<COUNTY_NAME1></COUNTY_NAME1>
<COUNTY_NAME2></COUNTY_NAME2>
<ALT_COUNTY_NAME></ALT_COUNTY_NAME>
<FORCED_CATEGORY_NAME></FORCED_CATEGORY_NAME>
<CAT_CODE></CAT_CODE>
<CATEGORY_NAME1></CATEGORY_NAME1>
<CATEGORY_NAME2></CATEGORY_NAME2>
<FORCED_STATUS_NAME></FORCED_STATUS_NAME>
<STATUS_NAME1></STATUS_NAME1>
<STATUS_NAME2></STATUS_NAME2>
<STATUS_NAME3></STATUS_NAME3>
<ALT_STATUS_TEXT></ALT_STATUS_TEXT>
<STATUS_CODE></STATUS_CODE>
<STATUS2_NAME1></STATUS2_NAME1>
<STATUS2_NAME2></STATUS2_NAME2>
<STATUS2_NAME3></STATUS2_NAME3>
<STATUS_CODE2></STATUS_CODE2>
<EXPIRATION></EXPIRATION>
<UPDATED></UPDATED>
<COMMENTS_LINE1></COMMENTS_LINE1>
<COMMENTS_LINE2></COMMENTS_LINE2>
<COMMENTS_LINE3></COMMENTS_LINE3>
<ADDRESS1></ADDRESS1>
<ADDRESS2></ADDRESS2>
<CITY></CITY>
<STATE>NY</STATE>
<ZIPCODE></ZIPCODE>
<ORGANIZATION_HOMEPAGE></ORGANIZATION_HOMEPAGE>
</RECORD>
<RECORD>
<REC_ID>1001097</REC_ID>
<FORCED_ORGANIZATION_NAME>Active Physical Therapy Solutions</FORCED_ORGANIZATION_NAME>
<ORGANIZATION_NAME1>Active Physical Therapy Solutions</ORGANIZATION_NAME1>
<ORGANIZATION_NAME2></ORGANIZATION_NAME2>
<ORGANIZATION_NAME3></ORGANIZATION_NAME3>
<ALT_ORGANIZATION_NAME></ALT_ORGANIZATION_NAME>
<FORCED_COUNTY_NAME></FORCED_COUNTY_NAME>
<COUNTY_NAME1></COUNTY_NAME1>
<COUNTY_NAME2></COUNTY_NAME2>
<ALT_COUNTY_NAME></ALT_COUNTY_NAME>
<FORCED_CATEGORY_NAME></FORCED_CATEGORY_NAME>
<CAT_CODE></CAT_CODE>
<CATEGORY_NAME1></CATEGORY_NAME1>
<CATEGORY_NAME2></CATEGORY_NAME2>
<FORCED_STATUS_NAME></FORCED_STATUS_NAME>
<STATUS_NAME1></STATUS_NAME1>
<STATUS_NAME2></STATUS_NAME2>
<STATUS_NAME3></STATUS_NAME3>
<ALT_STATUS_TEXT></ALT_STATUS_TEXT>
<STATUS_CODE></STATUS_CODE>
<STATUS2_NAME1></STATUS2_NAME1>
<STATUS2_NAME2></STATUS2_NAME2>
<STATUS2_NAME3></STATUS2_NAME3>
<STATUS_CODE2></STATUS_CODE2>
<EXPIRATION></EXPIRATION>
<UPDATED></UPDATED>
<COMMENTS_LINE1></COMMENTS_LINE1>
<COMMENTS_LINE2></COMMENTS_LINE2>
<COMMENTS_LINE3></COMMENTS_LINE3>
<ADDRESS1></ADDRESS1>
<ADDRESS2></ADDRESS2>
<CITY></CITY>
<STATE>NY</STATE>
<ZIPCODE></ZIPCODE>
<ORGANIZATION_HOMEPAGE></ORGANIZATION_HOMEPAGE>
</RECORD>
<RECORD>
<REC_ID>1000925</REC_ID>
<FORCED_ORGANIZATION_NAME>Agogi Martial Arts</FORCED_ORGANIZATION_NAME>
<ORGANIZATION_NAME1>Agogi Martial Arts</ORGANIZATION_NAME1>
<ORGANIZATION_NAME2></ORGANIZATION_NAME2>
<ORGANIZATION_NAME3></ORGANIZATION_NAME3>
<ALT_ORGANIZATION_NAME></ALT_ORGANIZATION_NAME>
<FORCED_COUNTY_NAME></FORCED_COUNTY_NAME>
<COUNTY_NAME1></COUNTY_NAME1>
<COUNTY_NAME2></COUNTY_NAME2>
<ALT_COUNTY_NAME></ALT_COUNTY_NAME>
<FORCED_CATEGORY_NAME></FORCED_CATEGORY_NAME>
<CAT_CODE></CAT_CODE>
<CATEGORY_NAME1></CATEGORY_NAME1>
<CATEGORY_NAME2></CATEGORY_NAME2>
<FORCED_STATUS_NAME></FORCED_STATUS_NAME>
<STATUS_NAME1></STATUS_NAME1>
<STATUS_NAME2></STATUS_NAME2>
<STATUS_NAME3></STATUS_NAME3>
<ALT_STATUS_TEXT></ALT_STATUS_TEXT>
<STATUS_CODE></STATUS_CODE>
<STATUS2_NAME1></STATUS2_NAME1>
<STATUS2_NAME2></STATUS2_NAME2>
<STATUS2_NAME3></STATUS2_NAME3>
<STATUS_CODE2></STATUS_CODE2>
<EXPIRATION></EXPIRATION>
<UPDATED></UPDATED>
<COMMENTS_LINE1></COMMENTS_LINE1>
<COMMENTS_LINE2></COMMENTS_LINE2>
<COMMENTS_LINE3></COMMENTS_LINE3>
<ADDRESS1></ADDRESS1>
<ADDRESS2></ADDRESS2>
<CITY></CITY>
<STATE>NY</STATE>
<ZIPCODE></ZIPCODE>
<ORGANIZATION_HOMEPAGE></ORGANIZATION_HOMEPAGE>
</RECORD>
<RECORD>
<REC_ID>1000433</REC_ID>
<FORCED_ORGANIZATION_NAME>AmeriCU Credit Union</FORCED_ORGANIZATION_NAME>
<ORGANIZATION_NAME1>AmeriCU Credit Union</ORGANIZATION_NAME1>
<ORGANIZATION_NAME2></ORGANIZATION_NAME2>
<ORGANIZATION_NAME3></ORGANIZATION_NAME3>
<ALT_ORGANIZATION_NAME></ALT_ORGANIZATION_NAME>
<FORCED_COUNTY_NAME></FORCED_COUNTY_NAME>
<COUNTY_NAME1></COUNTY_NAME1>
<COUNTY_NAME2></COUNTY_NAME2>
<ALT_COUNTY_NAME></ALT_COUNTY_NAME>
<FORCED_CATEGORY_NAME></FORCED_CATEGORY_NAME>
<CAT_CODE></CAT_CODE>
<CATEGORY_NAME1></CATEGORY_NAME1>
<CATEGORY_NAME2></CATEGORY_NAME2>
<FORCED_STATUS_NAME></FORCED_STATUS_NAME>
<STATUS_NAME1></STATUS_NAME1>
<STATUS_NAME2></STATUS_NAME2>
<STATUS_NAME3></STATUS_NAME3>
<ALT_STATUS_TEXT></ALT_STATUS_TEXT>
<STATUS_CODE></STATUS_CODE>
<STATUS2_NAME1></STATUS2_NAME1>
<STATUS2_NAME2></STATUS2_NAME2>
<STATUS2_NAME3></STATUS2_NAME3>
<STATUS_CODE2></STATUS_CODE2>
<EXPIRATION></EXPIRATION>
<UPDATED></UPDATED>
<COMMENTS_LINE1></COMMENTS_LINE1>
<COMMENTS_LINE2></COMMENTS_LINE2>
<COMMENTS_LINE3></COMMENTS_LINE3>
<ADDRESS1></ADDRESS1>
<ADDRESS2></ADDRESS2>
<CITY></CITY>
<STATE>NY</STATE>
<ZIPCODE></ZIPCODE>
<ORGANIZATION_HOMEPAGE></ORGANIZATION_HOMEPAGE>
</RECORD>
<RECORD>
<REC_ID>1000829</REC_ID>
<FORCED_ORGANIZATION_NAME>Apple Valley UMC, Nedrow</FORCED_ORGANIZATION_NAME>
<ORGANIZATION_NAME1>Apple Valley UMC, Nedrow</ORGANIZATION_NAME1>
<ORGANIZATION_NAME2></ORGANIZATION_NAME2>
<ORGANIZATION_NAME3></ORGANIZATION_NAME3>
<ALT_ORGANIZATION_NAME></ALT_ORGANIZATION_NAME>
<FORCED_COUNTY_NAME></FORCED_COUNTY_NAME>
<COUNTY_NAME1></COUNTY_NAME1>
<COUNTY_NAME2></COUNTY_NAME2>
<ALT_COUNTY_NAME></ALT_COUNTY_NAME>
<FORCED_CATEGORY_NAME></FORCED_CATEGORY_NAME>
<CAT_CODE></CAT_CODE>
<CATEGORY_NAME1></CATEGORY_NAME1>
<CATEGORY_NAME2></CATEGORY_NAME2>
<FORCED_STATUS_NAME></FORCED_STATUS_NAME>
<STATUS_NAME1></STATUS_NAME1>
<STATUS_NAME2></STATUS_NAME2>
<STATUS_NAME3></STATUS_NAME3>
<ALT_STATUS_TEXT></ALT_STATUS_TEXT>
<STATUS_CODE></STATUS_CODE>
<STATUS2_NAME1></STATUS2_NAME1>
<STATUS2_NAME2></STATUS2_NAME2>
<STATUS2_NAME3></STATUS2_NAME3>
<STATUS_CODE2></STATUS_CODE2>
<EXPIRATION></EXPIRATION>
<UPDATED></UPDATED>
<COMMENTS_LINE1></COMMENTS_LINE1>
<COMMENTS_LINE2></COMMENTS_LINE2>
<COMMENTS_LINE3></COMMENTS_LINE3>
<ADDRESS1></ADDRESS1>
<ADDRESS2></ADDRESS2>
<CITY></CITY>
<STATE>NY</STATE>
<ZIPCODE></ZIPCODE>
<ORGANIZATION_HOMEPAGE></ORGANIZATION_HOMEPAGE>
</RECORD>
<RECORD>
<REC_ID>1001357</REC_ID>
<FORCED_ORGANIZATION_NAME>Artistic Designs Dance Company</FORCED_ORGANIZATION_NAME>
<ORGANIZATION_NAME1>Artistic Designs Dance Company</ORGANIZATION_NAME1>
<ORGANIZATION_NAME2></ORGANIZATION_NAME2>
<ORGANIZATION_NAME3></ORGANIZATION_NAME3>
<ALT_ORGANIZATION_NAME></ALT_ORGANIZATION_NAME>
<FORCED_COUNTY_NAME></FORCED_COUNTY_NAME>
<COUNTY_NAME1></COUNTY_NAME1>
<COUNTY_NAME2></COUNTY_NAME2>
<ALT_COUNTY_NAME></ALT_COUNTY_NAME>
<FORCED_CATEGORY_NAME></FORCED_CATEGORY_NAME>
<CAT_CODE></CAT_CODE>
<CATEGORY_NAME1></CATEGORY_NAME1>
<CATEGORY_NAME2></CATEGORY_NAME2>
<FORCED_STATUS_NAME></FORCED_STATUS_NAME>
<STATUS_NAME1></STATUS_NAME1>
<STATUS_NAME2></STATUS_NAME2>
<STATUS_NAME3></STATUS_NAME3>
<ALT_STATUS_TEXT></ALT_STATUS_TEXT>
<STATUS_CODE></STATUS_CODE>
<STATUS2_NAME1></STATUS2_NAME1>
<STATUS2_NAME2></STATUS2_NAME2>
<STATUS2_NAME3></STATUS2_NAME3>
<STATUS_CODE2></STATUS_CODE2>
<EXPIRATION></EXPIRATION>
<UPDATED></UPDATED>
<COMMENTS_LINE1></COMMENTS_LINE1>
<COMMENTS_LINE2></COMMENTS_LINE2>
<COMMENTS_LINE3></COMMENTS_LINE3>
<ADDRESS1></ADDRESS1>
<ADDRESS2></ADDRESS2>
<CITY></CITY>
<STATE>NY</STATE>
<ZIPCODE></ZIPCODE>
<ORGANIZATION_HOMEPAGE></ORGANIZATION_HOMEPAGE>
</RECORD>
<RECORD>
<REC_ID>1001161</REC_ID>
<FORCED_ORGANIZATION_NAME>Auburn YMCA-WEIU</FORCED_ORGANIZATION_NAME>
<ORGANIZATION_NAME1>Auburn YMCA-WEIU</ORGANIZATION_NAME1>
<ORGANIZATION_NAME2></ORGANIZATION_NAME2>
<ORGANIZATION_NAME3></ORGANIZATION_NAME3>
<ALT_ORGANIZATION_NAME></ALT_ORGANIZATION_NAME>
<FORCED_COUNTY_NAME></FORCED_COUNTY_NAME>
<COUNTY_NAME1></COUNTY_NAME1>
<COUNTY_NAME2></COUNTY_NAME2>
<ALT_COUNTY_NAME></ALT_COUNTY_NAME>
<FORCED_CATEGORY_NAME></FORCED_CATEGORY_NAME>
<CAT_CODE></CAT_CODE>
<CATEGORY_NAME1></CATEGORY_NAME1>
<CATEGORY_NAME2></CATEGORY_NAME2>
<FORCED_STATUS_NAME></FORCED_STATUS_NAME>
<STATUS_NAME1></STATUS_NAME1>
<STATUS_NAME2></STATUS_NAME2>
<STATUS_NAME3></STATUS_NAME3>
<ALT_STATUS_TEXT></ALT_STATUS_TEXT>
<STATUS_CODE></STATUS_CODE>
<STATUS2_NAME1></STATUS2_NAME1>
<STATUS2_NAME2></STATUS2_NAME2>
<STATUS2_NAME3></STATUS2_NAME3>
<STATUS_CODE2></STATUS_CODE2>
<EXPIRATION></EXPIRATION>
<UPDATED></UPDATED>
<COMMENTS_LINE1></COMMENTS_LINE1>
<COMMENTS_LINE2></COMMENTS_LINE2>
<COMMENTS_LINE3></COMMENTS_LINE3>
<ADDRESS1></ADDRESS1>
<ADDRESS2></ADDRESS2>
<CITY></CITY>
<STATE>NY</STATE>
<ZIPCODE></ZIPCODE>
<ORGANIZATION_HOMEPAGE></ORGANIZATION_HOMEPAGE>
</RECORD>
<RECORD>
<REC_ID>1001453</REC_ID>
<FORCED_ORGANIZATION_NAME>Baldwinsville Community Band</FORCED_ORGANIZATION_NAME>
<ORGANIZATION_NAME1>Baldwinsville Community Band</ORGANIZATION_NAME1>
<ORGANIZATION_NAME2></ORGANIZATION_NAME2>
<ORGANIZATION_NAME3></ORGANIZATION_NAME3>
<ALT_ORGANIZATION_NAME></ALT_ORGANIZATION_NAME>
<FORCED_COUNTY_NAME></FORCED_COUNTY_NAME>
<COUNTY_NAME1></COUNTY_NAME1>
<COUNTY_NAME2></COUNTY_NAME2>
<ALT_COUNTY_NAME></ALT_COUNTY_NAME>
<FORCED_CATEGORY_NAME></FORCED_CATEGORY_NAME>
<CAT_CODE></CAT_CODE>
<CATEGORY_NAME1></CATEGORY_NAME1>
<CATEGORY_NAME2></CATEGORY_NAME2>
<FORCED_STATUS_NAME></FORCED_STATUS_NAME>
<STATUS_NAME1></STATUS_NAME1>
<STATUS_NAME2></STATUS_NAME2>
<STATUS_NAME3></STATUS_NAME3>
<ALT_STATUS_TEXT></ALT_STATUS_TEXT>
<STATUS_CODE></STATUS_CODE>
<STATUS2_NAME1></STATUS2_NAME1>
<STATUS2_NAME2></STATUS2_NAME2>
<STATUS2_NAME3></STATUS2_NAME3>
<STATUS_CODE2></STATUS_CODE2>
<EXPIRATION></EXPIRATION>
<UPDATED></UPDATED>
<COMMENTS_LINE1></COMMENTS_LINE1>
<COMMENTS_LINE2></COMMENTS_LINE2>
<COMMENTS_LINE3></COMMENTS_LINE3>
<ADDRESS1></ADDRESS1>
<ADDRESS2></ADDRESS2>
<CITY></CITY>
<STATE>NY</STATE>
<ZIPCODE></ZIPCODE>
<ORGANIZATION_HOMEPAGE></ORGANIZATION_HOMEPAGE>
</RECORD>
<RECORD>
<REC_ID>1000597</REC_ID>
<FORCED_ORGANIZATION_NAME>Baldwinsville Public Library</FORCED_ORGANIZATION_NAME>
<ORGANIZATION_NAME1>Baldwinsville Public Library</ORGANIZATION_NAME1>
<ORGANIZATION_NAME2></ORGANIZATION_NAME2>
<ORGANIZATION_NAME3></ORGANIZATION_NAME3>
<ALT_ORGANIZATION_NAME></ALT_ORGANIZATION_NAME>
<FORCED_COUNTY_NAME></FORCED_COUNTY_NAME>
<COUNTY_NAME1></COUNTY_NAME1>
<COUNTY_NAME2></COUNTY_NAME2>
<ALT_COUNTY_NAME></ALT_COUNTY_NAME>
<FORCED_CATEGORY_NAME></FORCED_CATEGORY_NAME>
<CAT_CODE></CAT_CODE>
<CATEGORY_NAME1></CATEGORY_NAME1>
<CATEGORY_NAME2></CATEGORY_NAME2>
<FORCED_STATUS_NAME></FORCED_STATUS_NAME>
<STATUS_NAME1></STATUS_NAME1>
<STATUS_NAME2></STATUS_NAME2>
<STATUS_NAME3></STATUS_NAME3>
<ALT_STATUS_TEXT></ALT_STATUS_TEXT>
<STATUS_CODE></STATUS_CODE>
<STATUS2_NAME1></STATUS2_NAME1>
<STATUS2_NAME2></STATUS2_NAME2>
<STATUS2_NAME3></STATUS2_NAME3>
<STATUS_CODE2></STATUS_CODE2>
<EXPIRATION></EXPIRATION>
<UPDATED></UPDATED>
<COMMENTS_LINE1></COMMENTS_LINE1>
<COMMENTS_LINE2></COMMENTS_LINE2>
<COMMENTS_LINE3></COMMENTS_LINE3>
<ADDRESS1></ADDRESS1>
<ADDRESS2></ADDRESS2>
<CITY></CITY>
<STATE>NY</STATE>
<ZIPCODE></ZIPCODE>
<ORGANIZATION_HOMEPAGE></ORGANIZATION_HOMEPAGE>
</RECORD>
<RECORD>
<REC_ID>1000721</REC_ID>
<FORCED_ORGANIZATION_NAME>Ballet &amp; Dance Center, DeWitt</FORCED_ORGANIZATION_NAME>
<ORGANIZATION_NAME1>Ballet &amp; Dance Center, DeWitt</ORGANIZATION_NAME1>
<ORGANIZATION_NAME2></ORGANIZATION_NAME2>
<ORGANIZATION_NAME3></ORGANIZATION_NAME3>
<ALT_ORGANIZATION_NAME></ALT_ORGANIZATION_NAME>
<FORCED_COUNTY_NAME></FORCED_COUNTY_NAME>
<COUNTY_NAME1></COUNTY_NAME1>
<COUNTY_NAME2></COUNTY_NAME2>
<ALT_COUNTY_NAME></ALT_COUNTY_NAME>
<FORCED_CATEGORY_NAME></FORCED_CATEGORY_NAME>
<CAT_CODE></CAT_CODE>
<CATEGORY_NAME1></CATEGORY_NAME1>
<CATEGORY_NAME2></CATEGORY_NAME2>
<FORCED_STATUS_NAME></FORCED_STATUS_NAME>
<STATUS_NAME1></STATUS_NAME1>
<STATUS_NAME2></STATUS_NAME2>
<STATUS_NAME3></STATUS_NAME3>
<ALT_STATUS_TEXT></ALT_STATUS_TEXT>
<STATUS_CODE></STATUS_CODE>
<STATUS2_NAME1></STATUS2_NAME1>
<STATUS2_NAME2></STATUS2_NAME2>
<STATUS2_NAME3></STATUS2_NAME3>
<STATUS_CODE2></STATUS_CODE2>
<EXPIRATION></EXPIRATION>
<UPDATED></UPDATED>
<COMMENTS_LINE1></COMMENTS_LINE1>
<COMMENTS_LINE2></COMMENTS_LINE2>
<COMMENTS_LINE3></COMMENTS_LINE3>
<ADDRESS1>3470 Erie Blvd. East</ADDRESS1>
<ADDRESS2></ADDRESS2>
<CITY>DeWitt</CITY>
<STATE>NY</STATE>
<ZIPCODE></ZIPCODE>
<ORGANIZATION_HOMEPAGE></ORGANIZATION_HOMEPAGE>
</RECORD>
<RECORD>
<REC_ID>1001417</REC_ID>
<FORCED_ORGANIZATION_NAME>Bellevue Heights Nursery School</FORCED_ORGANIZATION_NAME>
<ORGANIZATION_NAME1>Bellevue Heights Nursery School</ORGANIZATION_NAME1>
<ORGANIZATION_NAME2></ORGANIZATION_NAME2>
<ORGANIZATION_NAME3></ORGANIZATION_NAME3>
<ALT_ORGANIZATION_NAME></ALT_ORGANIZATION_NAME>
<FORCED_COUNTY_NAME></FORCED_COUNTY_NAME>
<COUNTY_NAME1></COUNTY_NAME1>
<COUNTY_NAME2></COUNTY_NAME2>
<ALT_COUNTY_NAME></ALT_COUNTY_NAME>
<FORCED_CATEGORY_NAME></FORCED_CATEGORY_NAME>
<CAT_CODE></CAT_CODE>
<CATEGORY_NAME1></CATEGORY_NAME1>
<CATEGORY_NAME2></CATEGORY_NAME2>
<FORCED_STATUS_NAME></FORCED_STATUS_NAME>
<STATUS_NAME1></STATUS_NAME1>
<STATUS_NAME2></STATUS_NAME2>
<STATUS_NAME3></STATUS_NAME3>
<ALT_STATUS_TEXT></ALT_STATUS_TEXT>
<STATUS_CODE></STATUS_CODE>
<STATUS2_NAME1></STATUS2_NAME1>
<STATUS2_NAME2></STATUS2_NAME2>
<STATUS2_NAME3></STATUS2_NAME3>
<STATUS_CODE2></STATUS_CODE2>
<EXPIRATION></EXPIRATION>
<UPDATED></UPDATED>
<COMMENTS_LINE1></COMMENTS_LINE1>
<COMMENTS_LINE2></COMMENTS_LINE2>
<COMMENTS_LINE3></COMMENTS_LINE3>
<ADDRESS1></ADDRESS1>
<ADDRESS2></ADDRESS2>
<CITY></CITY>
<STATE>NY</STATE>
<ZIPCODE></ZIPCODE>
<ORGANIZATION_HOMEPAGE></ORGANIZATION_HOMEPAGE>
</RECORD>
<RECORD>
<REC_ID>1000989</REC_ID>
<FORCED_ORGANIZATION_NAME>Bellevue Heights UMC</FORCED_ORGANIZATION_NAME>
<ORGANIZATION_NAME1>Bellevue Heights UMC</ORGANIZATION_NAME1>
<ORGANIZATION_NAME2></ORGANIZATION_NAME2>
<ORGANIZATION_NAME3></ORGANIZATION_NAME3>
<ALT_ORGANIZATION_NAME></ALT_ORGANIZATION_NAME>
<FORCED_COUNTY_NAME></FORCED_COUNTY_NAME>
<COUNTY_NAME1></COUNTY_NAME1>
<COUNTY_NAME2></COUNTY_NAME2>
<ALT_COUNTY_NAME></ALT_COUNTY_NAME>
<FORCED_CATEGORY_NAME></FORCED_CATEGORY_NAME>
<CAT_CODE></CAT_CODE>
<CATEGORY_NAME1></CATEGORY_NAME1>
<CATEGORY_NAME2></CATEGORY_NAME2>
<FORCED_STATUS_NAME></FORCED_STATUS_NAME>
<STATUS_NAME1></STATUS_NAME1>
<STATUS_NAME2></STATUS_NAME2>
<STATUS_NAME3></STATUS_NAME3>
<ALT_STATUS_TEXT></ALT_STATUS_TEXT>
<STATUS_CODE></STATUS_CODE>
<STATUS2_NAME1></STATUS2_NAME1>
<STATUS2_NAME2></STATUS2_NAME2>
<STATUS2_NAME3></STATUS2_NAME3>
<STATUS_CODE2></STATUS_CODE2>
<EXPIRATION></EXPIRATION>
<UPDATED></UPDATED>
<COMMENTS_LINE1></COMMENTS_LINE1>
<COMMENTS_LINE2></COMMENTS_LINE2>
<COMMENTS_LINE3></COMMENTS_LINE3>
<ADDRESS1></ADDRESS1>
<ADDRESS2></ADDRESS2>
<CITY></CITY>
<STATE>NY</STATE>
<ZIPCODE></ZIPCODE>
<ORGANIZATION_HOMEPAGE></ORGANIZATION_HOMEPAGE>
</RECORD>
<RECORD>
<REC_ID>1001045</REC_ID>
<FORCED_ORGANIZATION_NAME>Berean Calvary Chapel</FORCED_ORGANIZATION_NAME>
<ORGANIZATION_NAME1>Berean Calvary Chapel</ORGANIZATION_NAME1>
<ORGANIZATION_NAME2></ORGANIZATION_NAME2>
<ORGANIZATION_NAME3></ORGANIZATION_NAME3>
<ALT_ORGANIZATION_NAME></ALT_ORGANIZATION_NAME>
<FORCED_COUNTY_NAME></FORCED_COUNTY_NAME>
<COUNTY_NAME1></COUNTY_NAME1>
<COUNTY_NAME2></COUNTY_NAME2>
<ALT_COUNTY_NAME></ALT_COUNTY_NAME>
<FORCED_CATEGORY_NAME></FORCED_CATEGORY_NAME>
<CAT_CODE></CAT_CODE>
<CATEGORY_NAME1></CATEGORY_NAME1>
<CATEGORY_NAME2></CATEGORY_NAME2>
<FORCED_STATUS_NAME></FORCED_STATUS_NAME>
<STATUS_NAME1></STATUS_NAME1>
<STATUS_NAME2></STATUS_NAME2>
<STATUS_NAME3></STATUS_NAME3>
<ALT_STATUS_TEXT></ALT_STATUS_TEXT>
<STATUS_CODE></STATUS_CODE>
<STATUS2_NAME1></STATUS2_NAME1>
<STATUS2_NAME2></STATUS2_NAME2>
<STATUS2_NAME3></STATUS2_NAME3>
<STATUS_CODE2></STATUS_CODE2>
<EXPIRATION></EXPIRATION>
<UPDATED></UPDATED>
<COMMENTS_LINE1></COMMENTS_LINE1>
<COMMENTS_LINE2></COMMENTS_LINE2>
<COMMENTS_LINE3></COMMENTS_LINE3>
<ADDRESS1></ADDRESS1>
<ADDRESS2></ADDRESS2>
<CITY></CITY>
<STATE>NY</STATE>
<ZIPCODE></ZIPCODE>
<ORGANIZATION_HOMEPAGE></ORGANIZATION_HOMEPAGE>
</RECORD>
<RECORD>
<REC_ID>1000441</REC_ID>
<FORCED_ORGANIZATION_NAME>Bet Havarim</FORCED_ORGANIZATION_NAME>
<ORGANIZATION_NAME1>Bet Havarim</ORGANIZATION_NAME1>
<ORGANIZATION_NAME2></ORGANIZATION_NAME2>
<ORGANIZATION_NAME3></ORGANIZATION_NAME3>
<ALT_ORGANIZATION_NAME></ALT_ORGANIZATION_NAME>
<FORCED_COUNTY_NAME></FORCED_COUNTY_NAME>
<COUNTY_NAME1></COUNTY_NAME1>
<COUNTY_NAME2></COUNTY_NAME2>
<ALT_COUNTY_NAME></ALT_COUNTY_NAME>
<FORCED_CATEGORY_NAME></FORCED_CATEGORY_NAME>
<CAT_CODE></CAT_CODE>
<CATEGORY_NAME1></CATEGORY_NAME1>
<CATEGORY_NAME2></CATEGORY_NAME2>
<FORCED_STATUS_NAME></FORCED_STATUS_NAME>
<STATUS_NAME1></STATUS_NAME1>
<STATUS_NAME2></STATUS_NAME2>
<STATUS_NAME3></STATUS_NAME3>
<ALT_STATUS_TEXT></ALT_STATUS_TEXT>
<STATUS_CODE></STATUS_CODE>
<STATUS2_NAME1></STATUS2_NAME1>
<STATUS2_NAME2></STATUS2_NAME2>
<STATUS2_NAME3></STATUS2_NAME3>
<STATUS_CODE2></STATUS_CODE2>
<EXPIRATION></EXPIRATION>
<UPDATED></UPDATED>
<COMMENTS_LINE1></COMMENTS_LINE1>
<COMMENTS_LINE2></COMMENTS_LINE2>
<COMMENTS_LINE3></COMMENTS_LINE3>
<ADDRESS1></ADDRESS1>
<ADDRESS2></ADDRESS2>
<CITY></CITY>
<STATE>NY</STATE>
<ZIPCODE></ZIPCODE>
<ORGANIZATION_HOMEPAGE></ORGANIZATION_HOMEPAGE>
</RECORD>
<RECORD>
<REC_ID>1001133</REC_ID>
<FORCED_ORGANIZATION_NAME>Birnie Bus Service</FORCED_ORGANIZATION_NAME>
<ORGANIZATION_NAME1>Birnie Bus Service</ORGANIZATION_NAME1>
<ORGANIZATION_NAME2></ORGANIZATION_NAME2>
<ORGANIZATION_NAME3></ORGANIZATION_NAME3>
<ALT_ORGANIZATION_NAME></ALT_ORGANIZATION_NAME>
<FORCED_COUNTY_NAME></FORCED_COUNTY_NAME>
<COUNTY_NAME1></COUNTY_NAME1>
<COUNTY_NAME2></COUNTY_NAME2>
<ALT_COUNTY_NAME></ALT_COUNTY_NAME>
<FORCED_CATEGORY_NAME></FORCED_CATEGORY_NAME>
<CAT_CODE></CAT_CODE>
<CATEGORY_NAME1></CATEGORY_NAME1>
<CATEGORY_NAME2></CATEGORY_NAME2>
<FORCED_STATUS_NAME></FORCED_STATUS_NAME>
<STATUS_NAME1></STATUS_NAME1>
<STATUS_NAME2></STATUS_NAME2>
<STATUS_NAME3></STATUS_NAME3>
<ALT_STATUS_TEXT></ALT_STATUS_TEXT>
<STATUS_CODE></STATUS_CODE>
<STATUS2_NAME1></STATUS2_NAME1>
<STATUS2_NAME2></STATUS2_NAME2>
<STATUS2_NAME3></STATUS2_NAME3>
<STATUS_CODE2></STATUS_CODE2>
<EXPIRATION></EXPIRATION>
<UPDATED></UPDATED>
<COMMENTS_LINE1></COMMENTS_LINE1>
<COMMENTS_LINE2></COMMENTS_LINE2>
<COMMENTS_LINE3></COMMENTS_LINE3>
<ADDRESS1></ADDRESS1>
<ADDRESS2></ADDRESS2>
<CITY></CITY>
<STATE>NY</STATE>
<ZIPCODE></ZIPCODE>
<ORGANIZATION_HOMEPAGE></ORGANIZATION_HOMEPAGE>
</RECORD>
<RECORD>
<REC_ID>1001289</REC_ID>
<FORCED_ORGANIZATION_NAME>Blaze Gymnastics</FORCED_ORGANIZATION_NAME>
<ORGANIZATION_NAME1>Blaze Gymnastics</ORGANIZATION_NAME1>
<ORGANIZATION_NAME2></ORGANIZATION_NAME2>
<ORGANIZATION_NAME3></ORGANIZATION_NAME3>
<ALT_ORGANIZATION_NAME></ALT_ORGANIZATION_NAME>
<FORCED_COUNTY_NAME></FORCED_COUNTY_NAME>
<COUNTY_NAME1></COUNTY_NAME1>
<COUNTY_NAME2></COUNTY_NAME2>
<ALT_COUNTY_NAME></ALT_COUNTY_NAME>
<FORCED_CATEGORY_NAME></FORCED_CATEGORY_NAME>
<CAT_CODE></CAT_CODE>
<CATEGORY_NAME1></CATEGORY_NAME1>
<CATEGORY_NAME2></CATEGORY_NAME2>
<FORCED_STATUS_NAME></FORCED_STATUS_NAME>
<STATUS_NAME1></STATUS_NAME1>
<STATUS_NAME2></STATUS_NAME2>
<STATUS_NAME3></STATUS_NAME3>
<ALT_STATUS_TEXT></ALT_STATUS_TEXT>
<STATUS_CODE></STATUS_CODE>
<STATUS2_NAME1></STATUS2_NAME1>
<STATUS2_NAME2></STATUS2_NAME2>
<STATUS2_NAME3></STATUS2_NAME3>
<STATUS_CODE2></STATUS_CODE2>
<EXPIRATION></EXPIRATION>
<UPDATED></UPDATED>
<COMMENTS_LINE1></COMMENTS_LINE1>
<COMMENTS_LINE2></COMMENTS_LINE2>
<COMMENTS_LINE3></COMMENTS_LINE3>
<ADDRESS1></ADDRESS1>
<ADDRESS2></ADDRESS2>
<CITY></CITY>
<STATE>NY</STATE>
<ZIPCODE></ZIPCODE>
<ORGANIZATION_HOMEPAGE></ORGANIZATION_HOMEPAGE>
</RECORD>
<RECORD>
<REC_ID>1001085</REC_ID>
<FORCED_ORGANIZATION_NAME>Bluebird Music Together</FORCED_ORGANIZATION_NAME>
<ORGANIZATION_NAME1>Bluebird Music Together</ORGANIZATION_NAME1>
<ORGANIZATION_NAME2></ORGANIZATION_NAME2>
<ORGANIZATION_NAME3></ORGANIZATION_NAME3>
<ALT_ORGANIZATION_NAME></ALT_ORGANIZATION_NAME>
<FORCED_COUNTY_NAME></FORCED_COUNTY_NAME>
<COUNTY_NAME1></COUNTY_NAME1>
<COUNTY_NAME2></COUNTY_NAME2>
<ALT_COUNTY_NAME></ALT_COUNTY_NAME>
<FORCED_CATEGORY_NAME></FORCED_CATEGORY_NAME>
<CAT_CODE></CAT_CODE>
<CATEGORY_NAME1></CATEGORY_NAME1>
<CATEGORY_NAME2></CATEGORY_NAME2>
<FORCED_STATUS_NAME></FORCED_STATUS_NAME>
<STATUS_NAME1></STATUS_NAME1>
<STATUS_NAME2></STATUS_NAME2>
<STATUS_NAME3></STATUS_NAME3>
<ALT_STATUS_TEXT></ALT_STATUS_TEXT>
<STATUS_CODE></STATUS_CODE>
<STATUS2_NAME1></STATUS2_NAME1>
<STATUS2_NAME2></STATUS2_NAME2>
<STATUS2_NAME3></STATUS2_NAME3>
<STATUS_CODE2></STATUS_CODE2>
<EXPIRATION></EXPIRATION>
<UPDATED></UPDATED>
<COMMENTS_LINE1></COMMENTS_LINE1>
<COMMENTS_LINE2></COMMENTS_LINE2>
<COMMENTS_LINE3></COMMENTS_LINE3>
<ADDRESS1></ADDRESS1>
<ADDRESS2></ADDRESS2>
<CITY></CITY>
<STATE>NY</STATE>
<ZIPCODE></ZIPCODE>
<ORGANIZATION_HOMEPAGE></ORGANIZATION_HOMEPAGE>
</RECORD>
<RECORD>
<REC_ID>1000845</REC_ID>
<FORCED_ORGANIZATION_NAME>Bounce, Fun and More</FORCED_ORGANIZATION_NAME>
<ORGANIZATION_NAME1>Bounce, Fun and More</ORGANIZATION_NAME1>
<ORGANIZATION_NAME2></ORGANIZATION_NAME2>
<ORGANIZATION_NAME3></ORGANIZATION_NAME3>
<ALT_ORGANIZATION_NAME></ALT_ORGANIZATION_NAME>
<FORCED_COUNTY_NAME></FORCED_COUNTY_NAME>
<COUNTY_NAME1></COUNTY_NAME1>
<COUNTY_NAME2></COUNTY_NAME2>
<ALT_COUNTY_NAME></ALT_COUNTY_NAME>
<FORCED_CATEGORY_NAME></FORCED_CATEGORY_NAME>
<CAT_CODE></CAT_CODE>
<CATEGORY_NAME1></CATEGORY_NAME1>
<CATEGORY_NAME2></CATEGORY_NAME2>
<FORCED_STATUS_NAME></FORCED_STATUS_NAME>
<STATUS_NAME1></STATUS_NAME1>
<STATUS_NAME2></STATUS_NAME2>
<STATUS_NAME3></STATUS_NAME3>
<ALT_STATUS_TEXT></ALT_STATUS_TEXT>
<STATUS_CODE></STATUS_CODE>
<STATUS2_NAME1></STATUS2_NAME1>
<STATUS2_NAME2></STATUS2_NAME2>