<?xml version="1.0" standalone="no" ?>
<!DOCTYPE DATA [
  <!ELEMENT DATA                     (SOURCE,EXPORT_TYPE,NUM_CLOSINGS,RUN_DATE,RUN_EPOCH,RECORD*)>
  <!ELEMENT SOURCE                   (CDATA)>
  <!ELEMENT EXPORT_TYPE              (CDATA)>
  <!ELEMENT NUM_CLOSINGS             (CDATA)>
  <!ELEMENT RUN_DATE                 (CDATA)>
  <!ELEMENT RUN_EPOCH                (CDATA)>
  <!ELEMENT RECORD                   (REC_ID,FORCED_ORGANIZATION_NAME,ORGANIZATION_NAME1,ORGANIZATION_NAME2,ORGANIZATION_NAME3,ALT_ORGANIZATION_NAME,FORCED_COUNTY_NAME,COUNTY_NAME1,COUNTY_NAME2,ALT_COUNTY_NAME,CAT_CODE,CATEGORY_NAME1,CATEGORY_NAME2,COMPLETE_STATUS,FORCED_STATUS_NAME,STATUS_NAME1,STATUS_NAME2,STATUS_NAME3,ALT_STATUS_TEXT,STATUS_CODE,STATUS2_NAME1,STATUS2_NAME2,STATUS2_NAME3,STATUS_CODE2,EXPIRATION,UPDATED,COMMENTS_LINE1,COMMENTS_LINE2,COMMENTS_LINE3,ADDRESS1,ADDRESS2,CITY,STATE,ZIPCODE,ORGANIZATION_HOMEPAGE)>
  <!ELEMENT REC_ID                   (ID)>
  <!ELEMENT FORCED_ORGANIZATION_NAME (CDATA)>
  <!ELEMENT ORGANIZATION_NAME1       (CDATA)>
  <!ELEMENT ORGANIZATION_NAME2       (CDATA)>
  <!ELEMENT ORGANIZATION_NAME3       (CDATA)>
  <!ELEMENT ALT_ORGANIZATION_NAME    (CDATA)>
  <!ELEMENT FORCED_COUNTY_NAME       (CDATA)>
  <!ELEMENT COUNTY_NAME1             (CDATA)>
  <!ELEMENT COUNTY_NAME2             (CDATA)>
  <!ELEMENT ALT_COUNTY_NAME          (CDATA)>
  <!ELEMENT CAT_CODE                 (CDATA)>
  <!ELEMENT CATEGORY_NAME1           (CDATA)>
  <!ELEMENT CATEGORY_NAME2           (CDATA)>
  <!ELEMENT COMPLETE_STATUS          (CDATA)>
  <!ELEMENT FORCED_STATUS_NAME       (CDATA)>
  <!ELEMENT STATUS_NAME1             (CDATA)>
  <!ELEMENT STATUS_NAME2             (CDATA)>
  <!ELEMENT STATUS_NAME3             (CDATA)>
  <!ELEMENT ALT_STATUS_TEXT          (CDATA)>
  <!ELEMENT STATUS_CODE              (CDATA)>
  <!ELEMENT STATUS2_NAME1            (CDATA)>
  <!ELEMENT STATUS2_NAME2            (CDATA)>
  <!ELEMENT STATUS2_NAME3            (CDATA)>
  <!ELEMENT STATUS_CODE2             (CDATA)>
  <!ELEMENT EXPIRATION               (CDATA)>
  <!ELEMENT UPDATED                  (CDATA)>
  <!ELEMENT COMMENTS_LINE1           (CDATA)>
  <!ELEMENT COMMENTS_LINE2           (CDATA)>
  <!ELEMENT COMMENTS_LINE3           (CDATA)>
  <!ELEMENT ADDRESS1                 (CDATA)>
  <!ELEMENT ADDRESS2                 (CDATA)>
  <!ELEMENT CITY                     (CDATA)>
  <!ELEMENT STATE                    (CDATA)>
  <!ELEMENT ZIPCODE                  (CDATA)>
  <!ELEMENT ORGANIZATION_HOMEPAGE    (CDATA)>
]>
<DATA>
<SOURCE>NewsTicker</SOURCE>
<EXPORT_TYPE>L2</EXPORT_TYPE>
<NUM_CLOSINGS>531</NUM_CLOSINGS>
<RUN_DATE>Mon Oct 19 03:03:02 EDT 2015</RUN_DATE>
<RUN_EPOCH>1445238182</RUN_EPOCH>
<RECORD>
<REC_ID>2980</REC_ID>
<FORCED_ORGANIZATION_NAME>A Bright Future Learning Center</FORCED_ORGANIZATION_NAME>
<ORGANIZATION_NAME1>A Bright Future Learning Center</ORGANIZATION_NAME1>
<ORGANIZATION_NAME2></ORGANIZATION_NAME2>
<ORGANIZATION_NAME3></ORGANIZATION_NAME3>
<ALT_ORGANIZATION_NAME></ALT_ORGANIZATION_NAME>
<FORCED_COUNTY_NAME>Lackawanna</FORCED_COUNTY_NAME>
<COUNTY_NAME1>Lackawanna</COUNTY_NAME1>
<COUNTY_NAME2></COUNTY_NAME2>
<ALT_COUNTY_NAME></ALT_COUNTY_NAME>
<FORCED_CATEGORY_NAME>Daycare/Preschool</FORCED_CATEGORY_NAME>
<CAT_CODE>3</CAT_CODE>
<CATEGORY_NAME1>Daycare/Preschool</CATEGORY_NAME1>
<CATEGORY_NAME2></CATEGORY_NAME2>
<COMPLETE_STATUS></COMPLETE_STATUS>
<FORCED_STATUS_NAME></FORCED_STATUS_NAME>
<STATUS_NAME1></STATUS_NAME1>
<STATUS_NAME2></STATUS_NAME2>
<STATUS_NAME3></STATUS_NAME3>
<ALT_STATUS_TEXT></ALT_STATUS_TEXT>
<STATUS_CODE></STATUS_CODE>
<STATUS2_NAME1></STATUS2_NAME1>
<STATUS2_NAME2></STATUS2_NAME2>
<STATUS2_NAME3></STATUS2_NAME3>
<STATUS_CODE2></STATUS_CODE2>
<EXPIRATION></EXPIRATION>
<UPDATED></UPDATED>
<COMMENTS_LINE1></COMMENTS_LINE1>
<COMMENTS_LINE2></COMMENTS_LINE2>
<COMMENTS_LINE3></COMMENTS_LINE3>
<ADDRESS1>3821 Birney Avenue</ADDRESS1>
<ADDRESS2></ADDRESS2>
<CITY>Moosic</CITY>
<STATE>PA</STATE>
<ZIPCODE>18507</ZIPCODE>
<ORGANIZATION_HOMEPAGE></ORGANIZATION_HOMEPAGE>
</RECORD>
<RECORD>
<REC_ID>3376</REC_ID>
<FORCED_ORGANIZATION_NAME>A Step Ahead, LLC</FORCED_ORGANIZATION_NAME>
<ORGANIZATION_NAME1>A Step Ahead, LLC</ORGANIZATION_NAME1>
<ORGANIZATION_NAME2></ORGANIZATION_NAME2>
<ORGANIZATION_NAME3></ORGANIZATION_NAME3>
<ALT_ORGANIZATION_NAME></ALT_ORGANIZATION_NAME>
<FORCED_COUNTY_NAME>Luzerne</FORCED_COUNTY_NAME>
<COUNTY_NAME1>Luzerne</COUNTY_NAME1>
<COUNTY_NAME2></COUNTY_NAME2>
<ALT_COUNTY_NAME></ALT_COUNTY_NAME>
<FORCED_CATEGORY_NAME>Daycare/Preschool</FORCED_CATEGORY_NAME>
<CAT_CODE>3</CAT_CODE>
<CATEGORY_NAME1>Daycare/Preschool</CATEGORY_NAME1>
<CATEGORY_NAME2></CATEGORY_NAME2>
<COMPLETE_STATUS></COMPLETE_STATUS>
<FORCED_STATUS_NAME></FORCED_STATUS_NAME>
<STATUS_NAME1></STATUS_NAME1>
<STATUS_NAME2></STATUS_NAME2>
<STATUS_NAME3></STATUS_NAME3>
<ALT_STATUS_TEXT></ALT_STATUS_TEXT>
<STATUS_CODE></STATUS_CODE>
<STATUS2_NAME1></STATUS2_NAME1>
<STATUS2_NAME2></STATUS2_NAME2>
<STATUS2_NAME3></STATUS2_NAME3>
<STATUS_CODE2></STATUS_CODE2>
<EXPIRATION></EXPIRATION>
<UPDATED></UPDATED>
<COMMENTS_LINE1></COMMENTS_LINE1>
<COMMENTS_LINE2></COMMENTS_LINE2>
<COMMENTS_LINE3></COMMENTS_LINE3>
<ADDRESS1>768 Route 183 South</ADDRESS1>
<ADDRESS2></ADDRESS2>
<CITY>Schuylkill Haven</CITY>
<STATE>PA</STATE>
<ZIPCODE>17972</ZIPCODE>
<ORGANIZATION_HOMEPAGE></ORGANIZATION_HOMEPAGE>
</RECORD>
<RECORD>
<REC_ID>3660</REC_ID>
<FORCED_ORGANIZATION_NAME>A to Z Learning Daycare</FORCED_ORGANIZATION_NAME>
<ORGANIZATION_NAME1>A to Z Learning Daycare</ORGANIZATION_NAME1>
<ORGANIZATION_NAME2></ORGANIZATION_NAME2>
<ORGANIZATION_NAME3></ORGANIZATION_NAME3>
<ALT_ORGANIZATION_NAME></ALT_ORGANIZATION_NAME>
<FORCED_COUNTY_NAME>Monroe</FORCED_COUNTY_NAME>
<COUNTY_NAME1>Monroe</COUNTY_NAME1>
<COUNTY_NAME2></COUNTY_NAME2>
<ALT_COUNTY_NAME></ALT_COUNTY_NAME>
<FORCED_CATEGORY_NAME>Daycare/Preschool</FORCED_CATEGORY_NAME>
<CAT_CODE>3</CAT_CODE>
<CATEGORY_NAME1>Daycare/Preschool</CATEGORY_NAME1>
<CATEGORY_NAME2></CATEGORY_NAME2>
<COMPLETE_STATUS></COMPLETE_STATUS>
<FORCED_STATUS_NAME></FORCED_STATUS_NAME>
<STATUS_NAME1></STATUS_NAME1>
<STATUS_NAME2></STATUS_NAME2>
<STATUS_NAME3></STATUS_NAME3>
<ALT_STATUS_TEXT></ALT_STATUS_TEXT>
<STATUS_CODE></STATUS_CODE>
<STATUS2_NAME1></STATUS2_NAME1>
<STATUS2_NAME2></STATUS2_NAME2>
<STATUS2_NAME3></STATUS2_NAME3>
<STATUS_CODE2></STATUS_CODE2>
<EXPIRATION></EXPIRATION>
<UPDATED></UPDATED>
<COMMENTS_LINE1></COMMENTS_LINE1>
<COMMENTS_LINE2></COMMENTS_LINE2>
<COMMENTS_LINE3></COMMENTS_LINE3>
<ADDRESS1>613 Pocono Blvd</ADDRESS1>
<ADDRESS2></ADDRESS2>
<CITY>Mount Pocono</CITY>
<STATE>PA</STATE>
<ZIPCODE>18344</ZIPCODE>
<ORGANIZATION_HOMEPAGE></ORGANIZATION_HOMEPAGE>
</RECORD>
<RECORD>
<REC_ID>2844</REC_ID>
<FORCED_ORGANIZATION_NAME>ABC Daycare-Preschool</FORCED_ORGANIZATION_NAME>
<ORGANIZATION_NAME1>ABC Daycare-Preschool</ORGANIZATION_NAME1>
<ORGANIZATION_NAME2></ORGANIZATION_NAME2>
<ORGANIZATION_NAME3></ORGANIZATION_NAME3>
<ALT_ORGANIZATION_NAME></ALT_ORGANIZATION_NAME>
<FORCED_COUNTY_NAME>Monroe</FORCED_COUNTY_NAME>
<COUNTY_NAME1>Monroe</COUNTY_NAME1>
<COUNTY_NAME2></COUNTY_NAME2>
<ALT_COUNTY_NAME></ALT_COUNTY_NAME>
<FORCED_CATEGORY_NAME>Daycare/Preschool</FORCED_CATEGORY_NAME>
<CAT_CODE>3</CAT_CODE>
<CATEGORY_NAME1>Daycare/Preschool</CATEGORY_NAME1>
<CATEGORY_NAME2></CATEGORY_NAME2>
<COMPLETE_STATUS></COMPLETE_STATUS>
<FORCED_STATUS_NAME></FORCED_STATUS_NAME>
<STATUS_NAME1></STATUS_NAME1>
<STATUS_NAME2></STATUS_NAME2>
<STATUS_NAME3></STATUS_NAME3>
<ALT_STATUS_TEXT></ALT_STATUS_TEXT>
<STATUS_CODE></STATUS_CODE>
<STATUS2_NAME1></STATUS2_NAME1>
<STATUS2_NAME2></STATUS2_NAME2>
<STATUS2_NAME3></STATUS2_NAME3>
<STATUS_CODE2></STATUS_CODE2>
<EXPIRATION></EXPIRATION>
<UPDATED></UPDATED>
<COMMENTS_LINE1></COMMENTS_LINE1>
<COMMENTS_LINE2></COMMENTS_LINE2>
<COMMENTS_LINE3></COMMENTS_LINE3>
<ADDRESS1>PO Box 791</ADDRESS1>
<ADDRESS2></ADDRESS2>
<CITY>Brodheadsville</CITY>
<STATE>PA</STATE>
<ZIPCODE>18322</ZIPCODE>
<ORGANIZATION_HOMEPAGE></ORGANIZATION_HOMEPAGE>
</RECORD>
<RECORD>
<REC_ID>1008</REC_ID>
<FORCED_ORGANIZATION_NAME>ABC Kiddie Kampus</FORCED_ORGANIZATION_NAME>
<ORGANIZATION_NAME1>ABC Kiddie Kampus</ORGANIZATION_NAME1>
<ORGANIZATION_NAME2></ORGANIZATION_NAME2>
<ORGANIZATION_NAME3></ORGANIZATION_NAME3>
<ALT_ORGANIZATION_NAME></ALT_ORGANIZATION_NAME>
<FORCED_COUNTY_NAME>Lackawanna</FORCED_COUNTY_NAME>
<COUNTY_NAME1>Lackawanna</COUNTY_NAME1>
<COUNTY_NAME2></COUNTY_NAME2>
<ALT_COUNTY_NAME></ALT_COUNTY_NAME>
<FORCED_CATEGORY_NAME>Daycare/Preschool</FORCED_CATEGORY_NAME>
<CAT_CODE>3</CAT_CODE>
<CATEGORY_NAME1>Daycare/Preschool</CATEGORY_NAME1>
<CATEGORY_NAME2></CATEGORY_NAME2>
<COMPLETE_STATUS></COMPLETE_STATUS>
<FORCED_STATUS_NAME></FORCED_STATUS_NAME>
<STATUS_NAME1></STATUS_NAME1>
<STATUS_NAME2></STATUS_NAME2>
<STATUS_NAME3></STATUS_NAME3>
<ALT_STATUS_TEXT></ALT_STATUS_TEXT>
<STATUS_CODE></STATUS_CODE>
<STATUS2_NAME1></STATUS2_NAME1>
<STATUS2_NAME2></STATUS2_NAME2>
<STATUS2_NAME3></STATUS2_NAME3>
<STATUS_CODE2></STATUS_CODE2>
<EXPIRATION></EXPIRATION>
<UPDATED></UPDATED>
<COMMENTS_LINE1></COMMENTS_LINE1>
<COMMENTS_LINE2></COMMENTS_LINE2>
<COMMENTS_LINE3></COMMENTS_LINE3>
<ADDRESS1>701 S Main Street</ADDRESS1>
<ADDRESS2></ADDRESS2>
<CITY>Old Forge</CITY>
<STATE>PA</STATE>
<ZIPCODE>18518</ZIPCODE>
<ORGANIZATION_HOMEPAGE></ORGANIZATION_HOMEPAGE>
</RECORD>
<RECORD>
<REC_ID>3764</REC_ID>
<FORCED_ORGANIZATION_NAME>ABC Learning Tree</FORCED_ORGANIZATION_NAME>
<ORGANIZATION_NAME1>ABC Learning Tree</ORGANIZATION_NAME1>
<ORGANIZATION_NAME2></ORGANIZATION_NAME2>
<ORGANIZATION_NAME3></ORGANIZATION_NAME3>
<ALT_ORGANIZATION_NAME></ALT_ORGANIZATION_NAME>
<FORCED_COUNTY_NAME>Luzerne</FORCED_COUNTY_NAME>
<COUNTY_NAME1>Luzerne</COUNTY_NAME1>
<COUNTY_NAME2></COUNTY_NAME2>
<ALT_COUNTY_NAME></ALT_COUNTY_NAME>
<FORCED_CATEGORY_NAME>Daycare/Preschool</FORCED_CATEGORY_NAME>
<CAT_CODE>3</CAT_CODE>
<CATEGORY_NAME1>Daycare/Preschool</CATEGORY_NAME1>
<CATEGORY_NAME2></CATEGORY_NAME2>
<COMPLETE_STATUS></COMPLETE_STATUS>
<FORCED_STATUS_NAME></FORCED_STATUS_NAME>
<STATUS_NAME1></STATUS_NAME1>
<STATUS_NAME2></STATUS_NAME2>
<STATUS_NAME3></STATUS_NAME3>
<ALT_STATUS_TEXT></ALT_STATUS_TEXT>
<STATUS_CODE></STATUS_CODE>
<STATUS2_NAME1></STATUS2_NAME1>
<STATUS2_NAME2></STATUS2_NAME2>
<STATUS2_NAME3></STATUS2_NAME3>
<STATUS_CODE2></STATUS_CODE2>
<EXPIRATION></EXPIRATION>
<UPDATED></UPDATED>
<COMMENTS_LINE1></COMMENTS_LINE1>
<COMMENTS_LINE2></COMMENTS_LINE2>
<COMMENTS_LINE3></COMMENTS_LINE3>
<ADDRESS1>171 North Main Street</ADDRESS1>
<ADDRESS2></ADDRESS2>
<CITY>Pittston</CITY>
<STATE>PA</STATE>
<ZIPCODE>18640</ZIPCODE>
<ORGANIZATION_HOMEPAGE></ORGANIZATION_HOMEPAGE>
</RECORD>
<RECORD>
<REC_ID>2388</REC_ID>
<FORCED_ORGANIZATION_NAME>Abington Christian Academy</FORCED_ORGANIZATION_NAME>
<ORGANIZATION_NAME1>Abington Christian Academy</ORGANIZATION_NAME1>
<ORGANIZATION_NAME2></ORGANIZATION_NAME2>
<ORGANIZATION_NAME3></ORGANIZATION_NAME3>
<ALT_ORGANIZATION_NAME></ALT_ORGANIZATION_NAME>
<FORCED_COUNTY_NAME>Lackawanna</FORCED_COUNTY_NAME>
<COUNTY_NAME1>Lackawanna</COUNTY_NAME1>
<COUNTY_NAME2></COUNTY_NAME2>
<ALT_COUNTY_NAME></ALT_COUNTY_NAME>
<FORCED_CATEGORY_NAME>Catholic Schools/Tech Schools</FORCED_CATEGORY_NAME>
<CAT_CODE>2</CAT_CODE>
<CATEGORY_NAME1>Catholic Schools/Tech Schools</CATEGORY_NAME1>
<CATEGORY_NAME2></CATEGORY_NAME2>
<COMPLETE_STATUS></COMPLETE_STATUS>
<FORCED_STATUS_NAME></FORCED_STATUS_NAME>
<STATUS_NAME1></STATUS_NAME1>
<STATUS_NAME2></STATUS_NAME2>
<STATUS_NAME3></STATUS_NAME3>
<ALT_STATUS_TEXT></ALT_STATUS_TEXT>
<STATUS_CODE></STATUS_CODE>
<STATUS2_NAME1></STATUS2_NAME1>
<STATUS2_NAME2></STATUS2_NAME2>
<STATUS2_NAME3></STATUS2_NAME3>
<STATUS_CODE2></STATUS_CODE2>
<EXPIRATION></EXPIRATION>
<UPDATED></UPDATED>
<COMMENTS_LINE1></COMMENTS_LINE1>
<COMMENTS_LINE2></COMMENTS_LINE2>
<COMMENTS_LINE3></COMMENTS_LINE3>
<ADDRESS1>204 S Abington Road</ADDRESS1>
<ADDRESS2></ADDRESS2>
<CITY>Clarks Green</CITY>
<STATE>PA</STATE>
<ZIPCODE>18411</ZIPCODE>
<ORGANIZATION_HOMEPAGE></ORGANIZATION_HOMEPAGE>
</RECORD>
<RECORD>
<REC_ID>3828</REC_ID>
<FORCED_ORGANIZATION_NAME>Abington Heights Civic League Dance Academy</FORCED_ORGANIZATION_NAME>
<ORGANIZATION_NAME1>Abington Heights Civic League Dance Academy</ORGANIZATION_NAME1>
<ORGANIZATION_NAME2></ORGANIZATION_NAME2>
<ORGANIZATION_NAME3></ORGANIZATION_NAME3>
<ALT_ORGANIZATION_NAME></ALT_ORGANIZATION_NAME>
<FORCED_COUNTY_NAME>Lackawanna</FORCED_COUNTY_NAME>
<COUNTY_NAME1>Lackawanna</COUNTY_NAME1>
<COUNTY_NAME2></COUNTY_NAME2>
<ALT_COUNTY_NAME></ALT_COUNTY_NAME>
<FORCED_CATEGORY_NAME>Business</FORCED_CATEGORY_NAME>
<CAT_CODE>4</CAT_CODE>
<CATEGORY_NAME1>Business</CATEGORY_NAME1>
<CATEGORY_NAME2></CATEGORY_NAME2>
<COMPLETE_STATUS></COMPLETE_STATUS>
<FORCED_STATUS_NAME></FORCED_STATUS_NAME>
<STATUS_NAME1></STATUS_NAME1>
<STATUS_NAME2></STATUS_NAME2>
<STATUS_NAME3></STATUS_NAME3>
<ALT_STATUS_TEXT></ALT_STATUS_TEXT>
<STATUS_CODE></STATUS_CODE>
<STATUS2_NAME1></STATUS2_NAME1>
<STATUS2_NAME2></STATUS2_NAME2>
<STATUS2_NAME3></STATUS2_NAME3>
<STATUS_CODE2></STATUS_CODE2>
<EXPIRATION></EXPIRATION>
<UPDATED></UPDATED>
<COMMENTS_LINE1></COMMENTS_LINE1>
<COMMENTS_LINE2></COMMENTS_LINE2>
<COMMENTS_LINE3></COMMENTS_LINE3>
<ADDRESS1>115 Colburn Avenue</ADDRESS1>
<ADDRESS2></ADDRESS2>
<CITY>Clarks Summit</CITY>
<STATE>PA</STATE>
<ZIPCODE>18411</ZIPCODE>
<ORGANIZATION_HOMEPAGE></ORGANIZATION_HOMEPAGE>
</RECORD>
<RECORD>
<REC_ID>1504</REC_ID>
<FORCED_ORGANIZATION_NAME>Abington Heights School District</FORCED_ORGANIZATION_NAME>
<ORGANIZATION_NAME1>Abington Heights School District</ORGANIZATION_NAME1>
<ORGANIZATION_NAME2></ORGANIZATION_NAME2>
<ORGANIZATION_NAME3></ORGANIZATION_NAME3>
<ALT_ORGANIZATION_NAME></ALT_ORGANIZATION_NAME>
<FORCED_COUNTY_NAME>Lackawanna</FORCED_COUNTY_NAME>
<COUNTY_NAME1>Lackawanna</COUNTY_NAME1>
<COUNTY_NAME2></COUNTY_NAME2>
<ALT_COUNTY_NAME></ALT_COUNTY_NAME>
<FORCED_CATEGORY_NAME>Public Schools/Colleges</FORCED_CATEGORY_NAME>
<CAT_CODE>1</CAT_CODE>
<CATEGORY_NAME1>Public Schools/Colleges</CATEGORY_NAME1>
<CATEGORY_NAME2></CATEGORY_NAME2>
<COMPLETE_STATUS></COMPLETE_STATUS>
<FORCED_STATUS_NAME></FORCED_STATUS_NAME>
<STATUS_NAME1></STATUS_NAME1>
<STATUS_NAME2></STATUS_NAME2>
<STATUS_NAME3></STATUS_NAME3>
<ALT_STATUS_TEXT></ALT_STATUS_TEXT>
<STATUS_CODE></STATUS_CODE>
<STATUS2_NAME1></STATUS2_NAME1>
<STATUS2_NAME2></STATUS2_NAME2>
<STATUS2_NAME3></STATUS2_NAME3>
<STATUS_CODE2></STATUS_CODE2>
<EXPIRATION></EXPIRATION>
<UPDATED></UPDATED>
<COMMENTS_LINE1></COMMENTS_LINE1>
<COMMENTS_LINE2></COMMENTS_LINE2>
<COMMENTS_LINE3></COMMENTS_LINE3>
<ADDRESS1>200 E Grove Street</ADDRESS1>
<ADDRESS2></ADDRESS2>
<CITY>Clarks Summit</CITY>
<STATE>PA</STATE>
<ZIPCODE>18411</ZIPCODE>
<ORGANIZATION_HOMEPAGE></ORGANIZATION_HOMEPAGE>
</RECORD>
<RECORD>
<REC_ID>3076</REC_ID>
<FORCED_ORGANIZATION_NAME>Abundant Blessings Christian Daycare</FORCED_ORGANIZATION_NAME>
<ORGANIZATION_NAME1>Abundant Blessings Christian Daycare</ORGANIZATION_NAME1>
<ORGANIZATION_NAME2></ORGANIZATION_NAME2>
<ORGANIZATION_NAME3></ORGANIZATION_NAME3>
<ALT_ORGANIZATION_NAME></ALT_ORGANIZATION_NAME>
<FORCED_COUNTY_NAME>Lycoming</FORCED_COUNTY_NAME>
<COUNTY_NAME1>Lycoming</COUNTY_NAME1>
<COUNTY_NAME2></COUNTY_NAME2>
<ALT_COUNTY_NAME></ALT_COUNTY_NAME>
<FORCED_CATEGORY_NAME>Daycare/Preschool</FORCED_CATEGORY_NAME>
<CAT_CODE>3</CAT_CODE>
<CATEGORY_NAME1>Daycare/Preschool</CATEGORY_NAME1>
<CATEGORY_NAME2></CATEGORY_NAME2>
<COMPLETE_STATUS></COMPLETE_STATUS>
<FORCED_STATUS_NAME></FORCED_STATUS_NAME>
<STATUS_NAME1></STATUS_NAME1>
<STATUS_NAME2></STATUS_NAME2>
<STATUS_NAME3></STATUS_NAME3>
<ALT_STATUS_TEXT></ALT_STATUS_TEXT>
<STATUS_CODE></STATUS_CODE>
<STATUS2_NAME1></STATUS2_NAME1>
<STATUS2_NAME2></STATUS2_NAME2>
<STATUS2_NAME3></STATUS2_NAME3>
<STATUS_CODE2></STATUS_CODE2>
<EXPIRATION></EXPIRATION>
<UPDATED></UPDATED>
<COMMENTS_LINE1></COMMENTS_LINE1>
<COMMENTS_LINE2></COMMENTS_LINE2>
<COMMENTS_LINE3></COMMENTS_LINE3>
<ADDRESS1>701 South Second Street</ADDRESS1>
<ADDRESS2></ADDRESS2>
<CITY>Sunbury</CITY>
<STATE>PA</STATE>
<ZIPCODE>17801</ZIPCODE>
<ORGANIZATION_HOMEPAGE></ORGANIZATION_HOMEPAGE>
</RECORD>
<RECORD>
<REC_ID>3648</REC_ID>
<FORCED_ORGANIZATION_NAME>Access Services</FORCED_ORGANIZATION_NAME>
<ORGANIZATION_NAME1>Access Services</ORGANIZATION_NAME1>
<ORGANIZATION_NAME2></ORGANIZATION_NAME2>
<ORGANIZATION_NAME3></ORGANIZATION_NAME3>
<ALT_ORGANIZATION_NAME></ALT_ORGANIZATION_NAME>
<FORCED_COUNTY_NAME></FORCED_COUNTY_NAME>
<COUNTY_NAME1></COUNTY_NAME1>
<COUNTY_NAME2></COUNTY_NAME2>
<ALT_COUNTY_NAME></ALT_COUNTY_NAME>
<FORCED_CATEGORY_NAME>Business</FORCED_CATEGORY_NAME>
<CAT_CODE>4</CAT_CODE>
<CATEGORY_NAME1>Business</CATEGORY_NAME1>
<CATEGORY_NAME2></CATEGORY_NAME2>
<COMPLETE_STATUS></COMPLETE_STATUS>
<FORCED_STATUS_NAME></FORCED_STATUS_NAME>
<STATUS_NAME1></STATUS_NAME1>
<STATUS_NAME2></STATUS_NAME2>
<STATUS_NAME3></STATUS_NAME3>
<ALT_STATUS_TEXT></ALT_STATUS_TEXT>
<STATUS_CODE></STATUS_CODE>
<STATUS2_NAME1></STATUS2_NAME1>
<STATUS2_NAME2></STATUS2_NAME2>
<STATUS2_NAME3></STATUS2_NAME3>
<STATUS_CODE2></STATUS_CODE2>
<EXPIRATION></EXPIRATION>
<UPDATED></UPDATED>
<COMMENTS_LINE1></COMMENTS_LINE1>
<COMMENTS_LINE2></COMMENTS_LINE2>
<COMMENTS_LINE3></COMMENTS_LINE3>
<ADDRESS1></ADDRESS1>
<ADDRESS2></ADDRESS2>
<CITY></CITY>
<STATE>PA</STATE>
<ZIPCODE></ZIPCODE>
<ORGANIZATION_HOMEPAGE></ORGANIZATION_HOMEPAGE>
</RECORD>
<RECORD>
<REC_ID>1012</REC_ID>
<FORCED_ORGANIZATION_NAME>Acorns to Oaks</FORCED_ORGANIZATION_NAME>
<ORGANIZATION_NAME1>Acorns to Oaks</ORGANIZATION_NAME1>
<ORGANIZATION_NAME2></ORGANIZATION_NAME2>
<ORGANIZATION_NAME3></ORGANIZATION_NAME3>
<ALT_ORGANIZATION_NAME></ALT_ORGANIZATION_NAME>
<FORCED_COUNTY_NAME>Monroe</FORCED_COUNTY_NAME>
<COUNTY_NAME1>Monroe</COUNTY_NAME1>
<COUNTY_NAME2></COUNTY_NAME2>
<ALT_COUNTY_NAME></ALT_COUNTY_NAME>
<FORCED_CATEGORY_NAME>Daycare/Preschool</FORCED_CATEGORY_NAME>
<CAT_CODE>3</CAT_CODE>
<CATEGORY_NAME1>Daycare/Preschool</CATEGORY_NAME1>
<CATEGORY_NAME2></CATEGORY_NAME2>
<COMPLETE_STATUS></COMPLETE_STATUS>
<FORCED_STATUS_NAME></FORCED_STATUS_NAME>
<STATUS_NAME1></STATUS_NAME1>
<STATUS_NAME2></STATUS_NAME2>
<STATUS_NAME3></STATUS_NAME3>
<ALT_STATUS_TEXT></ALT_STATUS_TEXT>
<STATUS_CODE></STATUS_CODE>
<STATUS2_NAME1></STATUS2_NAME1>
<STATUS2_NAME2></STATUS2_NAME2>
<STATUS2_NAME3></STATUS2_NAME3>
<STATUS_CODE2></STATUS_CODE2>
<EXPIRATION></EXPIRATION>
<UPDATED></UPDATED>
<COMMENTS_LINE1></COMMENTS_LINE1>
<COMMENTS_LINE2></COMMENTS_LINE2>
<COMMENTS_LINE3></COMMENTS_LINE3>
<ADDRESS1>125 Rose Street</ADDRESS1>
<ADDRESS2></ADDRESS2>
<CITY>Scotrun</CITY>
<STATE>PA</STATE>
<ZIPCODE>18355</ZIPCODE>
<ORGANIZATION_HOMEPAGE></ORGANIZATION_HOMEPAGE>
</RECORD>
<RECORD>
<REC_ID>3728</REC_ID>
<FORCED_ORGANIZATION_NAME>Actors Circle</FORCED_ORGANIZATION_NAME>
<ORGANIZATION_NAME1>Actors Circle</ORGANIZATION_NAME1>
<ORGANIZATION_NAME2></ORGANIZATION_NAME2>
<ORGANIZATION_NAME3></ORGANIZATION_NAME3>
<ALT_ORGANIZATION_NAME></ALT_ORGANIZATION_NAME>
<FORCED_COUNTY_NAME>Lackawanna</FORCED_COUNTY_NAME>
<COUNTY_NAME1>Lackawanna</COUNTY_NAME1>
<COUNTY_NAME2></COUNTY_NAME2>
<ALT_COUNTY_NAME></ALT_COUNTY_NAME>
<FORCED_CATEGORY_NAME>Business</FORCED_CATEGORY_NAME>
<CAT_CODE>4</CAT_CODE>
<CATEGORY_NAME1>Business</CATEGORY_NAME1>
<CATEGORY_NAME2></CATEGORY_NAME2>
<COMPLETE_STATUS></COMPLETE_STATUS>
<FORCED_STATUS_NAME></FORCED_STATUS_NAME>
<STATUS_NAME1></STATUS_NAME1>
<STATUS_NAME2></STATUS_NAME2>
<STATUS_NAME3></STATUS_NAME3>
<ALT_STATUS_TEXT></ALT_STATUS_TEXT>
<STATUS_CODE></STATUS_CODE>
<STATUS2_NAME1></STATUS2_NAME1>
<STATUS2_NAME2></STATUS2_NAME2>
<STATUS2_NAME3></STATUS2_NAME3>
<STATUS_CODE2></STATUS_CODE2>
<EXPIRATION></EXPIRATION>
<UPDATED></UPDATED>
<COMMENTS_LINE1></COMMENTS_LINE1>
<COMMENTS_LINE2></COMMENTS_LINE2>
<COMMENTS_LINE3></COMMENTS_LINE3>
<ADDRESS1></ADDRESS1>
<ADDRESS2></ADDRESS2>
<CITY></CITY>
<STATE>PA</STATE>
<ZIPCODE></ZIPCODE>
<ORGANIZATION_HOMEPAGE></ORGANIZATION_HOMEPAGE>
</RECORD>
<RECORD>
<REC_ID>2948</REC_ID>
<FORCED_ORGANIZATION_NAME>Adventures in Learning Child Care</FORCED_ORGANIZATION_NAME>
<ORGANIZATION_NAME1>Adventures in Learning Child Care</ORGANIZATION_NAME1>
<ORGANIZATION_NAME2></ORGANIZATION_NAME2>
<ORGANIZATION_NAME3></ORGANIZATION_NAME3>
<ALT_ORGANIZATION_NAME></ALT_ORGANIZATION_NAME>
<FORCED_COUNTY_NAME>Luzerne</FORCED_COUNTY_NAME>
<COUNTY_NAME1>Luzerne</COUNTY_NAME1>
<COUNTY_NAME2></COUNTY_NAME2>
<ALT_COUNTY_NAME></ALT_COUNTY_NAME>
<FORCED_CATEGORY_NAME>Daycare/Preschool</FORCED_CATEGORY_NAME>
<CAT_CODE>3</CAT_CODE>
<CATEGORY_NAME1>Daycare/Preschool</CATEGORY_NAME1>
<CATEGORY_NAME2></CATEGORY_NAME2>
<COMPLETE_STATUS></COMPLETE_STATUS>
<FORCED_STATUS_NAME></FORCED_STATUS_NAME>
<STATUS_NAME1></STATUS_NAME1>
<STATUS_NAME2></STATUS_NAME2>
<STATUS_NAME3></STATUS_NAME3>
<ALT_STATUS_TEXT></ALT_STATUS_TEXT>
<STATUS_CODE></STATUS_CODE>
<STATUS2_NAME1></STATUS2_NAME1>
<STATUS2_NAME2></STATUS2_NAME2>
<STATUS2_NAME3></STATUS2_NAME3>
<STATUS_CODE2></STATUS_CODE2>
<EXPIRATION></EXPIRATION>
<UPDATED></UPDATED>
<COMMENTS_LINE1></COMMENTS_LINE1>
<COMMENTS_LINE2></COMMENTS_LINE2>
<COMMENTS_LINE3></COMMENTS_LINE3>
<ADDRESS1>301 Lake Street</ADDRESS1>
<ADDRESS2></ADDRESS2>
<CITY>Dallas</CITY>
<STATE>PA</STATE>
<ZIPCODE>18612</ZIPCODE>
<ORGANIZATION_HOMEPAGE></ORGANIZATION_HOMEPAGE>
</RECORD>
<RECORD>
<REC_ID>1576</REC_ID>
<FORCED_ORGANIZATION_NAME>All Saints Academy/Scranton</FORCED_ORGANIZATION_NAME>
<ORGANIZATION_NAME1>All Saints Academy/Scranton</ORGANIZATION_NAME1>
<ORGANIZATION_NAME2></ORGANIZATION_NAME2>
<ORGANIZATION_NAME3></ORGANIZATION_NAME3>
<ALT_ORGANIZATION_NAME></ALT_ORGANIZATION_NAME>
<FORCED_COUNTY_NAME>Lackawanna</FORCED_COUNTY_NAME>
<COUNTY_NAME1>Lackawanna</COUNTY_NAME1>
<COUNTY_NAME2></COUNTY_NAME2>
<ALT_COUNTY_NAME></ALT_COUNTY_NAME>
<FORCED_CATEGORY_NAME>Catholic Schools/Tech Schools</FORCED_CATEGORY_NAME>
<CAT_CODE>2</CAT_CODE>
<CATEGORY_NAME1>Catholic Schools/Tech Schools</CATEGORY_NAME1>
<CATEGORY_NAME2></CATEGORY_NAME2>
<COMPLETE_STATUS></COMPLETE_STATUS>
<FORCED_STATUS_NAME></FORCED_STATUS_NAME>
<STATUS_NAME1></STATUS_NAME1>
<STATUS_NAME2></STATUS_NAME2>
<STATUS_NAME3></STATUS_NAME3>
<ALT_STATUS_TEXT></ALT_STATUS_TEXT>
<STATUS_CODE></STATUS_CODE>
<STATUS2_NAME1></STATUS2_NAME1>
<STATUS2_NAME2></STATUS2_NAME2>
<STATUS2_NAME3></STATUS2_NAME3>
<STATUS_CODE2></STATUS_CODE2>
<EXPIRATION></EXPIRATION>
<UPDATED></UPDATED>
<COMMENTS_LINE1></COMMENTS_LINE1>
<COMMENTS_LINE2></COMMENTS_LINE2>
<COMMENTS_LINE3></COMMENTS_LINE3>
<ADDRESS1>1425 Jackson Street</ADDRESS1>
<ADDRESS2></ADDRESS2>
<CITY>Scranton</CITY>
<STATE>PA</STATE>
<ZIPCODE>18504</ZIPCODE>
<ORGANIZATION_HOMEPAGE></ORGANIZATION_HOMEPAGE>
</RECORD>
<RECORD>
<REC_ID>3620</REC_ID>
<FORCED_ORGANIZATION_NAME>All the latest closings and delays on</FORCED_ORGANIZATION_NAME>
<ORGANIZATION_NAME1>All the latest closings and delays on</ORGANIZATION_NAME1>
<ORGANIZATION_NAME2></ORGANIZATION_NAME2>
<ORGANIZATION_NAME3></ORGANIZATION_NAME3>
<ALT_ORGANIZATION_NAME></ALT_ORGANIZATION_NAME>
<FORCED_COUNTY_NAME></FORCED_COUNTY_NAME>
<COUNTY_NAME1></COUNTY_NAME1>
<COUNTY_NAME2></COUNTY_NAME2>
<ALT_COUNTY_NAME></ALT_COUNTY_NAME>
<FORCED_CATEGORY_NAME></FORCED_CATEGORY_NAME>
<CAT_CODE></CAT_CODE>
<CATEGORY_NAME1></CATEGORY_NAME1>
<CATEGORY_NAME2></CATEGORY_NAME2>
<COMPLETE_STATUS></COMPLETE_STATUS>
<FORCED_STATUS_NAME></FORCED_STATUS_NAME>
<STATUS_NAME1></STATUS_NAME1>
<STATUS_NAME2></STATUS_NAME2>
<STATUS_NAME3></STATUS_NAME3>
<ALT_STATUS_TEXT></ALT_STATUS_TEXT>
<STATUS_CODE></STATUS_CODE>
<STATUS2_NAME1></STATUS2_NAME1>
<STATUS2_NAME2></STATUS2_NAME2>
<STATUS2_NAME3></STATUS2_NAME3>
<STATUS_CODE2></STATUS_CODE2>
<EXPIRATION></EXPIRATION>
<UPDATED></UPDATED>
<COMMENTS_LINE1></COMMENTS_LINE1>
<COMMENTS_LINE2></COMMENTS_LINE2>
<COMMENTS_LINE3></COMMENTS_LINE3>
<ADDRESS1></ADDRESS1>
<ADDRESS2></ADDRESS2>
<CITY></CITY>
<STATE>PA</STATE>
<ZIPCODE></ZIPCODE>
<ORGANIZATION_HOMEPAGE></ORGANIZATION_HOMEPAGE>
</RECORD>
<RECORD>
<REC_ID>3088</REC_ID>
<FORCED_ORGANIZATION_NAME>Allied Services dePaul School</FORCED_ORGANIZATION_NAME>
<ORGANIZATION_NAME1>Allied Services dePaul School</ORGANIZATION_NAME1>
<ORGANIZATION_NAME2></ORGANIZATION_NAME2>
<ORGANIZATION_NAME3></ORGANIZATION_NAME3>
<ALT_ORGANIZATION_NAME></ALT_ORGANIZATION_NAME>
<FORCED_COUNTY_NAME>Lackawanna</FORCED_COUNTY_NAME>
<COUNTY_NAME1>Lackawanna</COUNTY_NAME1>
<COUNTY_NAME2></COUNTY_NAME2>
<ALT_COUNTY_NAME></ALT_COUNTY_NAME>
<FORCED_CATEGORY_NAME>Catholic Schools/Tech Schools</FORCED_CATEGORY_NAME>
<CAT_CODE>2</CAT_CODE>
<CATEGORY_NAME1>Catholic Schools/Tech Schools</CATEGORY_NAME1>
<CATEGORY_NAME2></CATEGORY_NAME2>
<COMPLETE_STATUS></COMPLETE_STATUS>
<FORCED_STATUS_NAME></FORCED_STATUS_NAME>
<STATUS_NAME1></STATUS_NAME1>
<STATUS_NAME2></STATUS_NAME2>
<STATUS_NAME3></STATUS_NAME3>
<ALT_STATUS_TEXT></ALT_STATUS_TEXT>
<STATUS_CODE></STATUS_CODE>
<STATUS2_NAME1></STATUS2_NAME1>
<STATUS2_NAME2></STATUS2_NAME2>
<STATUS2_NAME3></STATUS2_NAME3>
<STATUS_CODE2></STATUS_CODE2>
<EXPIRATION></EXPIRATION>
<UPDATED></UPDATED>
<COMMENTS_LINE1></COMMENTS_LINE1>
<COMMENTS_LINE2></COMMENTS_LINE2>
<COMMENTS_LINE3></COMMENTS_LINE3>
<ADDRESS1>475 Morgan Highway</ADDRESS1>
<ADDRESS2></ADDRESS2>
<CITY>Scranton</CITY>
<STATE>PA</STATE>
<ZIPCODE>18501</ZIPCODE>
<ORGANIZATION_HOMEPAGE></ORGANIZATION_HOMEPAGE>
</RECORD>
<RECORD>
<REC_ID>3368</REC_ID>
<FORCED_ORGANIZATION_NAME>Alnoor Academy</FORCED_ORGANIZATION_NAME>
<ORGANIZATION_NAME1>Alnoor Academy</ORGANIZATION_NAME1>
<ORGANIZATION_NAME2></ORGANIZATION_NAME2>
<ORGANIZATION_NAME3></ORGANIZATION_NAME3>
<ALT_ORGANIZATION_NAME></ALT_ORGANIZATION_NAME>
<FORCED_COUNTY_NAME>Luzerne</FORCED_COUNTY_NAME>
<COUNTY_NAME1>Luzerne</COUNTY_NAME1>
<COUNTY_NAME2></COUNTY_NAME2>
<ALT_COUNTY_NAME></ALT_COUNTY_NAME>
<FORCED_CATEGORY_NAME>Daycare/Preschool</FORCED_CATEGORY_NAME>
<CAT_CODE>3</CAT_CODE>
<CATEGORY_NAME1>Daycare/Preschool</CATEGORY_NAME1>
<CATEGORY_NAME2></CATEGORY_NAME2>
<COMPLETE_STATUS></COMPLETE_STATUS>
<FORCED_STATUS_NAME></FORCED_STATUS_NAME>
<STATUS_NAME1></STATUS_NAME1>
<STATUS_NAME2></STATUS_NAME2>
<STATUS_NAME3></STATUS_NAME3>
<ALT_STATUS_TEXT></ALT_STATUS_TEXT>
<STATUS_CODE></STATUS_CODE>
<STATUS2_NAME1></STATUS2_NAME1>
<STATUS2_NAME2></STATUS2_NAME2>
<STATUS2_NAME3></STATUS2_NAME3>
<STATUS_CODE2></STATUS_CODE2>
<EXPIRATION></EXPIRATION>
<UPDATED></UPDATED>
<COMMENTS_LINE1></COMMENTS_LINE1>
<COMMENTS_LINE2></COMMENTS_LINE2>
<COMMENTS_LINE3></COMMENTS_LINE3>
<ADDRESS1>PO Box 5061</ADDRESS1>
<ADDRESS2></ADDRESS2>
<CITY>Wilkes-Barre</CITY>
<STATE>PA</STATE>
<ZIPCODE>18710</ZIPCODE>
<ORGANIZATION_HOMEPAGE></ORGANIZATION_HOMEPAGE>
</RECORD>
<RECORD>
<REC_ID>1024</REC_ID>
<FORCED_ORGANIZATION_NAME>Alternative Learning Center</FORCED_ORGANIZATION_NAME>
<ORGANIZATION_NAME1>Alternative Learning Center</ORGANIZATION_NAME1>
<ORGANIZATION_NAME2></ORGANIZATION_NAME2>
<ORGANIZATION_NAME3></ORGANIZATION_NAME3>
<ALT_ORGANIZATION_NAME></ALT_ORGANIZATION_NAME>
<FORCED_COUNTY_NAME>Luzerne</FORCED_COUNTY_NAME>
<COUNTY_NAME1>Luzerne</COUNTY_NAME1>
<COUNTY_NAME2></COUNTY_NAME2>
<ALT_COUNTY_NAME></ALT_COUNTY_NAME>
<FORCED_CATEGORY_NAME>Daycare/Preschool</FORCED_CATEGORY_NAME>
<CAT_CODE>3</CAT_CODE>
<CATEGORY_NAME1>Daycare/Preschool</CATEGORY_NAME1>
<CATEGORY_NAME2></CATEGORY_NAME2>
<COMPLETE_STATUS></COMPLETE_STATUS>
<FORCED_STATUS_NAME></FORCED_STATUS_NAME>
<STATUS_NAME1></STATUS_NAME1>
<STATUS_NAME2></STATUS_NAME2>
<STATUS_NAME3></STATUS_NAME3>
<ALT_STATUS_TEXT></ALT_STATUS_TEXT>
<STATUS_CODE></STATUS_CODE>
<STATUS2_NAME1></STATUS2_NAME1>
<STATUS2_NAME2></STATUS2_NAME2>
<STATUS2_NAME3></STATUS2_NAME3>
<STATUS_CODE2></STATUS_CODE2>
<EXPIRATION></EXPIRATION>
<UPDATED></UPDATED>
<COMMENTS_LINE1></COMMENTS_LINE1>
<COMMENTS_LINE2></COMMENTS_LINE2>
<COMMENTS_LINE3></COMMENTS_LINE3>
<ADDRESS1>33 W Carey Street</ADDRESS1>
<ADDRESS2></ADDRESS2>
<CITY>Plains</CITY>
<STATE>PA</STATE>
<ZIPCODE>18705</ZIPCODE>
<ORGANIZATION_HOMEPAGE></ORGANIZATION_HOMEPAGE>
</RECORD>
<RECORD>
<REC_ID>1560</REC_ID>
<FORCED_ORGANIZATION_NAME>Alvernia University/Schuylkill Ctr</FORCED_ORGANIZATION_NAME>
<ORGANIZATION_NAME1>Alvernia University/Schuylkill Ctr</ORGANIZATION_NAME1>
<ORGANIZATION_NAME2></ORGANIZATION_NAME2>
<ORGANIZATION_NAME3></ORGANIZATION_NAME3>
<ALT_ORGANIZATION_NAME></ALT_ORGANIZATION_NAME>
<FORCED_COUNTY_NAME>Schuylkill</FORCED_COUNTY_NAME>
<COUNTY_NAME1>Schuylkill</COUNTY_NAME1>
<COUNTY_NAME2></COUNTY_NAME2>
<ALT_COUNTY_NAME></ALT_COUNTY_NAME>
<FORCED_CATEGORY_NAME>Public Schools/Colleges</FORCED_CATEGORY_NAME>
<CAT_CODE>1</CAT_CODE>
<CATEGORY_NAME1>Public Schools/Colleges</CATEGORY_NAME1>
<CATEGORY_NAME2></CATEGORY_NAME2>
<COMPLETE_STATUS></COMPLETE_STATUS>
<FORCED_STATUS_NAME></FORCED_STATUS_NAME>
<STATUS_NAME1></STATUS_NAME1>
<STATUS_NAME2></STATUS_NAME2>
<STATUS_NAME3></STATUS_NAME3>
<ALT_STATUS_TEXT></ALT_STATUS_TEXT>
<STATUS_CODE></STATUS_CODE>
<STATUS2_NAME1></STATUS2_NAME1>
<STATUS2_NAME2></STATUS2_NAME2>
<STATUS2_NAME3></STATUS2_NAME3>
<STATUS_CODE2></STATUS_CODE2>
<EXPIRATION></EXPIRATION>
<UPDATED></UPDATED>
<COMMENTS_LINE1></COMMENTS_LINE1>
<COMMENTS_LINE2></COMMENTS_LINE2>
<COMMENTS_LINE3></COMMENTS_LINE3>
<ADDRESS1>2650 Woodglen Road</ADDRESS1>
<ADDRESS2></ADDRESS2>
<CITY>Pottsville</CITY>
<STATE>PA</STATE>
<ZIPCODE>17901</ZIPCODE>
<ORGANIZATION_HOMEPAGE></ORGANIZATION_HOMEPAGE>
</RECORD>
<RECORD>
<REC_ID>3208</REC_ID>
<FORCED_ORGANIZATION_NAME>Amedisys Hospice</FORCED_ORGANIZATION_NAME>
<ORGANIZATION_NAME1>Amedisys Hospice</ORGANIZATION_NAME1>
<ORGANIZATION_NAME2></ORGANIZATION_NAME2>
<ORGANIZATION_NAME3></ORGANIZATION_NAME3>
<ALT_ORGANIZATION_NAME></ALT_ORGANIZATION_NAME>
<FORCED_COUNTY_NAME>Luzerne</FORCED_COUNTY_NAME>
<COUNTY_NAME1>Luzerne</COUNTY_NAME1>
<COUNTY_NAME2></COUNTY_NAME2>
<ALT_COUNTY_NAME></ALT_COUNTY_NAME>
<FORCED_CATEGORY_NAME>Business</FORCED_CATEGORY_NAME>
<CAT_CODE>4</CAT_CODE>
<CATEGORY_NAME1>Business</CATEGORY_NAME1>
<CATEGORY_NAME2></CATEGORY_NAME2>
<COMPLETE_STATUS></COMPLETE_STATUS>
<FORCED_STATUS_NAME></FORCED_STATUS_NAME>
<STATUS_NAME1></STATUS_NAME1>
<STATUS_NAME2></STATUS_NAME2>
<STATUS_NAME3></STATUS_NAME3>
<ALT_STATUS_TEXT></ALT_STATUS_TEXT>
<STATUS_CODE></STATUS_CODE>
<STATUS2_NAME1></STATUS2_NAME1>