<?xml version="1.0" standalone="no" ?>
<!DOCTYPE DATA [
  <!ELEMENT DATA                     (SOURCE,EXPORT_TYPE,NUM_CLOSINGS,RUN_DATE,RUN_EPOCH,RECORD*)>
  <!ELEMENT SOURCE                   (CDATA)>
  <!ELEMENT EXPORT_TYPE              (CDATA)>
  <!ELEMENT NUM_CLOSINGS             (CDATA)>
  <!ELEMENT RUN_DATE                 (CDATA)>
  <!ELEMENT RUN_EPOCH                (CDATA)>
  <!ELEMENT RECORD                   (REC_ID,FORCED_ORGANIZATION_NAME,ORGANIZATION_NAME1,ORGANIZATION_NAME2,ORGANIZATION_NAME3,ALT_ORGANIZATION_NAME,FORCED_COUNTY_NAME,COUNTY_NAME1,COUNTY_NAME2,ALT_COUNTY_NAME,CAT_CODE,CATEGORY_NAME1,CATEGORY_NAME2,FORCED_STATUS_NAME,STATUS_NAME1,STATUS_NAME2,STATUS_NAME3,ALT_STATUS_TEXT,STATUS_CODE,STATUS2_NAME1,STATUS2_NAME2,STATUS2_NAME3,STATUS_CODE2,EXPIRATION,UPDATED,COMMENTS_LINE1,COMMENTS_LINE2,COMMENTS_LINE3,ADDRESS1,ADDRESS2,CITY,STATE,ZIPCODE,ORGANIZATION_HOMEPAGE)>
  <!ELEMENT REC_ID                   (ID)>
  <!ELEMENT FORCED_ORGANIZATION_NAME (CDATA)>
  <!ELEMENT ORGANIZATION_NAME1       (CDATA)>
  <!ELEMENT ORGANIZATION_NAME2       (CDATA)>
  <!ELEMENT ORGANIZATION_NAME3       (CDATA)>
  <!ELEMENT ALT_ORGANIZATION_NAME    (CDATA)>
  <!ELEMENT FORCED_COUNTY_NAME       (CDATA)>
  <!ELEMENT COUNTY_NAME1             (CDATA)>
  <!ELEMENT COUNTY_NAME2             (CDATA)>
  <!ELEMENT ALT_COUNTY_NAME          (CDATA)>
  <!ELEMENT CAT_CODE                 (CDATA)>
  <!ELEMENT CATEGORY_NAME1           (CDATA)>
  <!ELEMENT CATEGORY_NAME2           (CDATA)>
  <!ELEMENT FORCED_STATUS_NAME       (CDATA)>
  <!ELEMENT STATUS_NAME1             (CDATA)>
  <!ELEMENT STATUS_NAME2             (CDATA)>
  <!ELEMENT STATUS_NAME3             (CDATA)>
  <!ELEMENT ALT_STATUS_TEXT          (CDATA)>
  <!ELEMENT STATUS_CODE              (CDATA)>
  <!ELEMENT STATUS2_NAME1            (CDATA)>
  <!ELEMENT STATUS2_NAME2            (CDATA)>
  <!ELEMENT STATUS2_NAME3            (CDATA)>
  <!ELEMENT STATUS_CODE2             (CDATA)>
  <!ELEMENT EXPIRATION               (CDATA)>
  <!ELEMENT UPDATED                  (CDATA)>
  <!ELEMENT COMMENTS_LINE1           (CDATA)>
  <!ELEMENT COMMENTS_LINE2           (CDATA)>
  <!ELEMENT COMMENTS_LINE3           (CDATA)>
  <!ELEMENT ADDRESS1                 (CDATA)>
  <!ELEMENT ADDRESS2                 (CDATA)>
  <!ELEMENT CITY                     (CDATA)>
  <!ELEMENT STATE                    (CDATA)>
  <!ELEMENT ZIPCODE                  (CDATA)>
  <!ELEMENT ORGANIZATION_HOMEPAGE    (CDATA)>
]>
<DATA>
<SOURCE>NewsTicker</SOURCE>
<EXPORT_TYPE>L2</EXPORT_TYPE>
<NUM_CLOSINGS>1023</NUM_CLOSINGS>
<RUN_DATE>Mon Jul 13 03:03:01 EDT 2015</RUN_DATE>
<RUN_EPOCH>1436770981</RUN_EPOCH>
<RECORD>
<REC_ID>89858</REC_ID>
<FORCED_ORGANIZATION_NAME>Planned Parenthood-Batavia</FORCED_ORGANIZATION_NAME>
<ORGANIZATION_NAME1>Planned Parenthood-Batavia</ORGANIZATION_NAME1>
<ORGANIZATION_NAME2></ORGANIZATION_NAME2>
<ORGANIZATION_NAME3></ORGANIZATION_NAME3>
<ALT_ORGANIZATION_NAME></ALT_ORGANIZATION_NAME>
<FORCED_COUNTY_NAME>Genesee County</FORCED_COUNTY_NAME>
<COUNTY_NAME1>Genesee County</COUNTY_NAME1>
<COUNTY_NAME2>Gene</COUNTY_NAME2>
<ALT_COUNTY_NAME></ALT_COUNTY_NAME>
<FORCED_CATEGORY_NAME></FORCED_CATEGORY_NAME>
<CAT_CODE></CAT_CODE>
<CATEGORY_NAME1></CATEGORY_NAME1>
<CATEGORY_NAME2></CATEGORY_NAME2>
<FORCED_STATUS_NAME></FORCED_STATUS_NAME>
<STATUS_NAME1></STATUS_NAME1>
<STATUS_NAME2></STATUS_NAME2>
<STATUS_NAME3></STATUS_NAME3>
<ALT_STATUS_TEXT></ALT_STATUS_TEXT>
<STATUS_CODE></STATUS_CODE>
<STATUS2_NAME1></STATUS2_NAME1>
<STATUS2_NAME2></STATUS2_NAME2>
<STATUS2_NAME3></STATUS2_NAME3>
<STATUS_CODE2></STATUS_CODE2>
<EXPIRATION></EXPIRATION>
<UPDATED></UPDATED>
<COMMENTS_LINE1></COMMENTS_LINE1>
<COMMENTS_LINE2></COMMENTS_LINE2>
<COMMENTS_LINE3></COMMENTS_LINE3>
<ADDRESS1>114 University Ave.</ADDRESS1>
<ADDRESS2></ADDRESS2>
<CITY>Rochester</CITY>
<STATE>NY</STATE>
<ZIPCODE>14605</ZIPCODE>
<ORGANIZATION_HOMEPAGE></ORGANIZATION_HOMEPAGE>
</RECORD>
<RECORD>
<REC_ID>89860</REC_ID>
<FORCED_ORGANIZATION_NAME>Planned Parenthood-Canandaigua</FORCED_ORGANIZATION_NAME>
<ORGANIZATION_NAME1>Planned Parenthood-Canandaigua</ORGANIZATION_NAME1>
<ORGANIZATION_NAME2></ORGANIZATION_NAME2>
<ORGANIZATION_NAME3></ORGANIZATION_NAME3>
<ALT_ORGANIZATION_NAME></ALT_ORGANIZATION_NAME>
<FORCED_COUNTY_NAME></FORCED_COUNTY_NAME>
<COUNTY_NAME1></COUNTY_NAME1>
<COUNTY_NAME2></COUNTY_NAME2>
<ALT_COUNTY_NAME></ALT_COUNTY_NAME>
<FORCED_CATEGORY_NAME></FORCED_CATEGORY_NAME>
<CAT_CODE></CAT_CODE>
<CATEGORY_NAME1></CATEGORY_NAME1>
<CATEGORY_NAME2></CATEGORY_NAME2>
<FORCED_STATUS_NAME></FORCED_STATUS_NAME>
<STATUS_NAME1></STATUS_NAME1>
<STATUS_NAME2></STATUS_NAME2>
<STATUS_NAME3></STATUS_NAME3>
<ALT_STATUS_TEXT></ALT_STATUS_TEXT>
<STATUS_CODE></STATUS_CODE>
<STATUS2_NAME1></STATUS2_NAME1>
<STATUS2_NAME2></STATUS2_NAME2>
<STATUS2_NAME3></STATUS2_NAME3>
<STATUS_CODE2></STATUS_CODE2>
<EXPIRATION></EXPIRATION>
<UPDATED></UPDATED>
<COMMENTS_LINE1></COMMENTS_LINE1>
<COMMENTS_LINE2></COMMENTS_LINE2>
<COMMENTS_LINE3></COMMENTS_LINE3>
<ADDRESS1>114 University Ave</ADDRESS1>
<ADDRESS2></ADDRESS2>
<CITY>Rochester</CITY>
<STATE></STATE>
<ZIPCODE>14605</ZIPCODE>
<ORGANIZATION_HOMEPAGE></ORGANIZATION_HOMEPAGE>
</RECORD>
<RECORD>
<REC_ID>89840</REC_ID>
<FORCED_ORGANIZATION_NAME>U.S. Bankruptcy Court-Buffalo</FORCED_ORGANIZATION_NAME>
<ORGANIZATION_NAME1>U.S. Bankruptcy Court-Buffalo</ORGANIZATION_NAME1>
<ORGANIZATION_NAME2></ORGANIZATION_NAME2>
<ORGANIZATION_NAME3></ORGANIZATION_NAME3>
<ALT_ORGANIZATION_NAME></ALT_ORGANIZATION_NAME>
<FORCED_COUNTY_NAME></FORCED_COUNTY_NAME>
<COUNTY_NAME1></COUNTY_NAME1>
<COUNTY_NAME2></COUNTY_NAME2>
<ALT_COUNTY_NAME></ALT_COUNTY_NAME>
<FORCED_CATEGORY_NAME></FORCED_CATEGORY_NAME>
<CAT_CODE></CAT_CODE>
<CATEGORY_NAME1></CATEGORY_NAME1>
<CATEGORY_NAME2></CATEGORY_NAME2>
<FORCED_STATUS_NAME></FORCED_STATUS_NAME>
<STATUS_NAME1></STATUS_NAME1>
<STATUS_NAME2></STATUS_NAME2>
<STATUS_NAME3></STATUS_NAME3>
<ALT_STATUS_TEXT></ALT_STATUS_TEXT>
<STATUS_CODE></STATUS_CODE>
<STATUS2_NAME1></STATUS2_NAME1>
<STATUS2_NAME2></STATUS2_NAME2>
<STATUS2_NAME3></STATUS2_NAME3>
<STATUS_CODE2></STATUS_CODE2>
<EXPIRATION></EXPIRATION>
<UPDATED></UPDATED>
<COMMENTS_LINE1></COMMENTS_LINE1>
<COMMENTS_LINE2></COMMENTS_LINE2>
<COMMENTS_LINE3></COMMENTS_LINE3>
<ADDRESS1></ADDRESS1>
<ADDRESS2></ADDRESS2>
<CITY></CITY>
<STATE></STATE>
<ZIPCODE></ZIPCODE>
<ORGANIZATION_HOMEPAGE></ORGANIZATION_HOMEPAGE>
</RECORD>
<RECORD>
<REC_ID>89841</REC_ID>
<FORCED_ORGANIZATION_NAME>U.S. Bankruptcy Court-Rochester</FORCED_ORGANIZATION_NAME>
<ORGANIZATION_NAME1>U.S. Bankruptcy Court-Rochester</ORGANIZATION_NAME1>
<ORGANIZATION_NAME2></ORGANIZATION_NAME2>
<ORGANIZATION_NAME3></ORGANIZATION_NAME3>
<ALT_ORGANIZATION_NAME></ALT_ORGANIZATION_NAME>
<FORCED_COUNTY_NAME></FORCED_COUNTY_NAME>
<COUNTY_NAME1></COUNTY_NAME1>
<COUNTY_NAME2></COUNTY_NAME2>
<ALT_COUNTY_NAME></ALT_COUNTY_NAME>
<FORCED_CATEGORY_NAME></FORCED_CATEGORY_NAME>
<CAT_CODE></CAT_CODE>
<CATEGORY_NAME1></CATEGORY_NAME1>
<CATEGORY_NAME2></CATEGORY_NAME2>
<FORCED_STATUS_NAME></FORCED_STATUS_NAME>
<STATUS_NAME1></STATUS_NAME1>
<STATUS_NAME2></STATUS_NAME2>
<STATUS_NAME3></STATUS_NAME3>
<ALT_STATUS_TEXT></ALT_STATUS_TEXT>
<STATUS_CODE></STATUS_CODE>
<STATUS2_NAME1></STATUS2_NAME1>
<STATUS2_NAME2></STATUS2_NAME2>
<STATUS2_NAME3></STATUS2_NAME3>
<STATUS_CODE2></STATUS_CODE2>
<EXPIRATION></EXPIRATION>
<UPDATED></UPDATED>
<COMMENTS_LINE1></COMMENTS_LINE1>
<COMMENTS_LINE2></COMMENTS_LINE2>
<COMMENTS_LINE3></COMMENTS_LINE3>
<ADDRESS1></ADDRESS1>
<ADDRESS2></ADDRESS2>
<CITY></CITY>
<STATE></STATE>
<ZIPCODE></ZIPCODE>
<ORGANIZATION_HOMEPAGE></ORGANIZATION_HOMEPAGE>
</RECORD>
<RECORD>
<REC_ID>89635</REC_ID>
<FORCED_ORGANIZATION_NAME>Watts Education</FORCED_ORGANIZATION_NAME>
<ORGANIZATION_NAME1>Watts Education</ORGANIZATION_NAME1>
<ORGANIZATION_NAME2></ORGANIZATION_NAME2>
<ORGANIZATION_NAME3></ORGANIZATION_NAME3>
<ALT_ORGANIZATION_NAME></ALT_ORGANIZATION_NAME>
<FORCED_COUNTY_NAME>Monroe County</FORCED_COUNTY_NAME>
<COUNTY_NAME1>Monroe County</COUNTY_NAME1>
<COUNTY_NAME2>Monr</COUNTY_NAME2>
<ALT_COUNTY_NAME></ALT_COUNTY_NAME>
<FORCED_CATEGORY_NAME></FORCED_CATEGORY_NAME>
<CAT_CODE></CAT_CODE>
<CATEGORY_NAME1></CATEGORY_NAME1>
<CATEGORY_NAME2></CATEGORY_NAME2>
<FORCED_STATUS_NAME></FORCED_STATUS_NAME>
<STATUS_NAME1></STATUS_NAME1>
<STATUS_NAME2></STATUS_NAME2>
<STATUS_NAME3></STATUS_NAME3>
<ALT_STATUS_TEXT></ALT_STATUS_TEXT>
<STATUS_CODE></STATUS_CODE>
<STATUS2_NAME1></STATUS2_NAME1>
<STATUS2_NAME2></STATUS2_NAME2>
<STATUS2_NAME3></STATUS2_NAME3>
<STATUS_CODE2></STATUS_CODE2>
<EXPIRATION></EXPIRATION>
<UPDATED></UPDATED>
<COMMENTS_LINE1></COMMENTS_LINE1>
<COMMENTS_LINE2></COMMENTS_LINE2>
<COMMENTS_LINE3></COMMENTS_LINE3>
<ADDRESS1>195 St. Paul St</ADDRESS1>
<ADDRESS2></ADDRESS2>
<CITY>Rochester</CITY>
<STATE>NY</STATE>
<ZIPCODE>14604</ZIPCODE>
<ORGANIZATION_HOMEPAGE></ORGANIZATION_HOMEPAGE>
</RECORD>
<RECORD>
<REC_ID>89998</REC_ID>
<FORCED_ORGANIZATION_NAME>WROC System 1</FORCED_ORGANIZATION_NAME>
<ORGANIZATION_NAME1>WROC System 1</ORGANIZATION_NAME1>
<ORGANIZATION_NAME2></ORGANIZATION_NAME2>
<ORGANIZATION_NAME3></ORGANIZATION_NAME3>
<ALT_ORGANIZATION_NAME></ALT_ORGANIZATION_NAME>
<FORCED_COUNTY_NAME></FORCED_COUNTY_NAME>
<COUNTY_NAME1></COUNTY_NAME1>
<COUNTY_NAME2></COUNTY_NAME2>
<ALT_COUNTY_NAME></ALT_COUNTY_NAME>
<FORCED_CATEGORY_NAME></FORCED_CATEGORY_NAME>
<CAT_CODE></CAT_CODE>
<CATEGORY_NAME1></CATEGORY_NAME1>
<CATEGORY_NAME2></CATEGORY_NAME2>
<FORCED_STATUS_NAME></FORCED_STATUS_NAME>
<STATUS_NAME1></STATUS_NAME1>
<STATUS_NAME2></STATUS_NAME2>
<STATUS_NAME3></STATUS_NAME3>
<ALT_STATUS_TEXT></ALT_STATUS_TEXT>
<STATUS_CODE></STATUS_CODE>
<STATUS2_NAME1></STATUS2_NAME1>
<STATUS2_NAME2></STATUS2_NAME2>
<STATUS2_NAME3></STATUS2_NAME3>
<STATUS_CODE2></STATUS_CODE2>
<EXPIRATION></EXPIRATION>
<UPDATED></UPDATED>
<COMMENTS_LINE1></COMMENTS_LINE1>
<COMMENTS_LINE2></COMMENTS_LINE2>
<COMMENTS_LINE3></COMMENTS_LINE3>
<ADDRESS1></ADDRESS1>
<ADDRESS2></ADDRESS2>
<CITY></CITY>
<STATE></STATE>
<ZIPCODE></ZIPCODE>
<ORGANIZATION_HOMEPAGE></ORGANIZATION_HOMEPAGE>
</RECORD>
<RECORD>
<REC_ID>89999</REC_ID>
<FORCED_ORGANIZATION_NAME>WROC System 2</FORCED_ORGANIZATION_NAME>
<ORGANIZATION_NAME1>WROC System 2</ORGANIZATION_NAME1>
<ORGANIZATION_NAME2></ORGANIZATION_NAME2>
<ORGANIZATION_NAME3></ORGANIZATION_NAME3>
<ALT_ORGANIZATION_NAME></ALT_ORGANIZATION_NAME>
<FORCED_COUNTY_NAME></FORCED_COUNTY_NAME>
<COUNTY_NAME1></COUNTY_NAME1>
<COUNTY_NAME2></COUNTY_NAME2>
<ALT_COUNTY_NAME></ALT_COUNTY_NAME>
<FORCED_CATEGORY_NAME></FORCED_CATEGORY_NAME>
<CAT_CODE></CAT_CODE>
<CATEGORY_NAME1></CATEGORY_NAME1>
<CATEGORY_NAME2></CATEGORY_NAME2>
<FORCED_STATUS_NAME></FORCED_STATUS_NAME>
<STATUS_NAME1></STATUS_NAME1>
<STATUS_NAME2></STATUS_NAME2>
<STATUS_NAME3></STATUS_NAME3>
<ALT_STATUS_TEXT></ALT_STATUS_TEXT>
<STATUS_CODE></STATUS_CODE>
<STATUS2_NAME1></STATUS2_NAME1>
<STATUS2_NAME2></STATUS2_NAME2>
<STATUS2_NAME3></STATUS2_NAME3>
<STATUS_CODE2></STATUS_CODE2>
<EXPIRATION></EXPIRATION>
<UPDATED></UPDATED>
<COMMENTS_LINE1></COMMENTS_LINE1>
<COMMENTS_LINE2></COMMENTS_LINE2>
<COMMENTS_LINE3></COMMENTS_LINE3>
<ADDRESS1></ADDRESS1>
<ADDRESS2></ADDRESS2>
<CITY></CITY>
<STATE></STATE>
<ZIPCODE></ZIPCODE>
<ORGANIZATION_HOMEPAGE></ORGANIZATION_HOMEPAGE>
</RECORD>
<RECORD>
<REC_ID>89997</REC_ID>
<FORCED_ORGANIZATION_NAME>WROC System 3</FORCED_ORGANIZATION_NAME>
<ORGANIZATION_NAME1>WROC System 3</ORGANIZATION_NAME1>
<ORGANIZATION_NAME2></ORGANIZATION_NAME2>
<ORGANIZATION_NAME3></ORGANIZATION_NAME3>
<ALT_ORGANIZATION_NAME></ALT_ORGANIZATION_NAME>
<FORCED_COUNTY_NAME></FORCED_COUNTY_NAME>
<COUNTY_NAME1></COUNTY_NAME1>
<COUNTY_NAME2></COUNTY_NAME2>
<ALT_COUNTY_NAME></ALT_COUNTY_NAME>
<FORCED_CATEGORY_NAME></FORCED_CATEGORY_NAME>
<CAT_CODE></CAT_CODE>
<CATEGORY_NAME1></CATEGORY_NAME1>
<CATEGORY_NAME2></CATEGORY_NAME2>
<FORCED_STATUS_NAME></FORCED_STATUS_NAME>
<STATUS_NAME1></STATUS_NAME1>
<STATUS_NAME2></STATUS_NAME2>
<STATUS_NAME3></STATUS_NAME3>
<ALT_STATUS_TEXT></ALT_STATUS_TEXT>
<STATUS_CODE></STATUS_CODE>
<STATUS2_NAME1></STATUS2_NAME1>
<STATUS2_NAME2></STATUS2_NAME2>
<STATUS2_NAME3></STATUS2_NAME3>
<STATUS_CODE2></STATUS_CODE2>
<EXPIRATION></EXPIRATION>
<UPDATED></UPDATED>
<COMMENTS_LINE1></COMMENTS_LINE1>
<COMMENTS_LINE2></COMMENTS_LINE2>
<COMMENTS_LINE3></COMMENTS_LINE3>
<ADDRESS1></ADDRESS1>
<ADDRESS2></ADDRESS2>
<CITY></CITY>
<STATE></STATE>
<ZIPCODE></ZIPCODE>
<ORGANIZATION_HOMEPAGE></ORGANIZATION_HOMEPAGE>
</RECORD>
<RECORD>
<REC_ID>89996</REC_ID>
<FORCED_ORGANIZATION_NAME>WROC System 4</FORCED_ORGANIZATION_NAME>
<ORGANIZATION_NAME1>WROC System 4</ORGANIZATION_NAME1>
<ORGANIZATION_NAME2></ORGANIZATION_NAME2>
<ORGANIZATION_NAME3></ORGANIZATION_NAME3>
<ALT_ORGANIZATION_NAME></ALT_ORGANIZATION_NAME>
<FORCED_COUNTY_NAME></FORCED_COUNTY_NAME>
<COUNTY_NAME1></COUNTY_NAME1>
<COUNTY_NAME2></COUNTY_NAME2>
<ALT_COUNTY_NAME></ALT_COUNTY_NAME>
<FORCED_CATEGORY_NAME></FORCED_CATEGORY_NAME>
<CAT_CODE></CAT_CODE>
<CATEGORY_NAME1></CATEGORY_NAME1>
<CATEGORY_NAME2></CATEGORY_NAME2>
<FORCED_STATUS_NAME></FORCED_STATUS_NAME>
<STATUS_NAME1></STATUS_NAME1>
<STATUS_NAME2></STATUS_NAME2>
<STATUS_NAME3></STATUS_NAME3>
<ALT_STATUS_TEXT></ALT_STATUS_TEXT>
<STATUS_CODE></STATUS_CODE>
<STATUS2_NAME1></STATUS2_NAME1>
<STATUS2_NAME2></STATUS2_NAME2>
<STATUS2_NAME3></STATUS2_NAME3>
<STATUS_CODE2></STATUS_CODE2>
<EXPIRATION></EXPIRATION>
<UPDATED></UPDATED>
<COMMENTS_LINE1></COMMENTS_LINE1>
<COMMENTS_LINE2></COMMENTS_LINE2>
<COMMENTS_LINE3></COMMENTS_LINE3>
<ADDRESS1></ADDRESS1>
<ADDRESS2></ADDRESS2>
<CITY></CITY>
<STATE></STATE>
<ZIPCODE></ZIPCODE>
<ORGANIZATION_HOMEPAGE></ORGANIZATION_HOMEPAGE>
</RECORD>
<RECORD>
<REC_ID>89716</REC_ID>
<FORCED_ORGANIZATION_NAME>Y. W. C. P. Charter School</FORCED_ORGANIZATION_NAME>
<ORGANIZATION_NAME1>Y. W. C. P. Charter School</ORGANIZATION_NAME1>
<ORGANIZATION_NAME2></ORGANIZATION_NAME2>
<ORGANIZATION_NAME3></ORGANIZATION_NAME3>
<ALT_ORGANIZATION_NAME></ALT_ORGANIZATION_NAME>
<FORCED_COUNTY_NAME></FORCED_COUNTY_NAME>
<COUNTY_NAME1></COUNTY_NAME1>
<COUNTY_NAME2></COUNTY_NAME2>
<ALT_COUNTY_NAME></ALT_COUNTY_NAME>
<FORCED_CATEGORY_NAME></FORCED_CATEGORY_NAME>
<CAT_CODE></CAT_CODE>
<CATEGORY_NAME1></CATEGORY_NAME1>
<CATEGORY_NAME2></CATEGORY_NAME2>
<FORCED_STATUS_NAME></FORCED_STATUS_NAME>
<STATUS_NAME1></STATUS_NAME1>
<STATUS_NAME2></STATUS_NAME2>
<STATUS_NAME3></STATUS_NAME3>
<ALT_STATUS_TEXT></ALT_STATUS_TEXT>
<STATUS_CODE></STATUS_CODE>
<STATUS2_NAME1></STATUS2_NAME1>
<STATUS2_NAME2></STATUS2_NAME2>
<STATUS2_NAME3></STATUS2_NAME3>
<STATUS_CODE2></STATUS_CODE2>
<EXPIRATION></EXPIRATION>
<UPDATED></UPDATED>
<COMMENTS_LINE1></COMMENTS_LINE1>
<COMMENTS_LINE2></COMMENTS_LINE2>
<COMMENTS_LINE3></COMMENTS_LINE3>
<ADDRESS1>1001 lake Ave</ADDRESS1>
<ADDRESS2></ADDRESS2>
<CITY>Rochester</CITY>
<STATE></STATE>
<ZIPCODE>14613</ZIPCODE>
<ORGANIZATION_HOMEPAGE></ORGANIZATION_HOMEPAGE>
</RECORD>
<RECORD>
<REC_ID>89575</REC_ID>
<FORCED_ORGANIZATION_NAME>Yates Office Aging-Transportation</FORCED_ORGANIZATION_NAME>
<ORGANIZATION_NAME1>Yates Office Aging-Transportation</ORGANIZATION_NAME1>
<ORGANIZATION_NAME2></ORGANIZATION_NAME2>
<ORGANIZATION_NAME3></ORGANIZATION_NAME3>
<ALT_ORGANIZATION_NAME></ALT_ORGANIZATION_NAME>
<FORCED_COUNTY_NAME></FORCED_COUNTY_NAME>
<COUNTY_NAME1></COUNTY_NAME1>
<COUNTY_NAME2></COUNTY_NAME2>
<ALT_COUNTY_NAME></ALT_COUNTY_NAME>
<FORCED_CATEGORY_NAME></FORCED_CATEGORY_NAME>
<CAT_CODE></CAT_CODE>
<CATEGORY_NAME1></CATEGORY_NAME1>
<CATEGORY_NAME2></CATEGORY_NAME2>
<FORCED_STATUS_NAME></FORCED_STATUS_NAME>
<STATUS_NAME1></STATUS_NAME1>
<STATUS_NAME2></STATUS_NAME2>
<STATUS_NAME3></STATUS_NAME3>
<ALT_STATUS_TEXT></ALT_STATUS_TEXT>
<STATUS_CODE></STATUS_CODE>
<STATUS2_NAME1></STATUS2_NAME1>
<STATUS2_NAME2></STATUS2_NAME2>
<STATUS2_NAME3></STATUS2_NAME3>
<STATUS_CODE2></STATUS_CODE2>
<EXPIRATION></EXPIRATION>
<UPDATED></UPDATED>
<COMMENTS_LINE1></COMMENTS_LINE1>
<COMMENTS_LINE2></COMMENTS_LINE2>
<COMMENTS_LINE3></COMMENTS_LINE3>
<ADDRESS1></ADDRESS1>
<ADDRESS2></ADDRESS2>
<CITY></CITY>
<STATE></STATE>
<ZIPCODE></ZIPCODE>
<ORGANIZATION_HOMEPAGE></ORGANIZATION_HOMEPAGE>
</RECORD>
<RECORD>
<REC_ID>89823</REC_ID>
<FORCED_ORGANIZATION_NAME>A Time for Dance</FORCED_ORGANIZATION_NAME>
<ORGANIZATION_NAME1>A Time for Dance</ORGANIZATION_NAME1>
<ORGANIZATION_NAME2></ORGANIZATION_NAME2>
<ORGANIZATION_NAME3></ORGANIZATION_NAME3>
<ALT_ORGANIZATION_NAME></ALT_ORGANIZATION_NAME>
<FORCED_COUNTY_NAME></FORCED_COUNTY_NAME>
<COUNTY_NAME1></COUNTY_NAME1>
<COUNTY_NAME2></COUNTY_NAME2>
<ALT_COUNTY_NAME></ALT_COUNTY_NAME>
<FORCED_CATEGORY_NAME>Businesses</FORCED_CATEGORY_NAME>
<CAT_CODE>2</CAT_CODE>
<CATEGORY_NAME1>Businesses</CATEGORY_NAME1>
<CATEGORY_NAME2></CATEGORY_NAME2>
<FORCED_STATUS_NAME></FORCED_STATUS_NAME>
<STATUS_NAME1></STATUS_NAME1>
<STATUS_NAME2></STATUS_NAME2>
<STATUS_NAME3></STATUS_NAME3>
<ALT_STATUS_TEXT></ALT_STATUS_TEXT>
<STATUS_CODE></STATUS_CODE>
<STATUS2_NAME1></STATUS2_NAME1>
<STATUS2_NAME2></STATUS2_NAME2>
<STATUS2_NAME3></STATUS2_NAME3>
<STATUS_CODE2></STATUS_CODE2>
<EXPIRATION></EXPIRATION>
<UPDATED></UPDATED>
<COMMENTS_LINE1></COMMENTS_LINE1>
<COMMENTS_LINE2></COMMENTS_LINE2>
<COMMENTS_LINE3></COMMENTS_LINE3>
<ADDRESS1>3765 Chili Ave</ADDRESS1>
<ADDRESS2></ADDRESS2>
<CITY>Rochester</CITY>
<STATE>NY</STATE>
<ZIPCODE>14624</ZIPCODE>
<ORGANIZATION_HOMEPAGE></ORGANIZATION_HOMEPAGE>
</RECORD>
<RECORD>
<REC_ID>88752</REC_ID>
<FORCED_ORGANIZATION_NAME>A.B.C.</FORCED_ORGANIZATION_NAME>
<ORGANIZATION_NAME1>A.B.C.</ORGANIZATION_NAME1>
<ORGANIZATION_NAME2></ORGANIZATION_NAME2>
<ORGANIZATION_NAME3></ORGANIZATION_NAME3>
<ALT_ORGANIZATION_NAME></ALT_ORGANIZATION_NAME>
<FORCED_COUNTY_NAME>Monroe County</FORCED_COUNTY_NAME>
<COUNTY_NAME1>Monroe County</COUNTY_NAME1>
<COUNTY_NAME2>Monr</COUNTY_NAME2>
<ALT_COUNTY_NAME></ALT_COUNTY_NAME>
<FORCED_CATEGORY_NAME>Businesses</FORCED_CATEGORY_NAME>
<CAT_CODE>2</CAT_CODE>
<CATEGORY_NAME1>Businesses</CATEGORY_NAME1>
<CATEGORY_NAME2></CATEGORY_NAME2>
<FORCED_STATUS_NAME></FORCED_STATUS_NAME>
<STATUS_NAME1></STATUS_NAME1>
<STATUS_NAME2></STATUS_NAME2>
<STATUS_NAME3></STATUS_NAME3>
<ALT_STATUS_TEXT></ALT_STATUS_TEXT>
<STATUS_CODE></STATUS_CODE>
<STATUS2_NAME1></STATUS2_NAME1>
<STATUS2_NAME2></STATUS2_NAME2>
<STATUS2_NAME3></STATUS2_NAME3>
<STATUS_CODE2></STATUS_CODE2>
<EXPIRATION></EXPIRATION>
<UPDATED></UPDATED>
<COMMENTS_LINE1></COMMENTS_LINE1>
<COMMENTS_LINE2></COMMENTS_LINE2>
<COMMENTS_LINE3></COMMENTS_LINE3>
<ADDRESS1>550 East Main St.</ADDRESS1>
<ADDRESS2></ADDRESS2>
<CITY>Rochester</CITY>
<STATE>NY</STATE>
<ZIPCODE>14604</ZIPCODE>
<ORGANIZATION_HOMEPAGE></ORGANIZATION_HOMEPAGE>
</RECORD>
<RECORD>
<REC_ID>88750</REC_ID>
<FORCED_ORGANIZATION_NAME>A.R. Arena Products</FORCED_ORGANIZATION_NAME>
<ORGANIZATION_NAME1>A.R. Arena Products</ORGANIZATION_NAME1>
<ORGANIZATION_NAME2></ORGANIZATION_NAME2>
<ORGANIZATION_NAME3>A.R.</ORGANIZATION_NAME3>
<ALT_ORGANIZATION_NAME></ALT_ORGANIZATION_NAME>
<FORCED_COUNTY_NAME>Monroe County</FORCED_COUNTY_NAME>
<COUNTY_NAME1>Monroe County</COUNTY_NAME1>
<COUNTY_NAME2>Monr</COUNTY_NAME2>
<ALT_COUNTY_NAME></ALT_COUNTY_NAME>
<FORCED_CATEGORY_NAME>Businesses</FORCED_CATEGORY_NAME>
<CAT_CODE>2</CAT_CODE>
<CATEGORY_NAME1>Businesses</CATEGORY_NAME1>
<CATEGORY_NAME2></CATEGORY_NAME2>
<FORCED_STATUS_NAME></FORCED_STATUS_NAME>
<STATUS_NAME1></STATUS_NAME1>
<STATUS_NAME2></STATUS_NAME2>
<STATUS_NAME3></STATUS_NAME3>
<ALT_STATUS_TEXT></ALT_STATUS_TEXT>
<STATUS_CODE></STATUS_CODE>
<STATUS2_NAME1></STATUS2_NAME1>
<STATUS2_NAME2></STATUS2_NAME2>
<STATUS2_NAME3></STATUS2_NAME3>
<STATUS_CODE2></STATUS_CODE2>
<EXPIRATION></EXPIRATION>
<UPDATED></UPDATED>
<COMMENTS_LINE1></COMMENTS_LINE1>
<COMMENTS_LINE2></COMMENTS_LINE2>
<COMMENTS_LINE3></COMMENTS_LINE3>
<ADDRESS1>2101 Mt. Read Blvd.</ADDRESS1>
<ADDRESS2></ADDRESS2>
<CITY>Rochester</CITY>
<STATE>NY</STATE>
<ZIPCODE>14615</ZIPCODE>
<ORGANIZATION_HOMEPAGE></ORGANIZATION_HOMEPAGE>
</RECORD>
<RECORD>
<REC_ID>89856</REC_ID>
<FORCED_ORGANIZATION_NAME>A.R.C. of Orleans</FORCED_ORGANIZATION_NAME>
<ORGANIZATION_NAME1>A.R.C. of Orleans</ORGANIZATION_NAME1>
<ORGANIZATION_NAME2></ORGANIZATION_NAME2>
<ORGANIZATION_NAME3></ORGANIZATION_NAME3>
<ALT_ORGANIZATION_NAME></ALT_ORGANIZATION_NAME>
<FORCED_COUNTY_NAME>Orleans County</FORCED_COUNTY_NAME>
<COUNTY_NAME1>Orleans County</COUNTY_NAME1>
<COUNTY_NAME2>Orle</COUNTY_NAME2>
<ALT_COUNTY_NAME></ALT_COUNTY_NAME>
<FORCED_CATEGORY_NAME>Businesses</FORCED_CATEGORY_NAME>
<CAT_CODE>2</CAT_CODE>
<CATEGORY_NAME1>Businesses</CATEGORY_NAME1>
<CATEGORY_NAME2></CATEGORY_NAME2>
<FORCED_STATUS_NAME></FORCED_STATUS_NAME>
<STATUS_NAME1></STATUS_NAME1>
<STATUS_NAME2></STATUS_NAME2>
<STATUS_NAME3></STATUS_NAME3>
<ALT_STATUS_TEXT></ALT_STATUS_TEXT>
<STATUS_CODE></STATUS_CODE>
<STATUS2_NAME1></STATUS2_NAME1>
<STATUS2_NAME2></STATUS2_NAME2>
<STATUS2_NAME3></STATUS2_NAME3>
<STATUS_CODE2></STATUS_CODE2>
<EXPIRATION></EXPIRATION>
<UPDATED></UPDATED>
<COMMENTS_LINE1></COMMENTS_LINE1>
<COMMENTS_LINE2></COMMENTS_LINE2>
<COMMENTS_LINE3></COMMENTS_LINE3>
<ADDRESS1>Robert E Waters-Orleans</ADDRESS1>
<ADDRESS2>215 Washington Street</ADDRESS2>
<CITY>Albion</CITY>
<STATE>NY</STATE>
<ZIPCODE>14411</ZIPCODE>
<ORGANIZATION_HOMEPAGE></ORGANIZATION_HOMEPAGE>
</RECORD>
<RECORD>
<REC_ID>89542</REC_ID>
<FORCED_ORGANIZATION_NAME>A.R.C. of Yates</FORCED_ORGANIZATION_NAME>
<ORGANIZATION_NAME1>A.R.C. of Yates</ORGANIZATION_NAME1>
<ORGANIZATION_NAME2></ORGANIZATION_NAME2>
<ORGANIZATION_NAME3></ORGANIZATION_NAME3>
<ALT_ORGANIZATION_NAME></ALT_ORGANIZATION_NAME>
<FORCED_COUNTY_NAME>Yates County</FORCED_COUNTY_NAME>
<COUNTY_NAME1>Yates County</COUNTY_NAME1>
<COUNTY_NAME2>Yate</COUNTY_NAME2>
<ALT_COUNTY_NAME></ALT_COUNTY_NAME>
<FORCED_CATEGORY_NAME>Businesses</FORCED_CATEGORY_NAME>
<CAT_CODE>2</CAT_CODE>
<CATEGORY_NAME1>Businesses</CATEGORY_NAME1>
<CATEGORY_NAME2></CATEGORY_NAME2>
<FORCED_STATUS_NAME></FORCED_STATUS_NAME>
<STATUS_NAME1></STATUS_NAME1>
<STATUS_NAME2></STATUS_NAME2>
<STATUS_NAME3></STATUS_NAME3>
<ALT_STATUS_TEXT></ALT_STATUS_TEXT>
<STATUS_CODE></STATUS_CODE>
<STATUS2_NAME1></STATUS2_NAME1>
<STATUS2_NAME2></STATUS2_NAME2>
<STATUS2_NAME3></STATUS2_NAME3>
<STATUS_CODE2></STATUS_CODE2>
<EXPIRATION></EXPIRATION>
<UPDATED></UPDATED>
<COMMENTS_LINE1></COMMENTS_LINE1>
<COMMENTS_LINE2></COMMENTS_LINE2>
<COMMENTS_LINE3></COMMENTS_LINE3>
<ADDRESS1>235 North Ave.</ADDRESS1>
<ADDRESS2></ADDRESS2>
<CITY>Penn Yan</CITY>
<STATE>NY</STATE>
<ZIPCODE>14527</ZIPCODE>
<ORGANIZATION_HOMEPAGE></ORGANIZATION_HOMEPAGE>
</RECORD>
<RECORD>
<REC_ID>88947</REC_ID>
<FORCED_ORGANIZATION_NAME>AA Tech</FORCED_ORGANIZATION_NAME>
<ORGANIZATION_NAME1>AA Tech</ORGANIZATION_NAME1>
<ORGANIZATION_NAME2></ORGANIZATION_NAME2>
<ORGANIZATION_NAME3></ORGANIZATION_NAME3>
<ALT_ORGANIZATION_NAME></ALT_ORGANIZATION_NAME>
<FORCED_COUNTY_NAME>Wayne County</FORCED_COUNTY_NAME>
<COUNTY_NAME1>Wayne County</COUNTY_NAME1>
<COUNTY_NAME2>Wayn</COUNTY_NAME2>
<ALT_COUNTY_NAME></ALT_COUNTY_NAME>
<FORCED_CATEGORY_NAME>Businesses</FORCED_CATEGORY_NAME>
<CAT_CODE>2</CAT_CODE>
<CATEGORY_NAME1>Businesses</CATEGORY_NAME1>
<CATEGORY_NAME2></CATEGORY_NAME2>
<FORCED_STATUS_NAME></FORCED_STATUS_NAME>
<STATUS_NAME1></STATUS_NAME1>
<STATUS_NAME2></STATUS_NAME2>
<STATUS_NAME3></STATUS_NAME3>
<ALT_STATUS_TEXT></ALT_STATUS_TEXT>
<STATUS_CODE></STATUS_CODE>
<STATUS2_NAME1></STATUS2_NAME1>
<STATUS2_NAME2></STATUS2_NAME2>
<STATUS2_NAME3></STATUS2_NAME3>
<STATUS_CODE2></STATUS_CODE2>
<EXPIRATION></EXPIRATION>
<UPDATED></UPDATED>
<COMMENTS_LINE1></COMMENTS_LINE1>
<COMMENTS_LINE2></COMMENTS_LINE2>
<COMMENTS_LINE3></COMMENTS_LINE3>
<ADDRESS1>124 Columbia Street</ADDRESS1>
<ADDRESS2></ADDRESS2>
<CITY>Clyde</CITY>
<STATE>NY</STATE>
<ZIPCODE>14433</ZIPCODE>
<ORGANIZATION_HOMEPAGE></ORGANIZATION_HOMEPAGE>
</RECORD>
<RECORD>
<REC_ID>88559</REC_ID>
<FORCED_ORGANIZATION_NAME>AAA Driver Safety Pgm</FORCED_ORGANIZATION_NAME>
<ORGANIZATION_NAME1>AAA Driver Safety Pgm</ORGANIZATION_NAME1>
<ORGANIZATION_NAME2></ORGANIZATION_NAME2>
<ORGANIZATION_NAME3></ORGANIZATION_NAME3>
<ALT_ORGANIZATION_NAME></ALT_ORGANIZATION_NAME>
<FORCED_COUNTY_NAME>Monroe County</FORCED_COUNTY_NAME>
<COUNTY_NAME1>Monroe County</COUNTY_NAME1>
<COUNTY_NAME2>Monr</COUNTY_NAME2>
<ALT_COUNTY_NAME></ALT_COUNTY_NAME>
<FORCED_CATEGORY_NAME>Businesses</FORCED_CATEGORY_NAME>
<CAT_CODE>2</CAT_CODE>
<CATEGORY_NAME1>Businesses</CATEGORY_NAME1>
<CATEGORY_NAME2></CATEGORY_NAME2>
<FORCED_STATUS_NAME></FORCED_STATUS_NAME>
<STATUS_NAME1></STATUS_NAME1>
<STATUS_NAME2></STATUS_NAME2>
<STATUS_NAME3></STATUS_NAME3>
<ALT_STATUS_TEXT></ALT_STATUS_TEXT>
<STATUS_CODE></STATUS_CODE>
<STATUS2_NAME1></STATUS2_NAME1>
<STATUS2_NAME2></STATUS2_NAME2>
<STATUS2_NAME3></STATUS2_NAME3>
<STATUS_CODE2></STATUS_CODE2>
<EXPIRATION></EXPIRATION>
<UPDATED></UPDATED>
<COMMENTS_LINE1></COMMENTS_LINE1>
<COMMENTS_LINE2></COMMENTS_LINE2>
<COMMENTS_LINE3></COMMENTS_LINE3>
<ADDRESS1>7485 Henry Clay Blvd.</ADDRESS1>
<ADDRESS2></ADDRESS2>
<CITY>Liverpool</CITY>
<STATE>NY</STATE>
<ZIPCODE>13088</ZIPCODE>
<ORGANIZATION_HOMEPAGE></ORGANIZATION_HOMEPAGE>
</RECORD>
<RECORD>
<REC_ID>88944</REC_ID>
<FORCED_ORGANIZATION_NAME>AAA Travel Branches</FORCED_ORGANIZATION_NAME>
<ORGANIZATION_NAME1>AAA Travel Branches</ORGANIZATION_NAME1>
<ORGANIZATION_NAME2></ORGANIZATION_NAME2>
<ORGANIZATION_NAME3></ORGANIZATION_NAME3>
<ALT_ORGANIZATION_NAME></ALT_ORGANIZATION_NAME>
<FORCED_COUNTY_NAME>Monroe County</FORCED_COUNTY_NAME>
<COUNTY_NAME1>Monroe County</COUNTY_NAME1>
<COUNTY_NAME2>Monr</COUNTY_NAME2>
<ALT_COUNTY_NAME></ALT_COUNTY_NAME>
<FORCED_CATEGORY_NAME>Businesses</FORCED_CATEGORY_NAME>
<CAT_CODE>2</CAT_CODE>
<CATEGORY_NAME1>Businesses</CATEGORY_NAME1>
<CATEGORY_NAME2></CATEGORY_NAME2>
<FORCED_STATUS_NAME></FORCED_STATUS_NAME>
<STATUS_NAME1></STATUS_NAME1>
<STATUS_NAME2></STATUS_NAME2>
<STATUS_NAME3></STATUS_NAME3>
<ALT_STATUS_TEXT></ALT_STATUS_TEXT>
<STATUS_CODE></STATUS_CODE>
<STATUS2_NAME1></STATUS2_NAME1>
<STATUS2_NAME2></STATUS2_NAME2>
<STATUS2_NAME3></STATUS2_NAME3>
<STATUS_CODE2></STATUS_CODE2>
<EXPIRATION></EXPIRATION>
<UPDATED></UPDATED>
<COMMENTS_LINE1></COMMENTS_LINE1>
<COMMENTS_LINE2></COMMENTS_LINE2>
<COMMENTS_LINE3></COMMENTS_LINE3>
<ADDRESS1>7485 Henry Clay Blvd.</ADDRESS1>
<ADDRESS2></ADDRESS2>
<CITY>Liverpool</CITY>
<STATE>NY</STATE>
<ZIPCODE>13088</ZIPCODE>
<ORGANIZATION_HOMEPAGE></ORGANIZATION_HOMEPAGE>
</RECORD>
<RECORD>
<REC_ID>88512</REC_ID>
<FORCED_ORGANIZATION_NAME>ABC Head Start</FORCED_ORGANIZATION_NAME>
<ORGANIZATION_NAME1>ABC Head Start</ORGANIZATION_NAME1>
<ORGANIZATION_NAME2></ORGANIZATION_NAME2>
<ORGANIZATION_NAME3>ABC</ORGANIZATION_NAME3>
<ALT_ORGANIZATION_NAME></ALT_ORGANIZATION_NAME>
<FORCED_COUNTY_NAME>Monroe County</FORCED_COUNTY_NAME>
<COUNTY_NAME1>Monroe County</COUNTY_NAME1>
<COUNTY_NAME2>Monr</COUNTY_NAME2>
<ALT_COUNTY_NAME></ALT_COUNTY_NAME>
<FORCED_CATEGORY_NAME>Businesses</FORCED_CATEGORY_NAME>
<CAT_CODE>2</CAT_CODE>
<CATEGORY_NAME1>Businesses</CATEGORY_NAME1>
<CATEGORY_NAME2></CATEGORY_NAME2>
<FORCED_STATUS_NAME></FORCED_STATUS_NAME>
<STATUS_NAME1></STATUS_NAME1>
<STATUS_NAME2></STATUS_NAME2>
<STATUS_NAME3></STATUS_NAME3>
<ALT_STATUS_TEXT></ALT_STATUS_TEXT>
<STATUS_CODE></STATUS_CODE>
<STATUS2_NAME1></STATUS2_NAME1>
<STATUS2_NAME2></STATUS2_NAME2>
<STATUS2_NAME3></STATUS2_NAME3>
<STATUS_CODE2></STATUS_CODE2>
<EXPIRATION></EXPIRATION>
<UPDATED></UPDATED>
<COMMENTS_LINE1></COMMENTS_LINE1>
<COMMENTS_LINE2></COMMENTS_LINE2>
<COMMENTS_LINE3></COMMENTS_LINE3>
<ADDRESS1>550 East Main Street</ADDRESS1>
<ADDRESS2></ADDRESS2>
<CITY>Rochester</CITY>
<STATE>NY</STATE>
<ZIPCODE>14604</ZIPCODE>
<ORGANIZATION_HOMEPAGE></ORGANIZATION_HOMEPAGE>
</RECORD>
<RECORD>
<REC_ID>88777</REC_ID>
<FORCED_ORGANIZATION_NAME>ABVI</FORCED_ORGANIZATION_NAME>
<ORGANIZATION_NAME1>ABVI</ORGANIZATION_NAME1>
<ORGANIZATION_NAME2></ORGANIZATION_NAME2>
<ORGANIZATION_NAME3></ORGANIZATION_NAME3>
<ALT_ORGANIZATION_NAME></ALT_ORGANIZATION_NAME>
<FORCED_COUNTY_NAME>Monroe County</FORCED_COUNTY_NAME>
<COUNTY_NAME1>Monroe County</COUNTY_NAME1>
<COUNTY_NAME2>Monr</COUNTY_NAME2>
<ALT_COUNTY_NAME></ALT_COUNTY_NAME>
<FORCED_CATEGORY_NAME>Businesses</FORCED_CATEGORY_NAME>
<CAT_CODE>2</CAT_CODE>
<CATEGORY_NAME1>Businesses</CATEGORY_NAME1>
<CATEGORY_NAME2></CATEGORY_NAME2>
<FORCED_STATUS_NAME></FORCED_STATUS_NAME>
<STATUS_NAME1></STATUS_NAME1>
<STATUS_NAME2></STATUS_NAME2>
<STATUS_NAME3></STATUS_NAME3>
<ALT_STATUS_TEXT></ALT_STATUS_TEXT>
<STATUS_CODE></STATUS_CODE>
<STATUS2_NAME1></STATUS2_NAME1>
<STATUS2_NAME2></STATUS2_NAME2>
<STATUS2_NAME3></STATUS2_NAME3>
<STATUS_CODE2></STATUS_CODE2>
<EXPIRATION></EXPIRATION>
<UPDATED></UPDATED>
<COMMENTS_LINE1></COMMENTS_LINE1>
<COMMENTS_LINE2></COMMENTS_LINE2>
<COMMENTS_LINE3></COMMENTS_LINE3>
<ADDRESS1>422 South Clinton Ave.</ADDRESS1>
<ADDRESS2></ADDRESS2>
<CITY>Rochester</CITY>
<STATE></STATE>
<ZIPCODE>14620</ZIPCODE>
<ORGANIZATION_HOMEPAGE></ORGANIZATION_HOMEPAGE>
</RECORD>
<RECORD>
<REC_ID>88618</REC_ID>
<FORCED_ORGANIZATION_NAME>Academy for Career Dev.</FORCED_ORGANIZATION_NAME>
<ORGANIZATION_NAME1>Academy for Career Dev.</ORGANIZATION_NAME1>
<ORGANIZATION_NAME2></ORGANIZATION_NAME2>
<ORGANIZATION_NAME3>Acad</ORGANIZATION_NAME3>
<ALT_ORGANIZATION_NAME></ALT_ORGANIZATION_NAME>
<FORCED_COUNTY_NAME>Monroe County</FORCED_COUNTY_NAME>
<COUNTY_NAME1>Monroe County</COUNTY_NAME1>
<COUNTY_NAME2>Monr</COUNTY_NAME2>
<ALT_COUNTY_NAME></ALT_COUNTY_NAME>
<FORCED_CATEGORY_NAME>Schools</FORCED_CATEGORY_NAME>
<CAT_CODE>1</CAT_CODE>
<CATEGORY_NAME1>Schools</CATEGORY_NAME1>
<CATEGORY_NAME2></CATEGORY_NAME2>
<FORCED_STATUS_NAME></FORCED_STATUS_NAME>
<STATUS_NAME1></STATUS_NAME1>
<STATUS_NAME2></STATUS_NAME2>
<STATUS_NAME3></STATUS_NAME3>
<ALT_STATUS_TEXT></ALT_STATUS_TEXT>
<STATUS_CODE></STATUS_CODE>
<STATUS2_NAME1></STATUS2_NAME1>
<STATUS2_NAME2></STATUS2_NAME2>
<STATUS2_NAME3></STATUS2_NAME3>
<STATUS_CODE2></STATUS_CODE2>
<EXPIRATION></EXPIRATION>
<UPDATED></UPDATED>
<COMMENTS_LINE1></COMMENTS_LINE1>
<COMMENTS_LINE2></COMMENTS_LINE2>
<COMMENTS_LINE3></COMMENTS_LINE3>
<ADDRESS1>1349 South Avenue</ADDRESS1>
<ADDRESS2></ADDRESS2>
<CITY>Roch</CITY>
<STATE>14</STATE>
<ZIPCODE></ZIPCODE>
<ORGANIZATION_HOMEPAGE></ORGANIZATION_HOMEPAGE>
</RECORD>
<RECORD>